alphagov/govuk-aws

terraform/data/govuk-vpc/integration.tfvars
govuk-vpc became infra-vpc, we forgot to remove one file.
=> Remove old vpc data file

terraform/projects/app-calculators-frontend/main.tf
The tags need underscores rather than hyphens for aws_migration.
=> Bugfix Calculators Frontend

terraform/projects/app-logs-elasticsearch/integration.delana.backend, terraform/projects/app-logs-elasticsearch/main.tf, terraform/userdata/10-attach-volumes
Update the attach-volume snippet to use a device tag so we can
attach several volumes to an instance and continue doing the
LVM management with Puppet.
The EBS TF resource needs to include a 'Device' tag so we can attach
the volume to the right device during the instance initialisation.
Puppet already manages the devices and LVM configuration, but we'll
need to update the lvm module in Puppet to use the puppetlabs version
instead of our fork, as it fixes several bugs that prevented a disk
already formatted from working properly when a new instance is running
Puppet the first time.
=> Update volume snippet and logs-elasticsearch

terraform/projects/app-apt/main.tf
There are several places where 'apt-1' is incorrectly used as a name.
This changes these to use just 'apt' in line with the other projects.
=> Change 'apt-1' to 'apt'

doc/ssh-configs/README.md, doc/ssh-configs/govuk-ssh
We will probably be working in multiple environments with multiple stacks. I don't want to have to populate my SSH config with long lists of the different stacks, so I wrote a wrapper which calls a script on the jumpboxes to find the different machines I want to log into to.
This is an alternative to `ec2ssh`. It's main feature is that it does not require maintaining a configuration file; just specify and go!
Depends on https://github.com/alphagov/govuk-puppet/pull/6151
=> Add govuk-ssh wrapper

terraform/data/app-exception-handler/integration/common.tfvars, terraform/data/app-exception-handler/integration/delana.tfvars, terraform/data/app-exception-handler/integration/issam.tfvars, terraform/data/app-graphite/integration/common.tfvars, terraform/data/app-graphite/integration/delana.tfvars, terraform/data/app-logs-elasticsearch/integration/common.tfvars, terraform/data/app-logs-elasticsearch/integration/delana.tfvars, terraform/data/app-mysql-primary/integration/common.tfvars, terraform/data/app-puppetmaster/integration/common.tfvars, terraform/data/common/integration/common.tfvars, terraform/data/common/integration/delana.tfvars, terraform/data/common/integration/issam.tfvars, terraform/data/infra-networking/integration/govuk.tfvars, terraform/data/infra-root-dns-zones/integration/govuk.tfvars, terraform/data/infra-stack-dns-zones/integration/delana.tfvars, terraform/data/infra-stack-dns-zones/integration/issam.tfvars, terraform/data/infra-vpc/integration/govuk.tfvars
Many tfvars files have a leading empty line or variable names surrounded
by double quotes, these aren't needed so remove them.
=> Remove un-needed whitespace and double quotes

terraform/projects/app-mapit/main.tf
While this didn't error in the plan or apply, having the incorrect tag assigned to the volume meant that the volume didn't get mounted when the instances were started.
=> Update tag for volume

terraform/data/app-logs-elasticsearch/integration/delana.tfvars, terraform/projects/app-logs-elasticsearch/additional_policy.json, terraform/projects/app-logs-elasticsearch/main.tf
This commit updates the logs_elasticsearch to:
- add instance 2 and 3 by repeating the work for instance 1
- add a new tag called "cluster_name" that will be used by Puppet to
join elasticsearch instances to a cluster using ec2 discovery
- Amend IAM permissions to allow Elasticsearch to DescribeInstances
=> Update logs_elasticsearch application

terraform/projects/app-puppetmaster/main.tf
I had an instance where the Puppetmaster ran out of memory, and it's a
pain for the Puppetmaster to struggle of resources when we're testing
things.
This doubles the amount of memory.
=> Increase resources of Puppetmaster

doc/guides/environment-provisioning.md, terraform/data/common/integration/blue.tfvars, terraform/data/common/integration/govuk.tfvars, terraform/projects/infra-security-groups/integration.govuk.backend, tools/aws-copy-puppet-setup.sh, tools/aws-push-puppet.sh
They should share a set of security groups to ensure all applications can
reach each other, no matter if they are blue or green.
=> [WIP] The blue and green stacks will both live under the govuk vpc

terraform/projects/infra-networking/integration.blue.backend, terraform/projects/infra-root-dns-zones/integration.backend, terraform/projects/infra-root-dns-zones/integration.blue.backend, terraform/projects/infra-vpc/integration.blue.backend
The app 'blue' stack will use the 'govuk' VPC, root DNS and network infra stacks,
so we don't need those 'blue' backend files.
Also, remove an old integration.backend, probably left behind during the last
code refactoring.
=> Remove infra blue stacks

terraform/projects/app-backend/main.tf
All the DNS for the backend hosts and ELBs should be on the
private network
=> Backend should have an internal ELB

terraform/userdata/20-puppet-client
Use a unique certificate name to avoid issues when DHCP ips are reassigned.
Add CSR extensions to Puppet certificates to enable policy based autosigning
and easier clean up.
=> Add Puppet CSR extensions and update certname

terraform/projects/app-db-admin/main.tf
=> Use port 22 for the db_admin instances.

terraform/projects/infra-security-groups/logs-redis.tf
The logship program connects directly to redis and so
needs this access
=> Allow all managed machines to connect to logs redis

tools/build-terraform-project.sh
This ensures that you don't accidentally copy local statefiles from other stacks.
There's an argument that a purge and init should happen for every plan and apply for safety.
=> Purge terraform dir on init

.pre-commit-config.yaml, Jenkinsfile, tools/json-check.sh
Check that JSON is valid using `jq`. This is a lightweight way to ensure that any IAM policies that are being submitted are valid JSON which will hopefully save a little time or pain.
=> Add JSON check tool

terraform/projects/app-puppetmaster/additional_policy.json, terraform/projects/app-puppetmaster/main.tf, terraform/userdata/20-puppetmaster, tools/aws-copy-puppet-setup.sh
Refactor the Puppetmaster project to move to puppetserver and support
policy-based autosign with AWS certificate extensions:
- Add additional policy to create tags on instances when the client
certificate is signed
- Increase puppetmaster root volume size
- Update puppetmaster userdata snippet to remove unrestricted autosign, as
we are going to use policies. The policy script will be installed in govuk-puppet
- Move openjdk package installation to govuk-puppet and gpg related gems to
bootstrap script. govuk-puppet is going to ensure these gems are absent after
installing the puppetserver package, as puppetserver uses its own gem tool.
=> Refactor Puppetmaster for Puppetserver

terraform/userdata/20-puppetmaster
The master section in the puppetmaster needs to configure the
certname to avoid having a certificate name with hostname instead
of instance Id.
=> Add certname to puppetmaster userdata

terraform/userdata/20-puppetmaster
We need the certname on the Puppet main section to make sure nothing
tries to use the hostname.
=> Add certname to puppet main section

terraform/projects/app-logging/main.tf
This is used to host a logstash jar and shouldn't be managed in this
project.
=> Remove bucket management from logging

terraform/projects/app-publishing-api/main.tf, terraform/projects/infra-security-groups/publishing-api.tf
This acts like a backend machine, so needs certificates.
Currently only listening on HTTP so LB will show as down, so apps are unable to speak to it.
=> Add certs to publishing-api

terraform/projects/infra-security-groups/mongo.tf
- The security group wasn't configured, which made backend apps eg
Maslow and Imminence sad when deploying them as they couldn't access
`mongo-1`.
=> Allow backend machines to access Mongo machines

terraform/data/common/integration/common.tfvars, terraform/projects/infra-security-groups/offsite_ssh.tf, terraform/projects/infra-security-groups/variables.tf
This allows SSH from the carrenza integration environment for the
purpose of syncing data
=> Allow ssh from carrenza integration

terraform/projects/app-db-admin/main.tf, terraform/projects/app-jumpbox/main.tf
- Upon trying to scp over a 21G publishing-api database dump, the
jumpbox ran out of disk space. Even compressed, when it gets to the
db-admin machine, it won't have enough space to uncompress it ready
for import, so increase the space available to 64G.
=> Increase disk space on jumpbox and db-admin machines

terraform/projects/app-calculators-frontend/main.tf, terraform/projects/app-frontend/main.tf, terraform/projects/app-performance-frontend/main.tf, terraform/projects/app-whitehall-frontend/main.tf
These are all hosts that have traffic routed to them from frontend_lb.
whitehall-frontend had an external ELB and record, but this is only accessed from the frontend_lb so should be internal.
The rest were missing service records.
=> Update DNS service records

terraform/data/common/integration/blue.tfvars, terraform/projects/app-graphite/main.tf, terraform/projects/infra-security-groups/graphite.tf
Monitoring needs access to graphite:443 internally
=> Add SGs to enable access to graphite:443 from monitoring

.blue.integration.env
When working with the build tool it's easier to source this file so you
don't have to pass in a bunch of parameters.
Overrides can still occur so it's a useful way of quickly setting up
your environment.
=> Add env file for blue integration

terraform/projects/app-db-admin/main.tf
This means that there's a fixed record from which db-admin is always accessible.
=> Add DNS record for db-admin

terraform/projects/app-cache/main.tf, terraform/projects/app-calculators-frontend/main.tf, terraform/projects/app-performance-backend/main.tf, terraform/projects/app-performance-frontend/main.tf, terraform/projects/app-search/main.tf
These ASGs should be resiable between environments. Also set the defaults
lower, we'll only run bigger groups in prod and perf test environments.
=> Allow dynamic autoscaling group values

terraform/modules/aws/rds_instance/main.tf, terraform/projects/app-mysql-primary/main.tf
This creates a parameter group for the mysql-primary RDS instance that
sets the `max_allowed_packet` to 1GB. The default AWS value is 4MB
which means database restores of databases with large blobs (e.g.
whitehall) will fail (with `ERROR 2006 (HY000) at line 8500: MySQL
server has gone away`).
As the parameter group name needs to be added to the `db_instance`
resource this adds a new variable to the RDS module,
`parameter_group_name` which passes this value to both the instance and
replica resources..
=> Set max_allowed_packet to 1GB for mysql in RDS

terraform/projects/app-draft-cache/main.tf
router-api also runs on draft-cache, so needs an internal DNS record.
=> Add DNS record for draft-router-api

terraform/projects/app-content-store/main.tf
It was using the wrong security group for the ELB.
=> Content Store fix

terraform/projects/app-logging/main.tf
They're not that load intensive, but everything connects to them so they need more than t2.micro.
=> Upgrade logging machines

terraform/projects/app-calculators-frontend/main.tf, terraform/projects/app-frontend-lb/main.tf, terraform/projects/app-frontend/main.tf
This adds the required DNS records and certificates to allow the cache instance to directly route requests to frontend and calculators-frontend, essentially bypassing frontend-lb.
This is something we wanted to do later on, and it makes sense to do it now because otherwise we will have conflicts in how we do DNS naming for apps and services.
It's also worth noting I fixed a bug where the wrong protocol was used with an LB listener, that meant that while requests were correctly being routed to tcp/80, they were still encrypted so nginx was unable to correctly parse the request.
=> Update frontend and calculators-frontend DNS names

terraform/modules/aws/rds_instance/main.tf
There needs to be a default otherwise terraform errors.
=> Set a default for parameter_group_name

terraform/projects/app-postgresql/main.tf
postgres-primary will host both existing postgres databases. Both of
these currently have 60GB each for data, this increases the storage in
RDS to give at least this much.
=> Increase postgres-primary storage to 120GB

terraform/projects/infra-wraith-bucket/integration.govuk.backend, terraform/projects/infra-wraith-bucket/main.tf, terraform/projects/infra-wraith-bucket/writer.tf
This is a world-readable bucket which will store the output of wraith
visual regression tests for frontend work. The bucket is writable only
by the created wraith_writer user. Access keys for this user need to be
generated separately.
=> Add s3 bucket for wraith output

terraform/projects/app-whitehall-backend/main.tf, terraform/projects/infra-security-groups/backend-redis.tf, terraform/projects/infra-security-groups/mongo.tf, terraform/projects/infra-security-groups/mysql-primary.tf
The whitehall machines and calculators-frontend needed access to some backend services. This opens up the security groups to allow them to do so.
https://trello.com/c/DS5stwo8/730-fix-frontend-flows
=> Allow further backend services access

doc/architecture/step-by-step.md, doc/guides/environment-provisioning.md, tools/build-terraform-project.sh
Update the build tool to run init on each run of the command. This is for safety reasons to ensure the modules and backend are correctly refreshed.
=> Run init on every run

terraform/projects/app-puppetmaster/main.tf
We're keeping this as a seperate record rather than making the nginx
vhost listen to "puppet" instead of "puppetdb" because we plan
to refactor this part of the architecture soon (tm) and it'll be easier
to rework if it all uses different names.
=> Add an alias for puppetdb

terraform/modules/aws/elasticache_redis_cluster/main.tf, terraform/projects/app-backend-redis/main.tf
We are seeing errors with publishing-api which seem to be related with redis.
Update the module so you can choose either clustered or non-clustered. If non-clustered is chosen, then a master with a read replica is created on redis 3.2.
=> Add a clustering option to redis module

terraform/projects/infra-security-groups/asset-master.tf
Backend and whitehall-backend both need access to the EFS share over tcp/udp 111.
=> Update asset-master security rules

terraform/projects/app-mirrorer/additional_policy.json, terraform/projects/app-mirrorer/main.tf
The mirrorer needs a large disk to store the static website prior to
upload. This adds a 100GB EBS volume to the instance.
This could, in theory, be done using a larger root volume but this would
mean that if the instance went away progress would be lost. This would
likely limit the usefulness of the static images if it had to repeat
large amounts of work.
=> Add EBS volume to mirrorer

terraform/projects/app-cache/main.tf, terraform/projects/app-deploy/main.tf, terraform/projects/infra-artefact-bucket/integration.govuk.backend, terraform/projects/infra-artefact-bucket/main.tf, terraform/projects/infra-artefact-bucket/reader.tf, terraform/projects/infra-artefact-bucket/replication-role.tf, terraform/projects/infra-artefact-bucket/writer.tf
This adds a project to build an artefact bucket. This is intended to
be written to by CI in Carrenza and read from by the deploy machines.
This means that we will not need to give AWS deploy machines access to
Carrenza (it would also simplify any bootstrapping process).
=> Add artefact bucket

terraform/projects/infra-security-groups/frontend.tf
Since machines are not going via the frontend-lb, we need to allow them to talk to the frontend machine.
=> Allow management to frontend

terraform/projects/app-whitehall-backend/main.tf, terraform/projects/infra-security-groups/outputs.tf, terraform/projects/infra-security-groups/whitehall-backend.tf
The current whitehall backend lives behind the backend load balancers,
this PR changes this in terraform and makes it available as an external resource.
=> Add an external ELB to whitehall

terraform/projects/app-exception-handler/main.tf, terraform/projects/infra-security-groups/exception-handler.tf, terraform/projects/infra-security-groups/outputs.tf
Since we removed backend-lb we go directly to the exception_handler ELB.
=> Add external ELB to exception_handler

terraform/projects/app-mapit/main.tf
Start using a variable to configure instance type for Mapit. This will
likely need to be done eventually (to allow larger instances in
production/staging) and this means that the two ASGs will both use the
same instance type.
=> Make instance type a variable for mapit

terraform/projects/app-content-store/main.tf, terraform/projects/app-draft-content-store/main.tf, terraform/projects/infra-security-groups/content-store.tf, terraform/projects/infra-security-groups/draft-content-store.tf, terraform/projects/infra-security-groups/outputs.tf
Update content-store and draft-content-store to use an internal
and external ELB in both cases. Use dedicated security groups
for each type of ELB.
=> Add external and internal ELBs to content stores

terraform/projects/infra-security-groups/publishing-api.tf
Apps need internal access to publishing-api (frontend deployments are
failing). For now we are giving access to the management network.
=> Enable internal access to publishing-api

terraform/projects/infra-security-groups/draft-frontend.tf
Apps need internal access to draft-frontend (draft collections and frontend apps
are erroring). For now we are giving access to the management network.
=> Enable internal access to draft-frontend

terraform/projects/app-draft-cache/main.tf, terraform/projects/infra-security-groups/draft-cache.tf
At the end of the router data sync, the script calls router-api from draft-content-store.
=> Allow calling https://draft-router-api

terraform/projects/app-apt/main.tf, terraform/projects/infra-security-groups/apt.tf
Put access to Gemstash back, after removing in previous Apt changes. We
need internal access to Apt ELB on port 80.
=> Fix Gemstash internal access

terraform/projects/infra-security-groups/deploy.tf
Allow Carrenza Integration IPs to allow for automated deployments into this environment. This can be triggered by the CI job.
=> Allow Carrenza Integration deploy

terraform/projects/app-monitortest/main.tf, terraform/projects/infra-security-groups/monitortest.tf
Update management security group to enable access from monitortest
to the node_exporter port.
Remove unused internal ELB on monitortest project.
=> Prometheus tests

terraform/projects/app-mongo/additional_policy.json, terraform/projects/app-mongo/main.tf, terraform/projects/infra-networking/main.tf, terraform/projects/infra-security-groups/mongo.tf, terraform/projects/infra-security-groups/outputs.tf, terraform/userdata/10-associate-eni
We're seeing an issue where applications using the mongo cluster are unable to connect to the cluster despite it being available.
We believe it may be related to the dynamic nature of ELBs, and the mongo-ruby-driver currently being unable to handle DNS updates without a reload of the application.
This commit removes the load balancers, creates an ENI and an EIP, and attaches the ENI to the instance on boot using userdata.
As per the documentation, an IP associated with an ENI should follow the interface to any attached instance:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html
We can assign a DNS record to the IP address so the Puppet code underneath does not have to change.
https://trello.com/c/luBryWgW/748-change-the-way-mongo-in-aws-works
=> Use private EIPs rather than ELBs on mongo

terraform/projects/app-cache/main.tf, terraform/projects/app-calculators-frontend/main.tf, terraform/projects/app-deploy/main.tf, terraform/projects/app-draft-cache/main.tf, terraform/projects/app-monitoring/main.tf, terraform/projects/app-monitortest/main.tf, terraform/projects/app-publishing-api/main.tf
The `elb_certname` variable has been replaced with
`elb_external_certname` and `elb_internal_certname` to
ensure we use the correct domain on each case.
Update the code to remove comments and references to the
old variable and update with the right one.
=> Remove elb_certname references

terraform/projects/app-monitortest/main.tf, terraform/projects/infra-security-groups/monitortest.tf
The Prometheus Alertmanager service can run on the same Prometheus instance.
We can enable the service externally to access the web UI, that runs on
port 9093. The monitortest project will need a secondary ELB to manage the
Alertmanager endpoint.
=> Add Prometheus Alertmanager resources

doc/guides/redeploying-applications-on-rebuild.md
govuk-delivery is no longer deployed to backend boxes (or any boxes for
that matter).
This commit removes it from the docs.
=> Remove govuk-delivery

terraform/projects/app-graphite/main.tf
In order to use the CloudWatch datasource in Grafana, the graphite
instance needs access to the CloudWatch API. The CloudWatchReadOnlyAccess
managed policy already provides all the permissions that we need, so
we don't need to provide a custom policy.
This change attaches the managed policy to the graphite role.
=> Add CloudWatchReadOnlyAccess policy to graphite role

terraform/projects/infra-stack-sns-alerts/integration.blue.backend, terraform/projects/infra-stack-sns-alerts/main.tf
Add initial project to configure a dedicated topic for stack alerts. The
project creates a SQS subscription to enable integration with other notification
methods.
=> Add infra-stack-sns-alerts

terraform/modules/aws/alarms/autoscaling/main.tf
Add a new AWS module to manage autoscaling alarms. At the moment
it only includes an alarm on the number of instances in service,
but we could add more based on our needs. The alarm threshold can
be configured with a variable. The actions need to be specified
with an input variable.
=> Add module alarms autoscaling

terraform/modules/aws/alarms/ec2/main.tf
Add new alarms module to monitor EC2 instances.
It enables alarms for EC2 instances that belong to a specific
autoscaling group. For this reason it could be combined with the
autoscaling module, but it looks more tidy to organise modules per
metric namespace. Also, if we create a new intance_id parameter,
it could also serve to apply to individual instances instead of filtering
per ASG, which would make the module more generic.
=> Add AWS module alarms EC2

terraform/modules/aws/alarms/ebs/main.tf
Add alarms module to monitor EBS volumes. For now we only monitor
the number of pending operations, we could extend the module later
to add metrics specific for each type of storage.
=> Add AWS module alarms EBS

terraform/modules/aws/alarms/rds/README.md, terraform/modules/aws/alarms/rds/main.tf
Add module to monitor RDS metrics. DB connections are not included
because we are not setting a limit in our RDS configuration. The
RelicaLag alarm should only be enabled on read replica DB instances.
=> Add AWS module alarms RDS

terraform/modules/aws/alarms/elasticache/README.md, terraform/modules/aws/alarms/elasticache/main.tf
Add module to monitor ElastiCache metrics. For now it only includes
host alarms.
=> Add AWS alarms Elasticache module

terraform/modules/aws/alarms/autoscaling/README.md, terraform/modules/aws/alarms/autoscaling/main.tf, terraform/modules/aws/alarms/ebs/README.md, terraform/modules/aws/alarms/ebs/main.tf, terraform/modules/aws/alarms/ec2/README.md, terraform/modules/aws/alarms/ec2/main.tf, terraform/modules/aws/alarms/elb/README.md, terraform/modules/aws/alarms/elb/main.tf, terraform/modules/aws/alarms/natgateway/README.md, terraform/modules/aws/alarms/natgateway/main.tf, terraform/modules/aws/alarms/rds/README.md, terraform/modules/aws/alarms/rds/main.tf
- Remove "::" in module name description
- Add missing links to metrics references
- Remove default from variable description
- Add relevant units to variable description
- Add single line comment with output description to work around https://github.com/segmentio/terraform-docs/issues/29
=> Alarms update docs

terraform/modules/aws/rds_instance/main.tf
- It's thought that backups should happen before the maintenance window,
presumably in case anything goes wrong.
=> Swap RDS maintenance window and backup times around

terraform/modules/aws/alarms/elasticache/README.md, terraform/modules/aws/alarms/elasticache/main.tf, terraform/modules/aws/elasticache_redis_cluster/README.md, terraform/modules/aws/elasticache_redis_cluster/main.tf
Add Cluster ID output to ElastiCache module and use this
parameter to filter CloudWatch metrics. Previously we were
using node ID but we only build instances with the cluster resource.
=> Add Redis cluster ID to module and alarm

terraform/modules/aws/alarms/natgateway/README.md, terraform/modules/aws/alarms/natgateway/main.tf, terraform/projects/infra-networking/main.tf, terraform/projects/infra-stack-sns-alerts/integration.govuk.backend
The `aws/network/nap` module outputs a list of NAT Gateway IDs, so we need to modify the `aws/alarms/natgateway` module to receive a list instead of string.
Add SNS topic for the 'govuk' infra stack to receive infra notifications.
Add natgateway alarm to the infra-networking project.
=> Add natgateway alarm to infra-networking

terraform/modules/aws/node_group/main.tf
Terraform recommends in the
[documentation](https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#using-with-autoscaling-groups)
to use launch configs in this way. We already set the
`create_before_destroy` lifecycle parameter, but because we hardcode the
name, terraform tries to create a new launch config with the same name
and fails. Updating the launch config to use name_prefix successfully
creates a new launch config with a different name and then applies that
to the ASG before destroying the existing launch config.
Because this is in a shared module, this will force a new launch config
when we next apply any changes using it, but this shouldnt result in any
difference except for the launch config name, which will have a random
suffix after it.
=> Use name_prefix instead of name for launch config

terraform/projects/app-db-admin/main.tf, terraform/projects/app-mongo/main.tf, terraform/projects/app-router-backend/main.tf, terraform/projects/app-transition-db-admin/main.tf, terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/integration.govuk.backend, terraform/projects/infra-database-backups-bucket/main.tf, terraform/projects/infra-database-backups-bucket/writer.tf
This contains a bucket and an iam policy allowing to write to this
bucket. Once this is applied the iam policy will be attached to instance
roles to allow them to write to the bucket.
=> Add a project for a database backups bucket

terraform/projects/infra-database-backups-bucket/main.tf
Add lifecycle rules to our database backups. In line with what we currently do, keep backups for 3 months, but move them to lower storage costs after 30 and 60 days respectively.
With mongodb, keep "regular" backups to 7 days so we have point in time backups that go back 7 days. Keep "daily" backups for 90 days.
https://trello.com/c/F6UQeeiN/777-design-rds-replicas-and-backups
=> Add lifecycle rules to database backups

.pre-commit-config.yaml
We're having some issues with this stopping clean commits so
it's being disabled until we can investigate
=> Remove pre-commit hook

terraform/projects/app-rummager-elasticsearch/main.tf
- These inconsistencies were undocumented, so make all three instances the same type.
=> Set rummager-elasticsearch-{2,3} to be m4.large, not t2.medium

terraform/projects/app-cache/README.md, terraform/projects/app-cache/main.tf, terraform/projects/app-db-admin/main.tf, terraform/projects/app-deploy/README.md, terraform/projects/app-deploy/main.tf, terraform/projects/app-mongo/main.tf, terraform/projects/app-router-backend/main.tf, terraform/projects/app-rummager-elasticsearch/README.md, terraform/projects/app-rummager-elasticsearch/main.tf, terraform/projects/app-transition-db-admin/main.tf
Attach the policy that would allow each instance to write snapshots to
the database backups S3 bucket.
Related to https://github.com/alphagov/govuk-aws/pull/348
https://trello.com/c/wl3p8Y9D/787-investigate-elasticsearch-backups
=> Allow rummager elasticsearch to write to backups bucket

terraform/projects/infra-database-backups-bucket/main.tf
Glacier charges an [early delete
fee](https://aws.amazon.com/premiumsupport/knowledge-center/glacier-early-delete-fees/)
for deleting objects which are stored for less than 90 days. This
appears to be calculated by charging you for 90 days of storage
regardless of the length of time things are stored in glacier, and
calling this an early deletion fee. This is a footnote on the [pricing
page](https://aws.amazon.com/glacier/pricing/) which reads
> Glacier archives have a minimum 90 days of storage, and archives
> deleted before 90 days incur a pro-rated charge equal to the storage
> charge for the remaining days
We may as well make use of this
additional time as we are already paying for it through the early
deletion fee.
=> Use all of available glacier time for backups

terraform/projects/app-mysql/README.md, terraform/projects/app-mysql/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/mysql.tf, terraform/projects/infra-security-groups/outputs.tf
Add a MySQL read replica. In our Puppet code this was previously called "mysql-slave", so take this opportunity to rename to "replica".
https://trello.com/c/F6UQeeiN/777-design-rds-replicas-and-backups
=> Add MySQL read replica

terraform/projects/app-graphite/main.tf
There have been common alerts for our graphite instance:
- disk space
- high disk time
We should increase the default disk space on the EBS volume, and also remove setting the disk size on the default node_group as this is set upstream by the module.
Also change the disk type to a disk capable of higher throughput:
See the [documentation](https://aws.amazon.com/ebs/details/) for details.
=> Change disks for Graphite

terraform/projects/app-graphite/main.tf
A minimum amount of IOPS must be set for this type of disk. Set to 100, and if it's problematic, increase.
=> Set IOPS for io1 disk

terraform/projects/app-whitehall-backend/main.tf
Smart Answers apparently needs to communicate with Whitehall Admin, so ensure the service records are also created for the internal zone.
=> Add internal_app_service_records

terraform/projects/app-graphite/main.tf
I set it to the minimum at 100, and the Icinga alert triggered way above critical.
I set it to 500, and it moved down to warning.
Moving it to 1000 seems sensible to ensure graphite can write all operations in a timely fashion.
I have made the change in place, so change is to reflect any future deployments.
=> Set IOPS to 1000 for Graphite volume

.pre-commit-config.yaml
Since upgrading terraform this has stopped working, and everyone is
disabling it locally, so remove it until we can invest some time
in to fixing it up.
=> Disable a broken pre-commit

terraform/projects/app-bouncer/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/bouncer.tf, terraform/projects/infra-security-groups/variables.tf
Bouncer should respond to traffic on port 80, as it handles redirects that may not neccessarily be coming from an https request.
We should also ensure there is a certificate for https requests, and update security groups so that the monitoring instance is able to test the endpoint.
EDIT: after doing this I realised that we'd need to allow all traffic in the external ELB to allow the monitoring instance to be able to connect. I don't want to create an internal ELB for a single check, so need to decide how we should best monitor this.
=> Update Bouncer ELBs and rules

terraform/projects/app-mysql/main.tf
I discovered that the Signon application had stopped working, and we discovered that the migration to a new schema had failed (a table was missing that the application expected).
In the migration, when trying to create a trigger that modifies data, MySQL throws an error because we do not have the correct level of privileges to create this:
```
15:40:09 *** [err :: ip-10-1-5-53.eu-west-1.compute.internal] E, [2017-11-20T15:40:09.784565 #675] ERROR -- : Error in class=Lhm::Entangler, reverting. exception=ActiveRecord::StatementInvalid message=Mysql2::Error: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable): create trigger `lhmt_del_event_logs`
```
Since we are unable to elevate the privilege for …
=> Add log_bin_trust_function_creators to MySQL

terraform/projects/app-cache/main.tf
The cache nodes are pretty important as they service all frontend traffic coming into our stack. After enabling traffic relay, I've seen alerts come through about memory usage. While Varnish should use an amount of memory for caching, the cache instances also run services such as NGINX and Router, and so we need to ensure we don't starve anything else of memory.
This also puts the cache instances in line with the memory size in the current integration environment.
=> Upgrade cache machines with more memory

doc/guides/environment-provisioning.md, terraform/projects/app-puppetmaster/README.md, terraform/projects/app-puppetmaster/main.tf
When browsing the puppetmaster manifest I thought it might easy enough to add in a variable which defaults to having no bootstrap ELB, but upon deployment we can set the var to true.
The story (referenced below) suggests that we should entirely extract the bootstrap ELB into it's own module. Personally this feels like overkill, and Terraform should be able to handle creating/destroy an ELB without issue. However, I am not aware of the context when the story was created so there may be something I'm not aware of.
https://trello.com/c/yDjFSzOX/652-aws-migration-refactor-puppetmaster-bootstrap
=> Add variable to disable Puppetmaster bootstrap ELB

terraform/projects/app-monitoring/main.tf, terraform/projects/infra-security-groups/monitoring.tf
We have a number of hosts running the `check_icinga` plugin. These are
currently failing to connect. This changeset should permit that access.
=> Allow internal hosts to connect to alert on port 443

terraform/projects/app-mysql/main.tf, terraform/projects/app-postgresql/main.tf, terraform/projects/app-transition-postgresql/main.tf, terraform/projects/infra-vpc/main.tf
We are using `${path.module}` in a module variable, that gets resolved
to the local user directory, which differs from user to user
causing a new lambda_function resource.
=> Update path to lambda_filename

terraform/modules/aws/rds_instance/README.md, terraform/modules/aws/rds_instance/main.tf
- This is so that we can tell which database snapshot we want to
restore, without having to write a script that queries the
DBInstanceID, finds out its tags, and matches them up to the snapshot
ID.
=> Set copy_tags_to_snapshot to true by default for RDS databases

terraform/modules/aws/rds_instance/README.md, terraform/modules/aws/rds_instance/main.tf
The `security` event category doesn't seem to be recognised, and
it's causing Terraform errors.
=> Remove security event from rds module

terraform/projects/app-puppetmaster/main.tf, terraform/projects/infra-security-groups/puppetmaster.tf
Someone had already added a DNS record for puppetdb, but we didn't allow anything to access it.
We have a check which specifically uses puppetdb to check what nodes require rebooting, and this is always run from the monitoring instance.
For now, only allow that instance access, and if we wish to open it up in the future (to make it accessible with our fabric scripts, for example), then we can do so.
=> Allow monitoring to speak to Puppetdb

terraform/projects/app-mysql/main.tf, terraform/projects/app-postgresql/main.tf, terraform/projects/app-transition-postgresql/main.tf
Replica lag can spike to up to 300 secs, we are getting
alarms all the time.
=> Increate the RDS alarm replicalag_threshold

terraform/userdata/30-deploy-apps
Only run this script if the file exists, which should only be on app
servers
=> Add a user data script to deploy apps

terraform/projects/infra-root-dns-zones/README.md, terraform/projects/infra-root-dns-zones/main.tf
Add internal and external domain name output to infra-root-dns-zones
to use with new root domain DNS entries.
=> infra-root-dns-zones add domain outputs

terraform/projects/app-whitehall-frontend/main.tf
The subnet should be private, as the rest of the ELB.
=> Fix whitehall-frontend LB subnet

terraform/modules/aws/node_group/main.tf
Use `aws_autoscaling_attachment` resources to attach an ASG to Classic
ELBs instead of the `load_balancers` parameter in the `aws_autoscaling_group`
resource.
The effect is similar in both cases, but both methods are not compatible and
we want to be able to create attachments to this ASG from other part of the
repository outside the `node_group` module. For more info:
https://www.terraform.io/docs/providers/aws/r/autoscaling_attachment.html
=> Use ELB ASG attachment

terraform/modules/aws/elasticache_redis_cluster/main.tf
The module shows errors when evaluating the conditional in the output
resources. Both vals of the conditional need to be of the same type,
currently they are string and list. Also, match the format of the
output _id resource.
=> Update elasticache_redis_cluster module for 0.11.1

terraform/projects/app-bouncer/main.tf, terraform/projects/infra-security-groups/bouncer.tf, terraform/projects/infra-security-groups/outputs.tf
Smokey tests are failing when trying to connect with bouncer:
```
2017-12-08 17:50:27: Step: [FAIL] When I request "http://www.attorneygeneral.gov.uk" from Bouncer directly
2017-12-08 17:50:27: Error: Unable to fetch 'https://bouncer.blue.integration.govuk.digital/'
```
Currently Bouncer only allow external access from replay traffic and
Fastly IPs, and we don't want to open it to the entire public. So in
order to have the Smokey tests working, we need to enable internal access
from monitoring to Bouncer, and update the app domain in the Smokey
test to use the internal one.
=> Add bouncer internal LB for monitoring

terraform/projects/infra-security/main.tf
This helps stop people using simple passwords and complies with the CIS
security docs (and scanners). We previously had everything apart from upper and special characters set so this is a little tighter.
This could have a param for each of those but I don't think we need that at this time.
=> Require the passwords to meet a minimum criteria

terraform/modules/aws/rds_instance/main.tf
Fix splat syntax warnings:
```
Warning: output "rds_replica_resource_id": must use splat syntax to access aws_db_instance.db_instance_replica attribute "resource_id", because it has "count" set; use aws_db_instance.db_instance_replica.*.resource_id to obtain a list of the attributes across all instances
```
Ensure the output is type string by using `join`. The output is used as variable in
other parts of the code and it's already expecting a string (not list).
=> Update module rds_instance 0.11.1

terraform/projects/app-backend/main.tf, terraform/projects/app-puppetmaster/main.tf, terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
Add `.integration.govuk-internal.digital` CNAMES to blue stack for
app records.
=> Add root DNS records for app services

terraform/projects/infra-public-services/main.tf
The assets internal DNS entry is missing.
Logs_cdn is not deployed right now, so the ASG-LB attachment needs to be
conditional.
=> Add missing assets to internal DNS and make logs_cdn conditional

terraform/userdata/00-base
I was trying to decide if this was the correct behaviour or not; I *think* it is.
Hosts should not resolve to their own stack when doing searches because we're providing resolution by the "top level" domain to assign which services go where.
If we need something to go to a specific stack we can still specify the FQDN, but a default lookup should resolve to the top level. For example, if we want to connect to redis, we should be connecting by default to `redis.integration.govuk-internal.digital`, rather than `redis.blue.integration.govuk-internal.digital`.
=> Remove stackname from search domain

terraform/projects/infra-security-groups/puppetmaster.tf
Our Fabric scripts are used by developers to run tasks. We should allow them to have the full toolbox at their disposal as they migrate over.
If we wish to change how PuppetDB is accessed in the future we should redesign it when we have time, rather than blocking other people do work.
In terms of security, we are keeping with the same risk as the current environment.
=> Allow Jumpbox to PuppetDB

terraform/projects/app-draft-cache/README.md, terraform/projects/app-draft-cache/main.tf, terraform/projects/infra-security-groups/draft-cache.tf, terraform/projects/infra-security-groups/outputs.tf
Draft Cache is public, but is accessed via Signon using authenticating-proxy.
Add an external ELB, and update the DNS so that users can access the draft stack.
=> Add external draft-cache ELB

terraform/projects/infra-public-services/main.tf, tools/migration-hosts.sh
The Draft stack is a public facing service, but has authentication which is handled by Signon.
This commit creates a public load balancer.
=> Add public facing Draft stack load balancer

terraform/projects/infra-security-groups/draft-cache.tf
This caused the service to not be inService when I added the external load balancer previously.
=> Add egress in

terraform/modules/aws/node_group/main.tf, terraform/projects/app-asset-master/main.tf, terraform/projects/app-backend/main.tf, terraform/projects/app-bouncer/main.tf, terraform/projects/app-cache/main.tf, terraform/projects/app-calculators-frontend/main.tf, terraform/projects/app-content-store/main.tf, terraform/projects/app-db-admin/main.tf, terraform/projects/app-deploy/main.tf, terraform/projects/app-docker-management/main.tf, terraform/projects/app-draft-cache/main.tf, terraform/projects/app-draft-content-store/main.tf, terraform/projects/app-draft-frontend/main.tf, terraform/projects/app-frontend/main.tf, terraform/projects/app-graphite/main.tf, terraform/projects/app-jumpbox/main.tf, terraform/projects/app-logs-cdn/main.tf, terraform/projects/app-mapit/main.tf, terraform/projects/app-mirrorer/main.tf, terraform/projects/app-mongo/main.tf, terraform/projects/app-monitoring/main.tf, terraform/projects/app-publishing-api/main.tf, terraform/projects/app-puppetmaster/main.tf, terraform/projects/app-rabbitmq/main.tf, terraform/projects/app-router-backend/main.tf, terraform/projects/app-rummager-elasticsearch/main.tf, terraform/projects/app-search/main.tf, terraform/projects/app-transition-db-admin/main.tf, terraform/projects/app-whitehall-backend/main.tf, terraform/projects/app-whitehall-frontend/main.tf
This is similar to b4782ff in that counts cannot be computed on a plan:
https://github.com/hashicorp/terraform/issues/12570#issuecomment-318414280
We must pass in a variable to get round this limitation on Terraform.
=> Add fix for ELB attachments count

terraform/projects/app-graphite/main.tf, terraform/projects/app-mongo/main.tf, terraform/projects/app-rummager-elasticsearch/main.tf
M5 instances use different device labels than M4, and we hardcode device names in our Puppet. We should continue to be consistent, so move back to using M4s with anything that attaches a disk (and Mongo because we'll attach a disk eventually).
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html
=> Change instances with disks to M4

doc/guides/environment-provisioning.md
Information related to the SSH key appeared to be omitted from the documentation.
=> Update docs for SSH key

doc/guides/environment-provisioning.md, terraform/projects/infra-security-groups/outputs.tf, terraform/userdata/00-base
This reverts commit 0b787c1.
I reverted because machines were unable to communicate with the Puppetmaster. This is because infra-public-services should be deployed both before and after instances are created.
Before to create a set of CNAMEs for the top level DNS, and after to create the public load balancers.
I believe these items should be separated for "internal" and "external" domains, although I need to clarify if there is a dependency when we have created a public load balancer on the node_group that it is attached to. I thought I had failed to destroy a project when it had an LB attached due to a dependency issue, so destroyed the entire infra-public-services project, but this caused issues when building the environment from scratch.
=> Clarify documentation on infra-public-services

terraform/modules/aws/alarms/natgateway/README.md, terraform/modules/aws/alarms/natgateway/main.tf, terraform/projects/infra-networking/main.tf
We need to declare a new variable to define the number of elements
in the nat_gateway_ids list, because this list is computed and can't
be used in a count element.
=> Fix module alarms nat computed count

deployment/README.md, deployment/default/README.md, deployment/terragov/README.md, deployment/terragov/deployment.yaml, deployment/terragov/integration.yaml
Adds some configuration files to use with Terragov to deploy an
environment.
We do not have to merge this, but it's useful to have the branch when thinking about deployment order.
=> Environment deployment

terraform/projects/app-graphite/main.tf, terraform/projects/app-mapit/main.tf
A couple of projects are missing the 'Device' tag in the EBS volume
that helps to attach the disk from Userdata.
=> Add missing device tags to EBS volumes

terraform/projects/infra-root-dns-zones/main.tf, terraform/projects/infra-stack-dns-zones/main.tf
```
Warning: output "internal_root_zone_id": must use splat syntax to
access aws_route53_zone.internal_zone attribute "zone_id", because it
has "count" set; use aws_route53_zone.internal_zone.*.zone_id to obtain
a list of the attributes across all instances.
```
=> Use splat syntax to access attributes with counts

terraform/projects/infra-artefact-bucket/README.md, terraform/projects/infra-artefact-bucket/main.tf, terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/main.tf, terraform/projects/infra-monitoring/main.tf
Update the infra-*-bucket proejcts to use the shared logging bucket
for S3 access logs. These projects were initially configured
without logging or a separate access log bucket, but since then we
enabled a shared bucket in infra-monitoring.
S3 buckets will use the prefix `s3/bucket_name/` to store logs.
=> infra buckets use shared logging

terraform/projects/app-asset-master/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/outputs.tf
asset-master is timing out when it tries to mount the EFS
volume. I think we are missing the security rules.
=> Add asset-master-efs security groups

terraform/modules/aws/lb/main.tf
The predefined security policy is ELBSecurityPolicy-2016-08, currently
applied on ELBs. Update the default version in the LB module to match
the predefined settings.
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-security-policy-table.html
=> Update the default SSL configuration in LBs

terraform/projects/app-rummager-elasticsearch/main.tf
This will also change the ELB device name and there is a Puppet PR for that:
https://github.com/alphagov/govuk-puppet/pull/7035
=> Upgrade the elasticsearch instances to m5 from m4

terraform/projects/app-graphite/main.tf
Update machine type to m5.xlarge. It should be cheaper, we tried to
resize it before but it didn't work because of disk labels. Trying again
after the 'Device' tag was added to the EBS volume.
=> Resize graphite machine type

terraform/projects/app-bouncer/main.tf, terraform/projects/infra-public-services/main.tf
On the bouncer machines, Nginx is configured to use the 'bouncer'
vhost as the default one. The Puppet template does not allow to
insert custom code before the 'location /' block, so we can't set
our health check to '/_healthcheck' as we have done in the other
machines.
Bouncer already deploys a heath check on `/healthcheck`, so use
that instead.
=> Fix Bouncer LB health check

terraform/projects/app-mongo/main.tf
There are no attached disks (yet) on these so it should be fine to bump these to m5. We now know how to make EBS devices mount in m5 so it shouldn't be a problem when we DO add the disks :)
=> Update Mongo instance type to m5.large.

terraform/projects/infra-security-groups/variables.tf
I forgot to add the variable in 7b677d5229d86b2489f4dfc693e4d617cb8e7d11.
I added it as an additional rather than updating the current variable for Integration as in the future we may wish to use the Integration variable.
=> Add variable for Carrenza Production IPs

terraform/projects/app-router-backend/README.md, terraform/projects/app-router-backend/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/outputs.tf, terraform/projects/infra-security-groups/router-backend.tf
Same as 14e27bf, we are seeing some issues in apps trying
to connect with the mongo instances in the router-backend
machines.
This change replaces the ELB with ENI and updates the instance
DNS to use the reserved IP assigned to the ENI.
We also update the security groups to apply to the instance
SG the same permissions perviously assigned to the ELB.
=> Attach ENI to router-backend

terraform/projects/app-router-backend/additional_policy.json, terraform/projects/app-router-backend/main.tf
Add missing additional policy to router-backend to attach ENIs,
missing in 4440f5.
=> Add network policy to router-backend

terraform/projects/app-router-backend/main.tf
ENI and ASG tags need to be the same so the machine can find the
ENI and attach it during provisioning.
The aws_migration tag had a typo.
=> Fix router-backend ENI tag

terraform/projects/app-asset-master/README.md, terraform/projects/app-asset-master/main.tf
Add the instance_ami_filter_name variable to asset-master to use
the same AMI filter as the rest of the environment. Without this
variable, the AMI defaults to the latest one, and we are very likely
to receive a resource refresh when planning/applying the TF config.
=> Asset-master add instance_ami_filter_name variable

terraform/projects/infra-security/production.govuk.backend
- This is needed so we can configure roles and users in production.
=> Add a backend file for infra-security production

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/offsite_ssh.tf, terraform/projects/infra-security-groups/variables.tf
Allow SSH to jumpbox from Carrenza Staging to sync attachments. We
can remove the rule when we finish syncing data or leave it after
the switchover.
=> Allow SSH to jumpbox from Carrenza Staging

terraform/projects/infra-database-backups-bucket/main.tf
This reverts commit efa488c0b23d663f8221ae0d0cba8c0d0363fe69.
Having the bucket open to office IPs is _too_ open and allows non-GOVUK people access.
=> Revert "Allow reads to database buckets from the office"

terraform/projects/app-deploy/main.tf, terraform/projects/infra-artefact-bucket/integration.govuk.backend, terraform/projects/infra-artefact-bucket/production.govuk.backend
Staging Jenkins failed to deploy because the key used was inconsistent.  We have updated it to use the consistent naming scheme across all backend files, and will update Integration to migrate the statefile.
https://trello.com/c/licP4V2x/925-build-staging-in-aws-and-review
=> Update infra-artefact-bucket key name

doc/guides/environment-provisioning.md
This updates the guide to give a semblance of order rather than just "deploy the rest of the stack".
=> Update env provisioning notes

terraform/projects/infra-security-groups/backend-redis.tf
This commit adds a security group rule to allow deploy machines to access redis machines. This allows the emergency banner job to work since it writes data directly to redis.
=> Allow deploy to access redis

terraform/projects/infra-security/test.govuk.backend
- So that we can deploy users to the test account, so that people can start playing with things.
=> Add a backend file for the test account

terraform/modules/aws/iam/role_user/main.tf, terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
As we add more environments and user roles, sometimes we don't
need to create all of them on each environment. For instance,
the users group doesn't need to be present on the Test environment,
where we want people to be able to create more things.
To support empty lists of users from the data files, the `role_X_user_arns`
parameters in the infra-security manifest need to default to empty list,
and the `role_user` module needs to only create a role when the list
of users is not null. This is needed because the `Principal` section in
the policy can't be an empty string.
=> infra-security support empty user list

Gemfile.lock, terraform/projects/infra-networking/main.tf
Within the test environment we do not want to add subnets for things like RDS and Elasticache. Setting empty defaults means the module will not create these subnets. Empty defaults need to be set because otherwise it expects variables to be passed in and will error without.
Also update Gemfile.lock for up to date Ruby dependencies.
https://trello.com/c/4lvHCiOg/965-tidy-up-govuk-infrastructure-test-aws-account
=> Add empty defaults in infra-networking

tools/govukcli
This allows backwards compatability with the environments in Carrenza. It also allows someone to SSH to machines in Carrenza like they are used to:
```
govukcli set-context staging
govukcli ssh backend-1
```
=> Update govukcli tool

jenkins.sh
This script invokes the `build-terraform-project.sh` script and should be triggered using Jenkins.
Sops is a precursor as an install to run these scripts, and should be managed by Puppet as it is less liable to change than Terraform.
If the Terraform version is not specified using TERRAFORM_VERSION, then it will use the default installed on the system where it is being run.
If you wish to test newer versions of Terraform (quite a common occurrence at this point in the Terraform lifecycle), then you can specify a version and the script will download, verify and set the path for that version of Terraform.
https://trello.com/c/qAzTAU4p/952-build-box-spike-on-adding-tf-deploys-to-current-integration-carrenza-deploy-jenkins
=> Add script for Jenkins deploy

tools/govukcli
Someone suggested a way to list node types. In Carrenza, this is tricky, but since I built in the option to SSH straight to specific machines it's less valuable.
In AWS, we can use the tags assigned to instances, so using a bit of jq magic, we can list all the types of instances available to SSH to.
=> Allow option to list node-types

deployment/terragov/deployment.yaml
- I didn't particularly know where to put this, it's on its own in Puppet as
far as I can see, so I put it with 'app-mirrorer' and 'app-apt' etc.
- Also note that it's only used in staging and production
=> Add app-logs-cdn to the Terragov deployment file

terraform/projects/infra-security-groups/graphite.tf
Testing out some changes to the release app on integration I
found that it timed out when trying to access a grafana 
dashboard, but on staging and production it did not.  It times
out in the "open" phase, rather than the "read" phase of the
http request, so we figured it was a firewall issue.  Opening
up access to graphite machines to the backend machines
(which is where the release app lives) should mean that the
request won't time out any more.
=> Allow backend machines access to graphite

terraform/projects/app-backend-redis/main.tf
This is required due to out of memory errors that occur as a result of
elasticsearch reindexing on a nightly basis.
3rd line ticket:
https://govuk.zendesk.com/agent/tickets/2587672
https://trello.com/c/JHcwDJc0/81-compress-rummager-data-in-sidekiq-when-updating-pageviews
=> Increase backend-redis to cache.m3.large

terraform/modules/aws/iam/role_user/main.tf
- Previously, every time we called "aws assume-role" on the command
line, we'd have to get our phones (or other designated MFA solution)
and type in a code. This would have to happen every hour, which was
tedious for long-running builds like building an environment.
- With this change, AWS won't require an MFA token upon assuming a role
if `sts get-session-token` with an MFA code has been successful within
the last 12 hours (43200 seconds).
- This doesn't remove the requirement to refresh your assume-role tokens
every hour, as that's a different AWS limitation.
=> Only ask for MFA on assume-role once in 12 hours

tools/build-terraform-project.sh
When a backend file is missing, a misleading error is shown. We should produce an error that guides the user to try the correct thing. This should produce a list of possible stacks to deploy to if the backend file does not exist for that stack in the specified environment.
=> Add verbose error for no backend file

terraform/projects/infra-public-services/main.tf
This commit removes the Terraform resource that creates a CNAME for email-alert-api, as we are already creating equivalent “A” records.
Trello: https://trello.com/c/oqi6Xvnu/629-move-email-alert-api-and-email-alert-service-to-dedicated-vms
=> Remove email-alert-api CNAME

terraform/modules/aws/lb/main.tf, terraform/projects/infra-public-services/main.tf
Firstly, use correct name for email alert api external elb security group output. It should use dashes not underscores for `email-alert-api`.
Also, we hit the character limit on an ELB target group name. This changes the naming to be managed by TF, and moves the previously specified naming into tags.
=> Fix email alert api public service

terraform/modules/aws/lb/main.tf
Use a combination of the protocol and port as the key for ARNs.
We no longer provide a derivable name.
This is currently `apply`ed in integration, I missed this commit in #503.
=> Change LB target group lookup to not rely on the name

doc/guides/connecting-to-the-environment.md, tools/govukcli.completion
Someone mentioned about bash completion (/cc @boffbowsh), so as a firebreak task I thought I'd add it to govukcli as it makes it easier to get to instances.
The `$lastword` variable is useful as it stops recursive completion against commands, which is why it's use in all the commands across these gross case statements. Writing in case statements does make it easier to add in further options in the future, though.
=> Add completion for govukcli

terraform/policies/s3_govuk_mirror_1_replication_policy.tpl, terraform/policies/s3_govuk_mirror_1_replication_role.tpl, terraform/projects/infra-mirror-bucket/README.md, terraform/projects/infra-mirror-bucket/integration.govuk.backend, terraform/projects/infra-mirror-bucket/main.tf, terraform/projects/infra-mirror-bucket/mirror-crawler-write-policy.tf, terraform/projects/infra-mirror-bucket/mirror-read-policy.tf, terraform/projects/infra-mirror-bucket/pingdom_probe_ips.sh, terraform/projects/infra-mirror-bucket/production.govuk.backend, terraform/projects/infra-mirror-bucket/staging.govuk.backend
- One instance, govuk-mirror-1, is written to directly by mirrorer, a second
instance, govuk-mirror-2, is replicated via Amazon services
Pair: @jljalderman @schmie
=> Add two new S3 mirrors to be used by mirrorer.

tools/govukcli, tools/govukcli.completion
Handles fetching AWS sessions for both gds-users and the requested
GOV.UK environment, including requesting the MFA token.
We fetch and cache a session token for gds-users first so we can assume
roles in other accounts without having to re-request an MFA token.
Requires a small documentation change in the dev docs: https://github.com/alphagov/govuk-developer-docs/pull/746
```
$ govukcli aws s3 ls
Enter MFA Token:
```
=> Add an AWS credentials helper to govukcli

terraform/projects/app-logs-cdn/main.tf
The ELB need to have the govuk_logs-cdn_elb_access security group to allow traffic from fastly to the ELB, and from the ELB to the instances
=> Adding security group to logs-cdn ELB

terraform/projects/infra-security-groups/backend-redis.tf
Gives access to redis for `db_admin`
Related to this PR: https://github.com/alphagov/govuk-puppet/pull/7397
For: https://trello.com/c/CA3PFmY1/129-install-redis-tools-on-aws-integration
=> Add db_admin security group to the redis one

terraform/projects/infra-security-groups/bouncer.tf
This was introduced for internal URLs in https://github.com/alphagov/govuk-aws/pull/408 but since then Smokey is now looking for bouncer from the external URL so access needs to be allowed.
=> Allow accessing external bouncer from monitoring

terraform/projects/infra-security-groups/bouncer.tf
This was referencing an aws_elb not the security group.
=> Fix reference to bouncer external ELB security group

terraform/projects/infra-security-groups/bouncer.tf
Reverts alphagov/govuk-aws#528
These are inbound rules, so the source should be where the traffic is coming from.
=> Revert "Configure the source security group for bouncer"

terraform/projects/infra-security-groups/bouncer.tf
We don't want to allow access to bouncer from the internet so instead we have to get Smokey to run internally.
=> Revert bouncer changes

terraform/projects/app-postgresql/main.tf
This matches the disk size with the equivalent machines in production and staging and prevents "out of space" errors.
=> Expand disk size for PostgreSQL machines to 190GB

terraform/modules/aws/iam/role_user/main.tf
- AWS recently increased the assume-role session token expiry time to a
maximum of 12 hours. This makes our sessions last for eight hours, the
length of the working day, to avoid having to re-assume role multiple
times a day.
- This will revert the changes I made in
https://github.com/alphagov/govuk-aws/pull/498, and I'll have to
change the docs again, but it makes it simpler in the long run - you
only have to remember an `assume-role` command, not also
`get-session-token`.
(I'll test this in the test account first.)
=> Increase the assume-role MFA expiry time to 8 hours (28800 seconds)

tools/govukcli
- Now that tokens last for 8 hours
(23dd074dbfaf4b7201d3fd11d9c948e6806cfbf2), we don't need to
re-assume-role every hour.
- Now we don't need to do that, we can just use `aws assume-role` once
every eight hours, we don't need the intermediary step of `aws sts
get-session-token`.
(This requires #533 to be merged and deployed first.)
Reviewers will find the `?w=1` query string useful to ignore whitespace changes.
=> Update the govukcli script to only use `aws assume-role`

terraform/projects/app-monitoring/main.tf
The monitoring instance that runs Icinga and Smokey in Integration has
begun running out of CPU credits. This is making it difficult to
diagnose problems elsewhere in the stack. Making it an m5.large costs
~$77pcm instead of ~$36pcm, and doubles the RAM.
=> Make our monitoring instances m5.large instead of t2

terraform/projects/app-postgresql/main.tf
- We have noticed performance problems with the current instance class
(db.m4.large). Also, this class provides a lower resource capacity
compared to what was available in Carranza. Due to these reasons we are
changing the instance class to match Carranza Integration instance
resource capacity.
https://trello.com/c/dNgZpaVf/1098-the-postgres-rds-instance-needs-to-be-more-powerful
=> Postgresql Instance Class

tools/govukcli
- It turns out that in 23dd074, setting the `max_session_duration`
parameter doesn't actually apply it to individual users' sessions
without specifying `--duration-seconds` in the `assume-role` command,
so people were still having their session tokens expire after an hour.
- This updates `govukcli` to request tokens valid for eight hours on
`assume-role`.
=> Specify the `--duration-seconds` parameter for assume-role in govukcli

terraform/projects/app-mirrorer/main.tf
- We're using different instance types in integration compared to
staging and production.
=> Specify the mirrorer instance type with a variable

terraform/modules/aws/rds_instance/main.tf
- We have identified that we can change the AWS token TTL. This will
help terraform apply without timing out soon. However, terrafom sets some
default time outs by default.
https://www.terraform.io/docs/providers/aws/r/db_instance.html [Please
check Timeouts]
- If this is not addressed, we get a message similar to the following.
"... aws_db_instance.db_instance_replica: timeout while waiting for
state to become 'available, storage-optimization' ..."
- This change is aimed at extending the default time-out to match the
maximum AWS TTL that we can set (8 hours).
https://trello.com/c/KlI3mK8H/1134-postgresql-rds-integration
https://govuk.zendesk.com/agent/tickets/2629112
=> AWS RDS Timeout

tools/govukcli
The `$CONTEXT` variable is incorrect, it's supposed to be `$GOVUK_ENV`. This was causing `_get_aws_config` to look for `govuk-`, so it will always return the config for the first environment listed in `~/.aws/config`.
=> Fix govukcli for multiple environments

terraform/projects/infra-wal-e-warehouse-bucket/README.md, terraform/projects/infra-wal-e-warehouse-bucket/main.tf, terraform/projects/infra-wal-e-warehouse-bucket/production.govuk.backend, terraform/projects/infra-wal-e-warehouse-bucket/staging.govuk.backend, terraform/projects/infra-wal-e-warehouse-bucket/writer.tf
Only needed in Staging and Production as Integration uses RDS. Once
this is deployed, credentials need creating in the console and adding
to hieradata.
This is based on the `infra-artefacts-bucket` project, plan passes at least.
=> Create destination for WAL-E backups for the data warehouse

terraform/projects/infra-public-services/main.tf
The `warehouse_db_admin` instances use an environment-level
record to access the RDS instance, so we need to CNAME this
to the record in `blue`
=> CNAME environment warehouse db record to stack level record

terraform/projects/app-monitoring/additional_policy.json, terraform/projects/app-monitoring/main.tf
- This change will add a persistent EBS volume to the monitoring
instance. The EBS volume will be used to store stats/data collected by
icinga.
https://trello.com/c/b6So3Wxl/1145-integration-monitoring-instance-ebs-volume
https://govuk.zendesk.com/agent/tickets/2747364
=> Monitoring EBS Volume.

tools/govukcli
The result of `set-user` was being ignored by the special-case `node-types` subcommand.
=> Fix bug with `govukcli ssh node-types`

.pre-commit-config.yaml, Jenkinsfile, terraform/modules/aws/rds_instance/README.md, terraform/projects/app-monitoring/README.md, terraform/projects/app-warehouse-db-admin/README.md, terraform/projects/app-warehouse/README.md, terraform/projects/infra-public-services/README.md, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-wal-e-warehouse-bucket/README.md
- We often forget to run this script when we update files, so instead
I'm adding it as a CI step that fails when
changes are detected by the `terraform-docs` command.
=> Make out-of-date docs fail CI

terraform/projects/app-puppetmaster/main.tf
- We have noticed high CPU usage in the AWS staging puppet master. While
comparing with the Carrenza staging server, we noticed that we have less
CPU cores in AWS. Hence we have performed the following change.
Please check here for history:
https://trello.com/c/nr8kuCOv/1170-aws-staging-puppet-is-broken
=> Puppet Master Instance Type

doc/guides/environment-provisioning.md, terraform/projects/app-puppetmaster/README.md, terraform/projects/app-puppetmaster/main.tf, terraform/userdata/20-puppetmaster, tools/govuk-puppetmaster-bootstrap.sh
- The old bootstrap process involves a lot of manual execution and is
quite complicated
- Integrating formerly manual executed scripts into one and call it via
terraform userdata snippet 20-puppetmaster
- Move required private keys to AWS SSM parameter store
- Update docs to reflect changes
Pair: @rtrinque @schmie
=> Puppetmaster auto bootstrap

tools/govuk-puppetmaster-bootstrap.sh
- This was accidentally ommitted from the original pull request
- SSH key name for cloning from github.com
@schmie
=> Fix SSH key parameter name

terraform/modules/aws/lb/README.md, terraform/modules/aws/lb/main.tf, terraform/projects/app-apt/main.tf, terraform/projects/app-bouncer/main.tf, terraform/projects/app-puppetmaster/README.md, terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
This is required because we want to be able to use the .digital and .publishing.service.gov.uk certificates on the public service load balancers to make the switch as seamless as possible
=> Adding support for a secondary certificate in the aws/lb module

terraform/projects/app-mongo/main.tf
https://alert.integration.publishing.service.gov.uk/cgi-bin/icinga/extinfo.cgi?type=2&host=ip-10-1-4-78.eu-west-1.compute.internal&service=low+available+disk+space
The disk on mongo integration is nearly full, which is preventing the
sync from production from working. Doubling the disk size should tie us
over for the foreseable future.
=> Increase mongo disk size to cope with dumps

terraform/projects/infra-datagovuk-static-bucket/README.md, terraform/projects/infra-datagovuk-static-bucket/datagovuk-write-policy.tf, terraform/projects/infra-datagovuk-static-bucket/fastly-read-policy.tf, terraform/projects/infra-datagovuk-static-bucket/integration.govuk.backend, terraform/projects/infra-datagovuk-static-bucket/main.tf, terraform/projects/infra-datagovuk-static-bucket/production.govuk.backend, terraform/projects/infra-datagovuk-static-bucket/staging.govuk.backend
As part of the migration of DGU's legacy CKAN to GOV.UK infrastructure, we need somewhere to store old static data. This will be routed to directly from Fastly, so we need to give their IPs read access.
This will be around 85GB in total.
This has been planned and applied in integration already.
=> Add a new S3 bucket for data.gov.uk static data

terraform/projects/app-postgresql/main.tf, terraform/projects/app-transition-postgresql/main.tf
- In August 2018, Amazon are deprecating PostgreSQL version 9.3 on RDS,
so we have to upgrade to a newer version.
- GOV.UK have chosen to upgrade to 9.6, to match the new data warehouse
project and give them more breathing room for future support.
=> Upgrade RDS Postgres instances to 9.6

terraform/projects/app-backend-redis/main.tf
This gives almost an extra 6GB of RAM (now 12.3GB) to Redis servers for an extra ~$60 per month per instance. Given the recent incidents caused by running out of memory in Redis, it makes sense to give us a bit of extra headroom.
The CPU count is unchanged at 2. This doesn't matter as our current CPU usage isn't high, and Redis is single-threaded anyway.
=> Resize Redis to r4.large

terraform/projects/infra-security-groups/deploy.tf
- We have a Jenkins job that runs after the data sync jobs, called
"trigger data sync complete". This has been failing while trying to
trigger the integration one, because access to
`https://deploy.integration.publishing.service.gov.uk` has been
failing. The IPs in each of the `carrenza_{environment}_ips` variables
in govuk-aws-data look good, they're just not referenced anywhere in
the security groups for the deploy ELB.
=> Allow Production Carrenza to talk to Integration

terraform/projects/fastly-datagovuk/README.md, terraform/projects/fastly-datagovuk/main.tf, terraform/projects/fastly-datagovuk/production.govuk.backend
This is the basic definition for data.gov.uk's Fastly service. The current resource has been imported, and the definition written so that `plan` results in no changes. Soon, I'll be changing this so it has different backends for different paths. There's only a `production` backend as there's only a Production service.
This is a proof-of-concept. I'd like a little discussion on whether this is the right place for this. This is a well-structured terraform repo and framework, so it's easy to put it here. However, this isn't actually AWS so it's a bit weird.
=> Manage Fastly service for data.gov.uk in Terraform

terraform/projects/app-mongo/main.tf, terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/bucket_policy.tf, terraform/projects/infra-database-backups-bucket/main.tf, terraform/projects/infra-database-backups-bucket/reader.tf, terraform/projects/infra-database-backups-bucket/writer.tf
- We have a requirement to make the production database backup S3 bucket
, readble by the staging and integration environments.
- This was necessary to reduce the backup duplication.
https://trello.com/c/9B3bGNK3/1200-write-or-modify-s3-bucket-policies-to-allow-staging-and-integration-to-read-backups-from-production
Pair: @schmie  @suthagarht
=> AWS S3 Cross Account Access

terraform/projects/infra-security-groups/graphite.tf
- In AWS grafana living on the same instance as graphite can no longer
access graphite as a data source
Pair: @schmie @benthorner
=> Allow ingress of graphite to self for grafana

terraform/projects/app-monitoring/main.tf, terraform/projects/infra-security-groups/monitoring.tf
- This is used by a number of fabric scripts attempting to contact
alert.cluster (and possibly others).
- This seems to be expected behaviour and is isolated/limited to the
internal network.
@schmie
=> Fix SSH access to alert from jumpbox

terraform/projects/infra-email-alert-api-archive/main.tf
This sets up a few resources to run a glue crawler that populates a partitioned database for querying the Email Alert API archives.
This:
- bumps the AWS terraform provider so we can use the glue methods
- creates a database for Email Alert API data
- creates a role that glue crawler can run as
- a policy so the glue crawler can access the data
- the crawler itself running on a 4 hour interval
- the schema for the database table defining the appropriate types for the JSON data and partitioning
=> Email alert api glue crawler

terraform/projects/infra-fastly-logs/main.tf
This sets up crawlers to run with the 3 strands of log files we have being sent from Fastly to S3: govuk-www, govuk-assets and bouncer.
It sets up a database for these 3 log files and a schema based on the format Fastly is configured to send (details of this is in the individual commits)
Finally this deletes logs from these buckets when they reach 90 days old.
=> AWS Glue Crawlers for log files

terraform/projects/infra-email-alert-api-archive/main.tf
Trello: https://trello.com/c/FM3MCuAl/255-investigate-email-alert-api-database-size-and-push-email-archives-to-s3
The field, subscriber_id, was incorrectly set up as a string with the expectation that this field would be a UUID. In fact it is actually an integer in Email Alert API so this updates this to match.
=> Change field type for Email Alert API DB definition

terraform/projects/app-monitoring/additional_policy.json
- We have made some changes to enable Icinga to report on AWS RDS
instances and Elastic Cache instances. We had to provide some additional
access privileges to the blue-monitoring instance to fulfil this need.
- We have added the following exceptions.
- Allow blue-monitoring to list and read 'CloudWatch' and 'CloudWatch
Logs'
- Allow to list 'ElasticCache'
- Allow to list and read on RDS.
https://trello.com/c/C7SY8edZ/1123-monitor-rds-and-elasticache-in-aws-and-alert-icinga
Solos: @suthagarht
=> AWS blue-monitoring IAM policy.

terraform/modules/aws/rds_instance/README.md, terraform/modules/aws/rds_instance/main.tf, terraform/projects/app-mysql/README.md, terraform/projects/app-mysql/main.tf, terraform/projects/app-postgresql/README.md, terraform/projects/app-postgresql/main.tf, terraform/projects/app-transition-postgresql/README.md, terraform/projects/app-transition-postgresql/main.tf, terraform/projects/app-warehouse/main.tf
- We don't specify an instance name when we create AWS RDS instances.
Hence, a default name is issued at creation. For example, it would look
like the following. 'terraform-20180410102142467900000002'
- This poses two issues.
- It is difficult to view the AWS RDS console and determine the
instance visually, without selecting the instance and checking other
notations.
- We identified that it is difficult to create Icninga checks with
dynamic names.
- To address the above mentioned issues, we are implementing the
`identifier` attribute of the `aws_db_instance` Terraform module.
https://trello.com/c/C7SY8edZ/1123-monitor-rds-and-elasticache-in-aws-and-alert-icinga
=> AWS RDS Instance naming.

terraform/projects/infra-artefact-bucket/main.tf
- We noticed that the artefact S3 bucket policy was failing when applied
via terraform. The same policy can be copied and pasted via the
console.
- The error that we noticed was referring to the format of the policy.
'* aws_s3_bucket_policy.govuk-artefact-bucket-policy: Error putting S3 policy: MalformedPolicy: Invalid principal in policy
status code: 400, request id: 1CCFE75F22EA31F3, host id:
g3IOHI35MTShg41/2AGEYOajDwUQMkPz1ttHfzrisC4EeGOZST5xY2HOiJEhqKNOIUNevK3NnKg='
- This seems to be caused by the line that has been removed.
- We have tested that the functionality is still available.
https://trello.com/c/366S8eBR/1309-start-building-production
Pair: @szd55gds @suthagarht
=> Changes to the artefact-s3-bucket policy

terraform/projects/app-db-admin/main.tf, terraform/projects/app-graphite/main.tf, terraform/projects/app-mongo/main.tf, terraform/projects/app-router-backend/main.tf, terraform/projects/app-rummager-elasticsearch/main.tf, terraform/projects/app-transition-db-admin/main.tf, terraform/projects/app-warehouse-db-admin/main.tf, terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/reader.tf, terraform/projects/infra-database-backups-bucket/writer.tf
- We had an AWS IAM policy called "database_backups_writer". This policy
provided write access to the "govuk-production-database-backups" bucket.
This policy was attached to the instances created by the "app-mongo"
project.
- The requirement has changed. We want the AWS Production environment
mongo instances to be able to write to the object called "govuk-production-database-backups/mongo-api".
We also need to provide read access to this location for the AWS  staging and integration environments.
- To accomplish this, we have modified the "writer" policy. The modified
policy will define a single resource per project. This enables us to
limit which objects within the bucket can be accessed (prefix). We are
using the prefix value in the backup script. …
=> AWS S3 Database Backup Writer

terraform/projects/infra-fastly-logs/main.tf
This changes the configuration of the Glue Crawlers that work with the data from Fastly logs. After a lot of fighting with Fastly logging formats I've found we can get it to output JSON and that seems to offer best options of reliable athena parsing and future extensibility.  The logs are now output in this so this updates the crawler to deal with them.
This also changes the delete behaviour to remove tables and partitions when they are gone. This is because we have a 90 day retention on objects and want the database to deal with them being removed.
=> Change Fastly logs Glue Crawler configuration

terraform/projects/infra-govuk-repo-mirror/main.tf
This is needed to persist the state to S3
=> Add backend configuation for govuk-repo-mirror project

terraform/projects/app-mongo/main.tf
- The IOPS limit on EBS volumes attached to mongo instances was very low (100).
- This had severe impact on performance, especially during synchronisation.
solo @schmie
=> Fix EBS type on Mongo instances

terraform/projects/app-performance-backend/production.blue.backend, terraform/projects/app-performance-backend/staging.blue.backend, terraform/projects/app-performance-frontend/production.blue.backend, terraform/projects/app-performance-frontend/staging.blue.backend, terraform/projects/app-performance-mongo/production.blue.backend, terraform/projects/app-performance-mongo/staging.blue.backend
- We don't have them in integration and shouldn't have them in staging
or production. They're moving to the PaaS.
=> Remove the app-performance-(backend,frontend,mongo) projects

terraform/projects/infra-security-groups/pgbouncer.tf
pgbouncer listens on port 6432
[Trello card](https://trello.com/c/BosbZ9n9/336-investigate-postgres-connection-pooling)
=> Allow port 6432 to db-admin

terraform/projects/app-db-admin/main.tf, terraform/projects/infra-security-groups/db-admin.tf, terraform/projects/infra-security-groups/pgbouncer.tf
[Trello card](https://trello.com/c/BosbZ9n9/336-investigate-postgres-connection-pooling)
- Add pgbouncer listener to the db_admin ELB:
- Allows backend etc machines to connect to pgbouncer running on db_admin boxes.
- Allow pgbouncer traffic to and from ELB 
- Allow applications to talk to db_admin ELB on 6432, but not db_admin directly.
- Allow ELB to talk to pgbouncer on db_admin
=> Enable pgbouncer traffic 

terraform/projects/app-db-admin/main.tf, terraform/projects/app-graphite/main.tf, terraform/projects/app-mongo/main.tf, terraform/projects/app-router-backend/main.tf, terraform/projects/app-rummager-elasticsearch/main.tf, terraform/projects/app-transition-db-admin/main.tf, terraform/projects/app-warehouse-db-admin/main.tf, terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/reader.tf, terraform/projects/infra-database-backups-bucket/writer.tf
- While executing cleanly, the current terraform created policies
including warnings.
- Access of machines to the database backups bucket was only 
partially working
- Non-prod machines need to be able to write to their own 
backup buckets
solo @schmie
=> Fix Terraform for S3 access to database backups

terraform/userdata/00-base, tools/govuk-puppetmaster-bootstrap.sh
Add GOV.UK Apt repos in 00-base cloud-init snippet.
Install the signing key and configure (one of) the GOV.UK Apt repos (awscli).
Install awscli in 00-base with apt, and don't install it in `tools/govuk-puppetmaster-bootstrap.sh` with pip.
=> Install the AWS CLI from the Apt repo instead of from Pip

terraform/projects/app-db-admin/additional_policy.json, terraform/projects/app-db-admin/main.tf
We give the right to db-admin instance to create an RDS to do
database scrubbing before importing them in integration.
=> Add RDS policy to db-admin instance

terraform/projects/infra-security/main.tf
- This inconsistency is annoying for everyone new to assume-role, and
our docs are even inconsistent. Instead of changing the docs, change the
pluralization of the role name to match `govuk-administratorS` and
`govuk-userS`, as now it's just a snowflake and always takes some time
to debug problems with people's config because of what is essentially
a typo.
=> Pluralize the `govuk_poweruser` role name to match the other roles

terraform/projects/infra-vpc/README.md, terraform/projects/infra-vpc/main.tf
This creates the two gateways and a VPN for connecting the VPC to Carrenza. There are 2 new variables to add in govuk-aws-data also. This should create the VPN and then we can get the created configuration to use to update the VCloud configuration in govuk-provisioning to deploy the Carrenza side of things.
=> New VPC resources for VPN to Carrenza.

terraform/projects/app-transition-db-admin/main.tf, terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/reader.tf, terraform/projects/infra-database-backups-bucket/writer.tf
- The new access policy filters for the S3 bucket in
infra-database-backups-bucket are based on prefixes.
- New policies added in infra-database-backups-bucket need a
corresponding change in the app terraform to attach properly.
- Re-apply of both projects is required
pair @schmie @szd55gds
=> Add separate access policy for transition

terraform/projects/app-warehouse-db-admin/main.tf, terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/reader.tf, terraform/projects/infra-database-backups-bucket/writer.tf
s3 read/write policies required to permit adding warehouse-db_admin in AWS to the env_backup app.
=> Add warehouse db admin policy to access s3 backup buckets

terraform/projects/infra-fastly-logs/main.tf
This has no actual code changes, just updates the comments to match an outside configuration change.
After a long support thread with fastly trying to debug getting JSON to
escape properly they unveiled a new json.escape function which makes all
our escaping simpler. This switches all places where we're using custom
escaping to that.
Also fixes a typo on correlate
=> Switch to using json.escape for fastly log formatting

terraform/projects/infra-database-backups-bucket/reader.tf, terraform/projects/infra-database-backups-bucket/writer.tf
We use the name mongo-router to stay coherent with the old
system
=> Change the S3 prefix router_backend to mongo-router

terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/reader.tf, terraform/projects/infra-database-backups-bucket/writer.tf
- We want to separate out RDS instances for publishing-api and
email-alert-api due to load.
- For symmetry we have decided to instantiate one db_admin per RDS.
- The new publishing-api-db_admin need a policy to read/write to
sync/backup buckets
solo: @schmie
=> Adding publishing-api RDS access to backup S3

terraform/projects/app-backend/main.tf
Reverts alphagov/govuk-aws#623
As per https://govuk.zendesk.com/agent/tickets/3107683.
=> Revert "Increasing the size of the root partition of backend from 30G to 60G"

terraform/userdata/30-deploy-apps
We need to wait for the deploy user to be created before we can
deploy apps on a newly created machine.
=> Modify the deploy-app snippet to wait for the deploy user creation

terraform/projects/infra-security-groups/cache.tf
This has to be done directly to the cache box because each
box houses its own siloed cache and we need them all cleared.
https://trello.com/c/f8U7EfUh/427-make-the-new-cache-clearing-app-invalidate-cache-in-varnish
=> Permit backend boxes to clear varnish caches

terraform/projects/app-db-admin/main.tf, terraform/projects/app-graphite/main.tf, terraform/projects/app-router-backend/main.tf, terraform/projects/app-transition-db-admin/main.tf, terraform/projects/app-warehouse-db-admin/main.tf, terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/reader.tf
- In order to grant cross-account access to buckets in multiple
environments (e.g. integration AND staging S3 access from integration) we
need to be able to manipulate policies in individual ways.
- We thus have removed the parametrised creation of these policies in
favour of explicit definition per environment.
pair: @issyl0 @schmie
=> Refactor database-backups-bucket access policies

terraform/projects/infra-database-backups-bucket/reader.tf
- For the data sync to integration, we read from the staging bucket if
the databases don't have to be sanitized. This is currently failing as
the IAM policies don't have permissions to read from the staging
bucket.
- This *doesn't* allow the sanitized databases to read unsanitized data
from the staging backups bucket, apart from in the case of whitehall
which is wrapped up in the `dbadmin` IAM role.
https://trello.com/c/9Oa4A8ji/1439-make-the-new-data-sync-work-for-non-sanitized-integration-databases-s
=> Allow integration to read the govuk-staging-database-backups bucket

terraform/projects/app-email-alert-api-db-admin/main.tf, terraform/projects/app-publishing-api-db-admin/main.tf, terraform/projects/app-rummager-elasticsearch/main.tf
- The new db-admins don't exist everywhere yet, but they will when we
rebuild, and to avoid errors we should do this.
=> Attach IAM reader policies to rummager-elasticsearch, publishing-api-db-admin and email-alert-api-db-admin

terraform/projects/app-frontend/main.tf
- This was t2.medium and could not cope with an increase in worker procs
imposed by platform health.
- Switched to t3 for testing purposes as well
solo: @schmie
=> Change frontend instance type to t3.large

terraform/projects/infra-database-backups-bucket/bucket_policy.tf
- Explicit access to keys resource in a bucket is required in addition
to bucket access (ie arn:::bucket/* as well as arn:::bucket) in order to
allow read access
- We missed this testing ls instead of cp, the former only needs bucket
access.
solo @schmie
=> Add key access permissions to cross account policy

terraform/modules/aws/rds_instance/README.md, terraform/modules/aws/rds_instance/main.tf, terraform/projects/app-email-alert-api-postgresql/README.md, terraform/projects/app-email-alert-api-postgresql/main.tf, terraform/projects/app-mysql/README.md, terraform/projects/app-mysql/main.tf, terraform/projects/app-postgresql/README.md, terraform/projects/app-postgresql/main.tf, terraform/projects/app-publishing-api-postgresql/README.md, terraform/projects/app-publishing-api-postgresql/main.tf, terraform/projects/app-transition-postgresql/README.md, terraform/projects/app-transition-postgresql/main.tf, terraform/projects/app-warehouse/README.md, terraform/projects/app-warehouse/main.tf
The setting of [final snapshot](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_DeleteInstance.html) on an RDS instance was controlled by the `rds_instance` module which defaulted it to `true`. This wasn't being overridden by any of the database projects that used the module.
Change the default to `false` to match the Terraform and AWS default and make it production safe.
Add the same variable to each of the database projects.
There is a corresponding data PR to set the values per environment - https://github.com/alphagov/govuk-aws-data/pull/211
=> Control RDS final snapshots

terraform/projects/infra-monitoring/main.tf
This commit adds a user that will be used to generate an access key and secret key for the AWS X-Ray daemon. It also correctly attaches the policy to the existing role.
Trello: https://trello.com/c/YMZBPMGF/450-provision-x-ray-and-set-up-permissions-%F0%9F%8D%90-portunity
=> Add user for AWS X-Ray daemon

terraform/policies/transition_executor_policy.tpl
The query is failing in production with:
> Unable to verify/create output bucket
> govuk-production-transition-fastly-logs
So this commit grants the same S3 permissions on the output bucket as
the AmazonAthenaFullAccess example policy, other than s3:CreateBucket.
There's no need to grant s3:CreateBucket as the bucket already exists.
https://docs.aws.amazon.com/athena/latest/ug/access.html
---
[Trello card](https://trello.com/c/dNtEfmJM/395-move-transition-hit-stats-processing-to-s3-and-athena-%F0%9F%8D%90-portunity)
=> Grant more S3 permissions on Athena output bucket

tools/govuk-puppetmaster-bootstrap.sh
- These have cost us some grieve in the past in case installation
methods change (awscli via apt, rather than pip -> /usr/bin, rather than
/usr/loocal/bin)
- We should rely on the PATH variable to configure these correctly
solo: @schmie
=> Refactor puppetmaster bootstrap

terraform/projects/app-db-admin/additional_policy.json
Required for the scrubber to clean up after itself and delete old snapshots.
=> Allow db-admin to delete snapshots

terraform/projects/app-apt/README.md, terraform/projects/app-apt/main.tf, terraform/projects/app-ckan/README.md, terraform/projects/app-ckan/main.tf, terraform/projects/app-deploy/README.md, terraform/projects/app-deploy/main.tf, terraform/projects/app-graphite/README.md, terraform/projects/app-graphite/main.tf, terraform/projects/app-logs-cdn/README.md, terraform/projects/app-logs-cdn/main.tf, terraform/projects/app-mapit/README.md, terraform/projects/app-mapit/main.tf, terraform/projects/app-mirrorer/README.md, terraform/projects/app-mirrorer/main.tf, terraform/projects/app-mongo/README.md, terraform/projects/app-mongo/main.tf, terraform/projects/app-monitoring/README.md, terraform/projects/app-monitoring/main.tf, terraform/projects/app-rummager-elasticsearch/README.md, terraform/projects/app-rummager-elasticsearch/main.tf
- This variable is set in `govuk-aws-data` common.tfvars per
environment. This is because we don't want to enable this just yet in
integration, but we do want it in staging and production because we're
starting afresh with those environments.
- This was a recommendation from the AWS well-architected review.
https://trello.com/c/GsT3KAMg/1479-enable-encryption-at-rest-on-several-ebs-volumes
=> Enable encryption on all EBS volumes, per environment

terraform/modules/aws/rds_instance/README.md, terraform/modules/aws/rds_instance/main.tf, terraform/projects/app-email-alert-api-postgresql/README.md, terraform/projects/app-email-alert-api-postgresql/main.tf, terraform/projects/app-email-alert-api-postgresql/staging.blue.backend, terraform/projects/app-mysql/staging.blue.backend, terraform/projects/app-postgresql/README.md, terraform/projects/app-postgresql/main.tf, terraform/projects/app-postgresql/staging.blue.backend, terraform/projects/app-publishing-api-postgresql/README.md, terraform/projects/app-publishing-api-postgresql/main.tf, terraform/projects/app-publishing-api-postgresql/staging.blue.backend, terraform/projects/app-transition-postgresql/README.md, terraform/projects/app-transition-postgresql/main.tf, terraform/projects/app-transition-postgresql/staging.blue.backend, terraform/projects/app-warehouse/README.md, terraform/projects/app-warehouse/main.tf, terraform/projects/app-warehouse/staging.blue.backend
This makes AWS create internal HA replicas in a different AZ from the primary DB of each RDS instance. These are not available for us to use as read-replicas but rather for use in a failover situation where the primary DB AZ fails. This failover and recovery is managed automatically by RDS. At the moment our RDS instances are not HA.
=> Add Multi-AZ support for RDS databases in Staging.

terraform/policies/terraboard_policy.tpl, terraform/projects/infra-monitoring/README.md, terraform/projects/infra-monitoring/main.tf
This commit adds new IAM users that have read-only access to the S3 buckets that hold Terraform state for each AWS environment. These users will have keys generated that will be provided to Terraboard for authentication.
Trello: https://trello.com/c/6UMlTRpa/490-get-terraboard-running-on-the-monitoring-machines-in-each-environment
=> Add IAM users for Terraboard

terraform/queries/transition_logs_query.sql
This causes problems around midnight, where a request can be received
on one day but be logged for the next, if the duration of the request
pushed it over the day change.  The SELECT hard-codes the date, rather
than returning the request_received, so we see two apparently
identical requests on the same day.
We don't really need the data to be as precise as possible, so we'll
just say that all requests which finished processing on a given day
were received on that day.  The error introduced in Day N by pushing
some requests on Day N+1 is resolved by some requests on Day N+1
inevitably being pushed to Day N+2, and so on.
---
[Trello card](https://trello.com/c/dNtEfmJM/395-move-transition-hit-stats-processing-to-s3-and-athena-%F0%9F%8D%90-portunity)
=> Do not group Athena query results by request_received

terraform/modules/aws/rds_instance/main.tf
Replica RDS instances don't support final snapshots. With `final_snapshot_identifier` set, we're getting an error from the API when destroying a replica instance.
=> Don't set final snapshot parameters on RDS Replicas

terraform/projects/app-monitoring/main.tf
This commit increases the size of the monitoring machines to double the amount of RAM since they will now be running Docker and Terraboard.
Trello: https://trello.com/c/6UMlTRpa/490-get-terraboard-running-on-the-monitoring-machines-in-each-environment
=> Increase size of monitoring machines

terraform/policies/terraboard_policy.tpl
This commit changes the S3 buckets that Terraboard reads from. Steppingstone is the new one.
Trello: https://trello.com/c/6UMlTRpa/490-get-terraboard-running-on-the-monitoring-machines-in-each-environment
=> Change S3 buckets for Terraboard

terraform/policies/xray_traces_assume_policy.tpl, terraform/policies/xray_traces_policy.json, terraform/projects/infra-monitoring/main.tf
This commit:
* Detaches the X-Ray permissions policy from the X-Ray user because that user is only used to assume the X-Ray role, which needs the permissions
* Changes the principal used in the X-Ray assume policy to be the X-Ray user
* Removes unknown X-Ray permissions
=> Fix AWS X-Ray permissions

terraform/policies/terraboard_policy.tpl, terraform/projects/infra-monitoring/main.tf
This commit adds versioning permissions for Terraboard’s access to the Terraform state S3 buckets, which is required to compare across multiple versions of a state file.
Trello: https://trello.com/c/6UMlTRpa/490-get-terraboard-running-on-the-monitoring-machines-in-each-environment
=> Add more permissions for Terraboard

terraform/projects/infra-database-backups-bucket/reader.tf, terraform/projects/infra-database-backups-bucket/writer.tf
Relax the glob patterns to match just the database names rather than `dbname-dbms` (e.g. `email-alert-api` instead of `email-alert-api-postgres`).
=> Update database backup bucket policies

doc/architecture/decisions/0003-aws-networking-outline.md, doc/architecture/decisions/0033-ip-ranges.md
- We have changed our original plans for parity between Carrenza
and AWS IP ranges, in light of requiring a VPN connection
between parts of the stack.
- Mark the original ADR, 0003, as partly superseded.
=> Create ADR 0033 for the new IP address ranges

terraform/projects/app-draft-frontend/main.tf
- We see draft-frontend instances freeze up due to OOM killings
- This bump has prior been applied to the frontend nodes as well
solo: @schmie
=> Increase draft-frontend instance size to t3.large

terraform/queries/transition_logs_query.sql
The current Transition logs importer uses a threshold of 10 to exclude
infrequently hit paths.  This has a massive effect on the number of
hits reported: on 2018-09-18 there are 8404 entries in the hit stats
file with the threshold, and 481371 without.
In principle, dropping this threshold would allow more precise
statistics.  However, after the logs are imported into Transition
every day, the statistics are generated from scratch.
Going from 10,000 records a day to nearly 500,000 is likely to reveal
inefficiencies in the current code, which we otherwise would not have
to worry about for years.
---
[Trello card](https://trello.com/c/dNtEfmJM/395-move-transition-hit-stats-processing-to-s3-and-athena-%F0%9F%8D%90-portunity)
=> Do not report hits under 10 occurrences

doc/guides/environment-provisioning.md
There were four missing projects that have now been added. For a list of these check in the repo `govuk-aws/terraform/projects`
=> Adding new management stack projects

terraform/modules/aws/elasticache_redis_cluster/main.tf
`engine_version` of elastic cache for redis must be fixed to 3.2.10 because latest is not compatible with redis 3.2
=> specify engine version

terraform/projects/infra-datagovuk-organogram-bucket/README.md, terraform/projects/infra-datagovuk-organogram-bucket/datagovuk-write-policy.tf, terraform/projects/infra-datagovuk-organogram-bucket/fastly-read-policy.tf, terraform/projects/infra-datagovuk-organogram-bucket/integration.govuk.backend, terraform/projects/infra-datagovuk-organogram-bucket/main.tf, terraform/projects/infra-datagovuk-organogram-bucket/production.govuk.backend, terraform/projects/infra-datagovuk-organogram-bucket/staging.govuk.backend
We are using a S3 bucket to store organograms in the new data.gov.uk publishing tool (upgraded CKAN).
This Terraform will: 
- Provision a S3 bucket `datagovuk-organogram` for storing organogram data for data.gov.uk
- Create a user `s3_datagovuk_organogram_writer_user` that will be used by CKAN to write organograms to this bucket
- Ensure Fastly is able to read from this bucket
Trello card: https://trello.com/c/odHiWSoq/63-implement-upload-organogram-to-s3
=> Add a S3 bucket for data.gov.uk organograms

terraform/projects/app-transition-db-admin/main.tf
allow production transition db admin server role to access the staging transition database so as to transfer transition data to new RDS in AWS production
Co-Authored-By: Conor Glynn
=> transition db admin server role changes

doc/architecture/decisions/0035-alb-ssl-redirect.md, terraform/modules/aws/lb/main.tf, terraform/projects/infra-public-services/main.tf
Add port 80 as a new listener for the bouncer load balancer
2 bugs have been found in the "aws/lb" terraform module and fixed:
1. `ssl_policy` is set for non-ssl listener. an option is set by its mere presence in terraform resource. Hence, there is a need to have 2 listener resource definitions: one for ssl and one for non-ssl.
2. secondary certificates were add to all listeners including the non-ssl listeners
=> Add port 80 bouncer load balancer

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
This commit creates a new role named `platformhealth-powerusers`. This role will be assumed by developers with production access who are in the Platform Health team. The main reason is to split the currently large `powerusers` role which has hit hard AWS limits on size.
=> Create Platform Health powerusers role

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/mapit.tf, terraform/projects/infra-security-groups/outputs.tf, terraform/projects/infra-security-groups/variables.tf
When transitioning from Carrenza to AWS provider, it was decided to split the different different components of the Mapit service across the 2 providers for operational reasons.
In essence:
1. the backend of the Mapit service will reside in the AWS provider along with its database
2. the frontend of the Mapit service will still reside in the Carrenza provider
There is a need for the frontend of Mapit in Carrenza to access its Backend in AWS. The current terraform plans do not allow for this because backend services are by default within private subnets.
The decision is to create an Application load balancer in AWS which allows Carrenza IPs to access the Mapit backend in AWS. 
1. https://trello.com/c/CFCVBVZS/1643-create-configure-inet-facing-mapit-load-balancer-with-limited-reachability …
=> add mapit alb and security group for Carrenza

terraform/projects/app-draft-cache/main.tf, terraform/projects/infra-security-groups/draft-cache.tf
This commit adds a DNS CNAME entry for `draft-publicapi` and also allows the draft_cache ELB to route to itself similar to the live stack cache machines.
Trello: https://trello.com/c/JDiLJ8h1/570-enable-viewing-content-store-on-draft-stack
=> Add draft-publicapi DNS and firewall entries

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
alert and alert.cluster CNAMES should point to
alert.blue.'env'.govuk-internal.digital
But due to the way the code is setup alert will point correctly but
alert.cluster will end up pointing to alert.cluster.'env'.govuk-internal.digital
which does not go anywhere.
This fix will get both records pointing into the correct destination.
Solo: @ronocg
=> GovUK-Migr-Trello-16: Fix CNAMES for monitoring

terraform/projects/app-bouncer/main.tf
- These had been spec'd a bit tight for my liking.
- Load in Carrenza seems overall low, but I rather reduce instance size
then risk running into overloading issues on migration
solo: @schmie
=> Bump bouncer instance sizes pre-migration

terraform/modules/aws/lb/main.tf
For secondary certificate attachment:
1. IF certificate name is PRESENT, then CREATE attach certificate to HTTPS listeners only
2. ELSE do not create secondary certificate attachment
TESTING:
1. tested for `infra-public-services` project for no change -> module keeps previous functionality
2. tested for `app-bouncer` project for no secondary certificate created -> fix issue
=> fix the aws/lb module for when no secondary certificate is specified

terraform/projects/infra-security/main.tf
Adding Policy to make sure they are unable to release/remove
EIPs from the environments.
The reason we wish to deny removal of the EIPs, is that we do not want
the EIPs changing. These EIPs are attahced to teh NAT gateways and if we
did have to re-spin the nat gateways then we would re-attach these EIPs
again.
This needs to be merged with branch https://github.com/alphagov/govuk-aws-data/tree/GovUK-Migr-Trello-1646
Pair: @ronocg @th31nitiate
=> GovUK Migr Trello 1646: Deny EIP Release

tools/govukcli
Reverts alphagov/govuk-aws#682
This change is throwing up the following error[1] for myself and @theseanything, but undoing it for on my GDS MacBook running bash works again.
1
```bash
$govukcli ssh monitoring                            
unknown option -- -
usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
[-D [bind_address:]port] [-E log_file] [-e escape_char]
[-F configfile] [-I pkcs11] [-i identity_file]
[-L [bind_address:]port:host:hostport] [-l login_name] [-m mac_spec]
[-O ctl_cmd] [-o option] [-p port]
[-Q cipher | cipher-auth | mac | kex | key]
[-R [bind_address:]port:host:hostport] [-S ctl_path] [-W host:port]
[-w local_tun[:remote_tun]] [user@]hostname [command]```
=> Revert "Fix govukcli bug"

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
During the AWS migration, it is desirable to have traffic replay from Carrenza Staging to AWS staging for the `content-store` app. 
Since the traffic is HTTPS and uses the production certificate, the load balancer in AWS Staging must have this production certificate also. 
Unfortunately, the classic public load balancer in AWS staging for the content-store does not allow a secondary certificate.
1. Create an application load balancer (rather than a classic load balancer) for the content-store. This load balancer will have both AWS certificate as well as the production one. This will allow this application load balancer to terminate the Gor traffic replace.
2. The application load balancer is created via a terraform module (has no count option) and is present for all AWS environment and …
=> add content store external elb for gor traffic replay

terraform/projects/infra-security-groups/ckan.tf
The name is already being used elsewhere
=> Rename `ckan_access` security group for SSH control

terraform/projects/app-draft-content-store/README.md, terraform/projects/app-draft-content-store/main.tf, terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/draft-content-store.tf, terraform/projects/infra-security-groups/variables.tf
Extends the allow list in the security group in Staging and Prod.
Integration has migrated so will use a blank list (default value).
Adding a public service dns entry for draft-content-store to the
external root dns.
This is required as part of the migration work for draft-content-store.
Authored-by: Conor Glynn <conor.glynn@digital.cabinet-office.gov.uk> & Julian Standring <julian.standring@digital.cabinet-office.gov.uk>
=> Add carrenza draft-frontend access to aws draft-content-store

terraform/projects/infra-carrenza-vpn/README.md, terraform/projects/infra-carrenza-vpn/main.tf, terraform/projects/infra-carrenza-vpn/production.govuk.backend, terraform/projects/infra-vpc/README.md, terraform/projects/infra-vpc/main.tf
- Carrenza expects 32 digit alphanumerical PSK
- Carrenza needed to configure a single subnet of /20 range in order for
the VPN to work AWS side
aws-data part: https://github.com/alphagov/govuk-aws-data/pull/256
pair: @schmie @stephenharker
=> Add explicit PSK for AWS production VPN to Carrenza

terraform/projects/app-warehouse/main.tf
The data syncs are failing because there's not enough space for it
to carry out the job.
https://deploy.publishing.service.gov.uk/job/copy_data_to_integration/857/console
=> Double disk size for warehouse db

.gitignore, terraform/modules/aws/lb/README.md, terraform/modules/aws/lb/main.tf, terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/backend.tf, terraform/projects/infra-security-groups/outputs.tf, terraform/projects/infra-security-groups/support-api.tf
This adds an application load balancer for the support-api service.
The support-api services resides on the backend instances, the backend
instances already have an LB associated with them as the other services
that run on the backend need to be accessible by the world, but
support-api needs to be tied down to the carrenza egress ips.
Therefore here we place a rule on the current backedn application load
balancer that gives back a 404 for support-api host-headers. And we
roll a new ALB that is limited via security group to the carrenza egress
ips, the new ALB will only be used for support-api backend services.
Solo: @ronocg <conor.glynn@digital.cabnet-office.gov.uk>
=> Trello-1796: Add ALB for support-api

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/outputs.tf, terraform/projects/infra-security-groups/variables.tf, terraform/projects/infra-security-groups/vpn.tf
The VPN resources / security group will not exist in integration_aws but
will exist in staging and production aws.
This PR is to put in place a count loop for the vpn security group and
rules, so that terraform will not attempt to create them for
environments that do not have the correct variable set.
Solo: @ronocg <conor.glynn@digital.cabinet-office.gov.uk>
=> BAU: Fixup Terraform resources for VPN

terraform/projects/infra-govuk-repo-mirror/README.md, terraform/projects/infra-govuk-repo-mirror/main.tf
This commit adds the Jenkins SSH public key for the relevant environment to the CodeCommit IAM user. This will allow the Jenkins Deploy_App job to deploy apps from CodeCommit repositories.
Depends on: https://github.com/alphagov/govuk-aws-data/pull/269
=> Add Jenkins SSH key to CodeCommit IAM user

terraform/projects/infra-security-groups/content-store.tf
The content-store external ALB and external ELB in staging_aws and
production_aws are currently opened to the world. Here we are limiting
access to the content-stores from the corresponding environment in
Carrenza. This is so teh frontends in Carrenza which have not been
migrated yet are allowed to talk with the content-store.
Allowing the GDS Office IP ranges in also. 
Solo: @ronocg <conor.glynn@digital.cabinet-office.gov.uk>
=> Trello-1808: Tie down access to content-stores AWS

terraform/projects/infra-security-groups/content-store.tf
We don't want the office IPs to be able to access the content-store
external IP address directly for now, it should only be the relevant IPs
in the GOV.UK Carrenza environment.
=> Remove Office IPs from external CS access

tools/deploy.rb
This commit adds a Ruby deploy script to simplify the process of deploying Terraform.
The script accepts the same input as the Jenkins job, and also requires GitHub credentials.
It then uses `govukcli` (in the same directory) to generate temporary AWS credentials. The GitHub and AWS credentials, along with the initial command line input and a Jenkins “crumb” are used to queue the the `Deploy_Terraform_GOVUK_AWS` job in Jenkins.
Using Jenkins allows deployments to be auditable.
=> Add deploy script

terraform/projects/infra-public-services/main.tf
The content-store ALB has its healthcheck for its target backends
wrongly configured. The healthcheck path should be /_healthcheck.
Pair: @ronocg <conor.glynn@digital.cabinet-office.gov.uk
@karlbaker02 <karl.baker@digital.cabinet-office.gov.uk
=> 2ndline-trello-386: fix healthcheck for content-store alb

terraform/projects/app-calculators-frontend/README.md, terraform/projects/app-calculators-frontend/main.tf
We want to match the spec to Carrenza before moving the apps.
To do this the following is needed:
- Increase ASG size to 3
- Change EBS volume size from default 20 GB to 60 GB
- Change instance type to c5.xlarge
=> Increase spec of calculator-frontends

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/feedback.tf, terraform/projects/infra-security-groups/outputs.tf
Adding feedback public LB and dns entry for it in the environments root
zone. Also setting security groups to restrict access to feedback from
carrenza egress env IPs.
=> Trello-1827: Add feedback public lb

terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/feedback.tf, terraform/projects/infra-security-groups/variables.tf
The feedback ALB should be on the private subnets, as it will only
forward traffic to its target group that comes from Carrenza. The
private subnets have the carenza ranges in their routing tables.
Also setting the security group for the feedback ALB to be specific on
the carrenza ip ranges it is allowing inbound.
=> Trello-1827: Place ALB on the private subnet

terraform/projects/infra-security-groups/feedback.tf
This resource is not really required for integration but to keep the
code and environments as consistent as possible, this code will execute
for the integration environment. So we are placing a count on the
resource so if the variable does not exist then the rule will not be created.
@jstandring-gds <julian.standring@digital.cabinet-office.gov.uk>
=> BAU: adding a count for this resource

terraform/projects/infra-splunk/README.md, terraform/projects/infra-splunk/integration.govuk.backend, terraform/projects/infra-splunk/main.tf, terraform/projects/infra-splunk/production.govuk.backend, terraform/projects/infra-splunk/staging.govuk.backend
This policy and role is required by the Cyber Security Team, in order to
probe the resources and services in our account and gather that
info/data into splunk cloud. The policy has been passed directly to us
by the Cyber Team.
=> Trello-1885: Splunk Discovery

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/gatling.tf, terraform/projects/infra-security-groups/outputs.tf
We will start Gatling FrontLine instances using this security group.
It allows inbound traffic on port 22 and 80 and all outbound traffic.
[Trello Card](https://trello.com/c/kxP64gJo/700-redo-the-load-test-to-see-what-impact-weve-had-with-our-changes)
=> Add a security group for Gatling

terraform/projects/infra-security-groups/management.tf
This enables the prometheus server to scrape metrics from the
node-exporters (9080). The node-exporters run on each node in the
environment.
@jstandring-gds <julian.standring@digital.cabinet-office.gov.uk>
=> Trello-1900: Prometheus node-exporter SG rule

terraform/projects/app-prometheus/README.md, terraform/projects/app-prometheus/main.tf, terraform/projects/app-prometheus/production.blue.backend, terraform/projects/app-prometheus/staging.blue.backend, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/prometheus.tf
The prometheus elb is not required, there is an existing ALB that will
do the job it is spun up in infra-public-services.
Also allowing from the alb to the instance on port 80.
Putting config in place to roll prometheus to staging and production
also.
@jstandring-gds <julian.standring@digital.cabinet-office.gov.uk>
=> Trello-1903: Removing prometheus elb

terraform/projects/app-prometheus/main.tf, terraform/projects/infra-security-groups/prometheus.tf
The prometheus load balancer needs to be able to forward http traffic
down to the security group attached to the prometheus instance, this
commit puts that egress rule in place.
Also removingthe instance_elb_ids from teh prometheus module, as we are
no longer building an elb at this state level, there is an application
load balancer built within infra-public-services that takes care of the
laod-balancing to prometheus.
=> Trello-1903: update prometheus lb security group

terraform/projects/infra-security-groups/prometheus.tf
There needs to be a source_security_group_id defined, in this instance
the source security group would be the security that egress to, being
the prometheus instance security group.
=> Trello-1903: fix source security group

README.md, terraform/projects/infra-security/tools.govuk.backend, tools/deploy.rb
This account will contain resources that are one-off, or otherwise outside the usual production/staging/integration environments.
The initial user accounts and roles are identical to production.
=> Add user accounts for the new govuk-tools AWS account

terraform/projects/app-cache/README.md, terraform/projects/app-cache/main.tf
Other app projects only need to have asg_size variable to define the max, min and desired number of machine. Hence, we do the same for app-cache for uniformity because app-cache has no different requirements.
1. declare `asg_size` variable and use it to set the autoscaling max, min and desired number of instances. 
2. remove redundant variables.
=> normalize app-cache so that only asg_size variable is needed 

terraform/projects/infra-security/tools.govuk.backend
The previous name was already taken.
=> Rename tools tfstate bucket

terraform/projects/infra-security/tools.govuk.backend
This bucket is in London. Also, change the name back since we’ve now been able to create a bucket with the original name.
=> Change region for steppingstone S3 bucket

terraform/projects/infra-security-groups/cache.tf, terraform/projects/infra-security-groups/draft-cache.tf
In order to have Gor traffic replay between Carrenza and AWS cache machines, there is a need to allow Carrenza cache machines IPs to pass through the AWS cache ELB.
1. open the security group of the AWS Cache ELB to Carrenza outbound traffic IPs
=> allow carrenza cache machines to reach aws cache machines

doc/guides/redeploying-applications-on-rebuild.md, tools/migration-hosts.sh
This application no longer exists. The policy pages have been replaced
by topic pages, part of the GOV.UK Topic Taxonomy.
=> Remove references to Policy Publisher

tools/govukcli
Builds on top of https://github.com/alphagov/govuk-aws/pull/736
These changes mean that the following command works for example:
govukcli ssh --context staging-aws backend
I personally would like the govukcli ssh behaviour to be more
predictable, based on the command being run. So rather than relying on
the correct context being set, instead, passing it in every time and
being explicit. I think this is easier to understand and use, as well
as being less error prone.
=> Allow passing the context to govukcli ssh

terraform/projects/app-content-store/main.tf
The content-store in AWS production is complaining about a lack of disk space (most of the disk space is consumed by logs) and therefore, we need to increase it from its current 20 GB to 40 GB.
1. increase volume from 20GB to 40GB (no new variable was introduced from govuk-aws-data to keep the way it is done now)
=> increase content store ebs from 20 gb to 40gb

terraform/projects/fastly-datagovuk/README.md, terraform/projects/fastly-datagovuk/main.tf
This commit adds a Fastly API key (retrieved from SOPS) to be used when deploying the `fastly-datagovuk` project.
=> Add Fastly API key for data.gov.uk

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
A interruptibe task was raised by gov.uk 2nd line (@kevindew) to cname the draft-whitehall-frontend internal dns name to the whitehall-frontend internal dns name.
1. Modify the infra-public-services terraform project's logic to reflect this and then also modify the corresponding terraform aws data: https://github.com/alphagov/govuk-aws-data/pull/301
=> add draft_whitehall_frontend cnaming to whitehall_frontend

terraform/userdata/30-deploy-apps
We still have cases where the system try to deploy apps before
the deploy user is created.
=> Increase wait time for deploy user creation

terraform/projects/infra-govuk-repo-mirror/README.md, terraform/projects/infra-govuk-repo-mirror/main.tf
This commit adds a new IAM role which will be used by a new Concourse pipeline to backup all GOV.UK git repositories from GitHub to AWS CodeCommit in the `govuk-tools` account.
=> Add IAM role for CodeCommit Concourse pipeline

tools/govukcli
This commit fixes an issue with `govukcli` when used to run `aws` commands. In this case, it doesn’t correctly get the currently set context, which means any `aws` commands that are environment-specific fail.
=> Fix govukcli getting context for aws commands

tools/govukcli
This commit adds the new govuk-tools AWS account to `govukcli` so it can run commands against the new account.
=> Add govuk-tools account to govukcli

terraform/projects/infra-govuk-repo-mirror/README.md, terraform/projects/infra-govuk-repo-mirror/main.tf, terraform/projects/infra-govuk-repo-mirror/tools.govuk.backend
* Add tools backend (used by the new Concourse pipeline)
* Move the Concourse role ARN to a variable
* Fix the reference to the CodeCommit role
* Add a new user with SSH key for Concourse
=> Fix infra-govuk-repo-mirror project

terraform/projects/app-data-science/README.md, terraform/projects/app-data-science/main.tf
This commit ads an `office_ips` variable that is set in govuk-aws-data to allow office IPs to access the machines via SSH.
=> Add office IPs to data science machines

terraform/modules/aws/node_group/main.tf
This commit adds the Amazon owner ID to the list of AMI owners that images are filtered by. The ID `898082745236` is an Amazon owner ID that owns the deep learning Ubuntu AMIs.
=> Add Amazon owner ID to AMI owners

terraform/projects/app-data-science/main.tf
This commit increases the disk size of the data science machines from 20GB to 200GB to allow for the size of the AMI base image and computed data.
=> Add more disk space to data science machines

terraform/modules/aws/es_domain/README.md, terraform/modules/aws/es_domain/main.tf, terraform/projects/app-elasticsearch/README.md, terraform/projects/app-elasticsearch/main.tf
See also https://github.com/alphagov/govuk-aws-data/pull/311
---
With this change, planning locally fails complaining about missing keys in the remote state.  But one of them (`data.terraform_remote_state.infra_networking.private_subnet_names_ids_map`) is used in a bunch of other places, and I used the boilerplate remote state set-up.  So I suspect that this is some kind of local problem.
=> Fix elasticsearch snapshot hour format & linked service role name

terraform/projects/app-elasticsearch/main.tf
`list(foo)`, where `foo` is already a list, returns a nested list.
=> Remove double-listing of elasticsearch subnet names

terraform/modules/aws/es_domain/main.tf
The terraform documentation is wrong:
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/slr-es.html
=> Change aws linked service name to es.amazonaws.com

terraform/projects/app-postgresql/main.tf
This commit increases the PostgreSQL primary DB instances to the next instance class to provide more CPUs and RAM. This is due to CKAN now using this database, resuting in increased load. The instances are changed from M4 to M5 since they have improved performance and are cheaper for the equivalent instances than M4.
The changes will be made during the next maintenance window, which is Monday 4-6am, since `apply_immediately` is not set and defaults to `false`.
Trello: https://trello.com/c/gEzC3bPn/756-add-more-resources-to-aws-rds
=> Increase PostgreSQL primary DB to next instance class

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
As part of the AWS migration of the licence finder frontend, the frontend needs to directly contact the rummager elastic search instances directly. These instances are not migrated from Carrenza. Hence, we need to add internal DNS A records so that AWS license finder can find the Carrenza rummager elastic search instances.
1. Add A records for the Carrenza rummager elastic search instances in the AWS internal DNS.
1. The data for the logic applied here is located in PR: https://github.com/alphagov/govuk-aws-data/pull/317
=> Carrenza rummanger a records aws

terraform/projects/infra-govuk-repo-mirror/README.md, terraform/projects/infra-govuk-repo-mirror/integration.govuk.backend, terraform/projects/infra-govuk-repo-mirror/main.tf, terraform/projects/infra-govuk-repo-mirror/production.govuk.backend, terraform/projects/infra-govuk-repo-mirror/staging.govuk.backend, terraform/projects/infra-govuk-repo-mirror/test.govuk.backend
This commit removes govuk-repo-mirror from all environements except the tools account, from where it now runs.
=> Remove govuk-repo-mirror from all environments

terraform/projects/infra-public-services/main.tf
Set the TTL for rummager search A record to 300.
=> fix ttl for rummager search

terraform/projects/fastly-datagovuk/README.md, terraform/projects/fastly-datagovuk/main.tf
This commit adds the `stackname` variable for the `fastly-datagovuk` project, since this variable is used in the project.
=> Add stackname variable for fastly-datagovuk

terraform/projects/fastly-datagovuk/main.tf
This was missed when we upgraded to the new CKAN.
=> Add /education-standards proxy for data.gov.uk

terraform/projects/fastly-datagovuk/main.tf
A request-type header assumes the `req` prefix to all variables. In addition, a `;` is automatically added at the end of the `source` field.
=> Fix data.gov.uk education standards backend

terraform/projects/app-data-science/main.tf
https://trello.com/c/52Lcfble/359-migrate-to-p2xlarge-aws-instance-to-produce-related-links-using-graphsage
This is part of the related links project.
=> Switch data science EC2 instance type to p2.xlarge

terraform/projects/app-elasticsearch5/README.md, terraform/projects/app-elasticsearch5/main.tf
AWS Managed Elasticsearch requires an even number of nodes when running over multiple availability zones.  This increases the node count from 3 to 4.
Trello card: https://trello.com/c/ut3wIgN6/31-set-up-new-managed-elasticsearch-cluster-in-aws
=> Increase Elasticsearch node count

terraform/projects/app-elasticsearch5/main.tf
The only advanced option we are setting is not supported.  We will look at an alternative way of implementing `action.destructive_requires_name`.  It is not essential for initially setting up the cluster..
Trello card: https://trello.com/c/ut3wIgN6/31-set-up-new-managed-elasticsearch-cluster-in-aws
=> Remove Elasticsearch advanced_options

terraform/projects/infra-security-groups/elasticsearch5.tf
Managed Elasticsearch provides access via HTTPS on port 443, not the Elasticsearch default of 9200.  This updates the ingress rules so calculators_frontend and search machines can access the search endpoint.
Trello card: https://trello.com/c/ut3wIgN6/31-set-up-new-managed-elasticsearch-cluster-in-aws
=> Update ingress rules for managed Elasticsearch cluster

terraform/projects/app-data-science/main.tf
This will allow SSH access to the individual machines. The security group will still restrict access to office IPs.
=> Give data science machines public IP addresses

terraform/projects/app-elasticsearch5/main.tf, terraform/projects/infra-security-groups/elasticsearch5.tf
This policy permits access to all clients within the VPC (without signing the requests), subject to the ingress filtering specified in the security group.
Trello card: https://trello.com/c/ut3wIgN6/31-set-up-new-managed-elasticsearch-cluster-in-aws
=> Add access policy for AWS Elasticsearch cluster

terraform/projects/app-cache/main.tf, terraform/projects/app-draft-frontend/main.tf
Spinning production instances in prep for migration of the frontends to
AWS.
1/ setting the instance type for the cache instances to m5.xlarge
2/ setting the instance type for the draft_frontend instances to t2.medium
The draft-frontend instances are being reduced in size according to the
source of truth in this document: https://docs.google.com/spreadsheets/u/1/d/1czAEGFndgh9sPVOMDyvrAPO6Tc8uBmkB4ArThcf6A-c/edit#gid=1041561724
=> Trello-2029: Spin prod instances

terraform/projects/app-elasticsearch5/README.md, terraform/projects/app-elasticsearch5/main.tf
These get spread across three availability zones, so we need a count that is divisible by three.
Trello card: https://trello.com/c/jxqmybdP/53-configure-our-cluster-for-three-availability-zones
=> Decrease Elasticsearch node count to 3

terraform/projects/app-elasticsearch5/main.tf
AWS offer three types of logs for the managed Elasticsearch service:
- Application error logs
- Slow query logs
- Slow index logs
This PR exports all three types to Cloudwatch, with a retention period of 90 days.  Further work will deal with the exporting of these to S3.
Trello card: https://trello.com/c/jc1LM6nM/58-set-up-export-of-error-logs-from-elasticsearch-to-cloudwatch
=> Publish the Elasticsearch logs to Cloudwatch

terraform/projects/app-data-science/main.tf
This PR upgrades the `data-science-2` EC2 instance type from `p3.2xlarge` to `p3.8xlarge`.
This instance is being used to evaulate the implementation of a GraphSAGE algorithm which will be used to generate related links for content pages across GOV.UK. To perform this evaluation, it is necessary to run the algorithm against a set of sample data.
Currently on the `p3.2xlarge` instance, it takes approximately 20 minutes to evaluate one page of the sample data (one content item) using the algorithm. By switching the instance type to `p3.8xlarge`, we roughly estimate that this time can be brought down to 5 minutes per page of the sample data.
By speeding up the evaluation process, we will be able to determine the suitability of the algorithm for the purpose of generating related links and …
=> Upgrade data-science-2 instance type p3.8xlarge

terraform/modules/aws/cloudwatch_log_exporter/main.tf
The Elasticsearch logs have slashes in their names, which are not permitted by the regex `"^[a-zA-Z0-9-_]+$"`.  This replaces them with a permitted character.  Putting it here so we don't encounter the same problem with any future log exports.
Trello card: https://trello.com/c/44CAPD5j/57-set-up-export-of-logs-from-cloudwatch-to-s3
=> Remove non-permitted slash characters from lambda permission name

terraform/modules/aws/cloudwatch_log_exporter/main.tf
AWS limits this to 64 characters, so take the basename only.
Trello card: https://trello.com/c/44CAPD5j/57-set-up-export-of-logs-from-cloudwatch-to-s3
=> Reduce length of Lambda function name

terraform/projects/app-mongo/main.tf
Staging & Integration mongo machines should be able to read production mongo s3 buckets so as to sync with production
1. attach the production read access policy to the mongo machines.
=> staging & integration mongo machines should be able to read production mongo s3 buckets

terraform/projects/infra-security-groups/ckan.tf
We need this to support the data sync from production to staging as it needs to run some post processing task on the ckan machine.
See https://github.com/alphagov/govuk-aws/pull/811 for more information.
[Trello Card](https://trello.com/c/RiOpZ1qs/762-get-ckan-database-up-and-running-on-staging)
=> Allow db-admin to SSH into the ckan machine

terraform/projects/app-elasticsearch5/README.md, terraform/projects/app-elasticsearch5/main.tf
This updates the architecture of the managed Elasticsearch cluster, based on the Google doc: https://docs.google.com/document/d/1rnXMNQVUWa4rNGH1L6H7dI3NPXD_Niuht9uZyAI_XjM/edit
No changes have been made to the sharding strategy.  Two methods of sharding will be implemented later and compared.
Trello card: https://trello.com/c/nLemuXWJ/62-update-es5-cluster-configuration-based-on-architecture-decision
=> Update the managed Elasticsearch cluster architecture

terraform/projects/app-backend/main.tf
We noticed on 2nd line that the backend machines in Carrenza are 8 CPU 32GB of ram whereas in AWS they are 4 CPU and 16GB. 
This PR rather simply changes the EC2 class to be 8 CPU and 32GB which leaves the hard work of how we actually change this.
The problem this seems to be causing in integration is that there isn't enough memory to run clamav.
When trying to start clamav this error occurs:
```
Feb 22 16:23:43 ip-10-1-5-128.eu-west-1.compute.internal clamd[19758]: daemonize() failed: Cannot allocate memory
```
=> Double backend capacity to match Carrenza

terraform/modules/aws/network/nat/README.md, terraform/modules/aws/network/nat/main.tf, terraform/projects/infra-networking/README.md, terraform/projects/infra-networking/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/cache.tf, terraform/projects/infra-security-groups/remote_state.tf
The monitoring box in each AWS environment should be able to contact the external ELB of the cache machines of that AWS environment because there is an Icinga check to verify the SSL certificate expiry date.
Since the monitoring box uses the NAT gateway to contact the external ELB of the cache machines, the NAT gateway public IPs must be authorized to communicate with the external ELB.
1. output the public IPs of the nat gateways from the infra-networking project.
2. use the outputted public IPs in Step 1 in the list of IPs which are authorized to contact the cache external ELB.
=> allow monitoring boxes to access the cache external ELB for certificate check

terraform/projects/app-draft-frontend/main.tf, terraform/projects/app-frontend/README.md, terraform/projects/app-frontend/main.tf
- These instances seem to run out of memory during deployment
- This is to determine whether we can use bumped instances as a
workaround
solo: @schmie
=> Bump the frontend and draft-frontend instance sizes

terraform/projects/infra-security-groups/ckan.tf
We previously allowed SSH access into the CKAN ELB however I think really we want access directly into the CKAN instance. The ELB sits in front and handles HTTP requests only.
[Trello Card](https://trello.com/c/RiOpZ1qs/762-get-ckan-database-up-and-running-on-staging)
=> Fix security group to point to CKAN rather than CKAN ELB

terraform/projects/infra-security-groups/draft-cache.tf
Context
We need access to draft-origin and subsequently draft-cache for training
sessions run on the integration environment. Access to
draft-origin.integration.publishing.service.gov.uk being restricted to the list
of fastly and office ips means that anyone on GovWiFi (for example) will be
unable to do their training. Access is further restricted by signon.
Decision
Modify the draft-cache security group to allow access to everyone. They
will still need a signon account.
=> Open integration draft-cache to the world

terraform/projects/app-publishing-api-db-admin/README.md, terraform/projects/app-publishing-api-db-admin/main.tf, terraform/projects/app-transition-db-admin/README.md, terraform/projects/app-transition-db-admin/main.tf, terraform/projects/app-warehouse-db-admin/README.md, terraform/projects/app-warehouse-db-admin/main.tf, terraform/userdata/90-data-science-base
Also reflow a comment so the lines are not so long.
Unless theres a need for fancier kinds of whitespace, it's probably
better just to stick to spaces, and maybe tabs.
=> Remove non-breaking spaces

terraform/projects/infra-s3-mirrors/README.md, terraform/projects/infra-s3-mirrors/integration.govuk.backend, terraform/projects/infra-s3-mirrors/main.tf, terraform/projects/infra-s3-mirrors/mirror-crawler-write-policy.tf, terraform/projects/infra-s3-mirrors/mirror-read-policy.tf, terraform/projects/infra-s3-mirrors/pingdom_probe_ips.sh, terraform/projects/infra-s3-mirrors/production.govuk.backend, terraform/projects/infra-s3-mirrors/staging.govuk.backend
Mirrors were created using the older terraform code base,
repo:`govuk-terraform-provisioning`. In order to modify the buckets we need to
have this under an active code base.
- Write code to provision the infrastructure (this commit)
- Import the existing resources to the new state file, example for integration
is written below.
To manually run terraform from `govuk-aws` root
`/tools/build-terraform-project.sh -c apply -p infra-s3-mirrors -d
../govuk-aws-data/data -e integration -s govuk`
```
terraform import aws_s3_bucket.govuk_mirror_access_logs
govuk-mirror-integration-access-logs
terraform import aws_s3_bucket.govuk_mirror govuk-mirror-integration
terraform import aws_iam_user.s3_mirror_writer_user s3_mirror_writer
terraform import aws_iam_policy.s3_mirror_writer_policy …
```
=> Add code for s3-mirrors

jenkins.sh
Now that the Jenkins job definition has been changed in govuk-puppet
to not wipe the workspace, this directory needs deleting so that it
can be cloned.
It's probably possible to do this more efficiently, but this is a
simple way of making it work again.
=> Fix the jenkins.sh script for a persistent workspace

terraform/projects/infra-security-groups/graphite.tf
After the cache machines have been migrated to AWS, the Grafana dashboard which still resides in Carrenza should have access to the Graphite service in AWS so that it can correctly display important metrics.
1. allow Carrenza environment subnet access to the Graphite load balancer in AWS.
=> allow carrenza dashboard to access the graphite service in AWS

terraform/projects/infra-security-groups/cache.tf
This makes it easier to set up load testing as we don't need to manually configure the IP addresses that Gatling uses (which can change frequently).
=> Allow Gatling to access port 443 on cache machines

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/outputs.tf, terraform/projects/infra-security-groups/search-api.tf, terraform/projects/infra-security-groups/search.tf
This PR removes the search-api internal service name, that should more properly be a CNAME pointing to the "search" hostname, as search-api lives on the app-search machines (just like rummager).
It also adds an ALB so that Carrenza IPs can talk to search-api over the public internet, which is needed for:
1. Traffic replay from rummager to search-api while we have both running in parallel
2. Direct communication from search-admin and whitehall when rummager is switched off
govuk-aws-data PR: https://github.com/alphagov/govuk-aws-data/pull/339
---
[Trello card](https://trello.com/c/YU9bS9jR/76-get-search-api-running-in-aws-staging)
=> Add ALB for search-api external access, use a CNAME for internal access

doc/guides/getting-started.md
The GOV.UK Developer Docs have the most recent guidance for deploying
Terraform. There were two ways of deploying Terraform code, but there
is now only one documented process.
=> Update "Deploying code" in the Getting Started guide

terraform/projects/app-router-backend/main.tf
During the AWS migration of router and draft-router, there is a need to allow AWS Staging to access the S3 bucket where the AWS production database of router and draft-router are backed up.
1. add the policy to read production buckets to router/draft-router S3 buckets.
=> allow staging to read the production router database

terraform/projects/infra-security-groups/graphite.tf
Reverts alphagov/govuk-aws#837 because second line will use the Grafana in AWS now rather than the Carrenza one.
=> Revert "allow carrenza dashboard to access the graphite service in AWS"

terraform/projects/app-elasticsearch5/README.md, terraform/projects/app-elasticsearch5/main.tf
We're going to use snapshots for the data sync, as the current
dump/export script we use doesn't support elasticsearch 5, and it's
always better to use built-in functionality if you can.
The cluster is configured to take an automatic snapshot every day, but
these snapshots are stored in a bucket we don't have access to.  So we
need to take manual snapshots, which are written to a custom location.
*However*, terraform doesn't support configuring manual snapshots.
This has to be done by hand.  This is what the
`manual_snapshot_domain_configuration_policy` is for: it will be added
to the list of policies administrators and powerusers have, and
someone will be able to configure the elasticsearch cluster using that
policy.
The details of this all are in the AWS documentation: …
=> Set up a bucket and policy for manual elasticsearch snapshots

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/calculators-frontend.tf, terraform/projects/infra-security-groups/outputs.tf
- For some reason the publisher requires to talk to the calendars
frontend app
- This load balancer will be locked down to the Carrenza CIDR and allow
publisher to access the app over the internet
- We have used this approach in the past for mapit and content-store
Requires: https://github.com/alphagov/govuk-aws-data/pull/347
solo: @schmie
=> Add Carrenza facing ALB for calendars app

terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/calculators-frontend.tf
- A security group for calendars has to be explicitly in place
- The autoscaling group target for the calendars has to be calculators
frontend
- I got both the wrong way around
solo: @schmie
=> More oversight in copy-paste

terraform/projects/app-elasticsearch5/README.md, terraform/projects/app-elasticsearch5/main.tf
Elasticsearch needs to have access to buckets across environments:
- read from the environment above (eg, pulling production data to
staging)
- write to the current environment (eg, backing up staging)
We decided to store the bucket ARNs in govuk-aws-data to simplify
this.  There's no risk in doing this, because we only use these
buckets for the data sync.  Giving (eg) staging write access to
production doesn't let ot touch production's atcual backups, only the
ones used for the data sync.
There will be a follow-up change to govuk-aws-data.
---
[Trello card](https://trello.com/c/QQHOpt56/75-update-data-sync-for-elasticsearch-5)
=> Parameterise elasticsearch by what manual snapshot buckets exist

terraform/projects/app-elasticsearch5/main.tf
Planned this branch on integration and staging with no problems so it should be fine.  It also has the advantage of only creating one policy per environment, rather than one policy per bucket per environment.
---
[Trello card](https://trello.com/c/QQHOpt56/75-update-data-sync-for-elasticsearch-5)
=> Fix policy for managed elasticsearch snapshot buckets

terraform/projects/infra-security-groups/calculators-frontend.tf
We need this security group rule to allow access through to the
calculators-frontend host from the calendar alb.
Co-authored-by: Sebastian Schmieschek <sebastian.schmieschek@digital.cabinet-office.gov.uk>
=> Adding require sg for calendar alb

terraform/projects/infra-database-backups-bucket/reader.tf
Through the ListBucket permission. Previously "s3:List*" was being
specified as an action, but this seems not to apply to resources that
specify files within a bucket, it must apply to the whole bucket.
This kinda makes sense, I was getting confused by the combination of
the resources and actions in the other policies.
This commit splits the actions across two statements, the first
statement applying to the bucket itself, and removes the wildcards
from the actions being specific about what's actually intended.
=> Fix the Content Data API DB Admin reader to allow ListObjects

terraform/projects/infra-govuk-repo-mirror/README.md, terraform/projects/infra-govuk-repo-mirror/main.tf
This commit adds the SSH key for Jenkins production to be used for repo mirroring and deploying from CodeCommit.
=> Add Jenkins production SSH key

terraform/projects/app-elasticsearch5/main.tf
The ARN was not being specified in full, so creating the policy failed
Trello card: https://trello.com/c/QQHOpt56/75-update-data-sync-for-elasticsearch-5
=> Fix resources list for ES5 manual snapshots S3 bucket policy

terraform/projects/infra-govuk-csp-forwarder/tools.govuk.backend
A lambda function and the S3 bucket it is provisioned from need to be in the same region.
=> Change infra-govuk-csp-forwarder region

terraform/policies/content_data_admin_s3_writer_policy.tpl
Fixed the JSON formatting for the IAM policy which prevented the IAM user from being created for Content Data to access S3.
=> Fix json in IAM policy for Content Data

terraform/projects/infra-govuk-csp-forwarder/README.md, terraform/projects/infra-govuk-csp-forwarder/main.tf, terraform/projects/infra-govuk-csp-forwarder/tools.govuk.backend
This PR does two things:
* Moves the creation of the `govuk-csp-forwarder` lambda function to eu-west-1 since this is the region the deployed lambda artefact exists in
* Adds an API gateway endpoint to allow HTTP POST requests to reach the lambda function
=> Create govuk-csp-forwarder lambda in eu-west-1 and add API Gateway

terraform/policies/content_data_admin_s3_writer_policy.tpl
Adding `GetBucketLocation` and `PutObjectAcl` permissions as needed to HEAD buckets and PUT object with public access.
=> Fix missing permissions in S3 policy

terraform/policies/content_data_admin_s3_writer_policy.tpl
This adds a missing GetObjectAcl permissions needed for Content Data Admin to fetch an object's public url.
=> Add missing S3 permissions for Content Data Admin

terraform/projects/infra-govuk-csp-forwarder/main.tf
This commit moves all govuk-csp-forwarder resources to eu-west-2, using the artefact replication bucket as a source to allow this.
=> Create govuk-csp-forwarder in eu-west-2

terraform/projects/infra-database-backups-bucket/writer.tf
I'm currently seeing the following error. I can't track down what
permissions are required for the CreateMultipartUpload operation, so
maybe it relates to this bit of the policy...
1:
(AccessDenied) when calling the CreateMultipartUpload operation
=> Fix the Content Data API database backups bucket prefix

terraform/projects/infra-database-backups-bucket/reader.tf
Add the missing `_production` suffix to the Content Data API database
name, and add an extra resource covering the
`content_performance_manager_production` database being used by the
Content Data API during the migration.
=> Improve the Content Data API database backups reader policy

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/frontend.tf, terraform/projects/infra-security-groups/outputs.tf
Following the migration of static on AWS:
Whitehall in carrenza need a way to talk to static on AWS
This new ALB needs to be locked down to the carrenza CIDR
=> Add Carrenza facing ALB for the static app

terraform/modules/aws/s3_bucket_lifecycle/README.md, terraform/modules/aws/s3_bucket_lifecycle/main.tf
Context
We have different environments (Integration, Staging and Production) with
different lifecycle requirements yet these are created with the same code. This
means that all lifecycle rules will be the same for any buckets created with
the same code. Lifecycle rules have to be defined inline and cannot be attached
to existing buckets.
Decision
Create a module to allow for basic expiration of objects, namely expiration of
current and noncurrent objects. This commmit creates a module that allows
enable/disable of a current object expiration rule and the enable/disable of a
noncurrent object expiration rule. It also allows an override of the default 5
days for both these rules.
=> Module to create s3 buckets with expiration lifecycle rules

terraform/projects/app-content-data-api-postgresql/main.tf
For the RDS instances.  These currently have 1000GB of space, but we
want to know if we're using more than half of that, so set the alarms
accordingly.
=> Increase the freestoragespace_threshold for the Content Data API

terraform/projects/infra-csw/README.md, terraform/projects/infra-csw/main.tf
The latest version of CSW will not need target account ID.
Related PRs:
- https://github.com/alphagov/csw-client-role/pull/14
- https://github.com/alphagov/govuk-aws-data/pull/358
=> Remove CSW target account ID

terraform/projects/infra-s3-mirrors/pingdom_probe_ips.sh
Context
The probe to determine pingdom ips doesn't filter out "NULL" entries.
Decision
Remove the invert-match ("-v") and add regex specifically for IPv4 addresses.
(regex ref: https://www.shellhacks.com/regex-find-ip-addresses-file-grep/)
=> Fix Pingdom probe sh script

terraform/projects/fastly-datagovuk/README.md, terraform/projects/fastly-datagovuk/main.tf
This allows us to set up a different staging configuration that points to the staging data.gov.uk PaaS instance.
[Trello Card](https://trello.com/c/MomTjKnV/910-ensure-only-whitelisted-ips-can-purge-dgu-cache)
=> Make data.gov.uk Fastly backend domain configurable

terraform/projects/fastly-datagovuk/datagovuk.vcl, terraform/projects/fastly-datagovuk/main.tf
This means that purge requests to data.gov.uk will be limited to the IPs listed in the VCL.
Tested this deploy to staging:
```
❯ curl -XPURGE https://staging.data.gov.uk/test -k
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<title>403 Forbidden</title>
</head>
<body>
<h1>Error 403 Forbidden</h1>
<p>Forbidden</p>
<h3>Guru Mediation:</h3>
<p>Details: cache-ams21026-AMS 1554123729 1861220372</p>
<hr>
<p>Varnish cache server</p>
</body>
</html>
❯ ssh backend-1.production
Last login: Mon Apr  1 13:01:56 2019 from jumpbox-1.management.publishing.service.gov.uk
thomasleese@production-backend-1:~$ curl -XPURGE https://staging.data.gov.uk/test -k
{"status": "ok", "id": …
```
=> Add custom data.gov.uk VCL to limit purge requests

terraform/projects/infra-s3-mirrors/main.tf, terraform/projects/infra-s3-mirrors/mirror-crawler-write-policy.tf, terraform/projects/infra-s3-mirrors/mirror-read-policy.tf
Context
We have a module that will improve the consistency of lifecycle rules across s3
buckets. The infra-s3-mirrors project is one of several that would benefit.
Decision
Use the module and it's defaults to ensure versioned objects are deleted for
this project. Do this while ensuring data isn't deleted and that key
infrastructure is not destroyed. This requires both code and implementation
steps.
The following approach was used to implement this across aws envs:
1. Run a plan with `./tools/build-terraform-project.sh` for the project.
2. Confirm what would be destroyed and confirm other changes.
3. Change directory to the project to run `terraform state` and rename the
entries to keep in the state file. This will also create a local backup of the
state file.  e.g. `terraform state mv …
=> Start using s3 module for infra-s3-mirrors project

terraform/modules/aws/node_group/README.md, terraform/modules/aws/node_group/main.tf, terraform/projects/app-search/main.tf
The healthcheck only checks nginx is running, not that the app is running.  We've seen this cause occasional problems elsewhere, so just set it to a large value for the search machines, given that we're planning to grow the ASG to 3 nodes.
=> Give search machines a 600s warmup period

terraform/projects/app-search/main.tf
It took a little over 10 minutes on staging for search-api to be
deployed to the new machine, so the 600s period is not enough.
=> Bump search grace period to 1200s

tools/govukcli
Sometimes it's useful to list all the machines of a particular class,
for example when you are debugging something strange that's only
affecting a particular machine.
Add a `node-list <machine>` to `ssh` to support this.
For example, running `govukcli ssh node-list whitehall_backend` should
list all the whitehall backend machines in the context of the environment.
=> Add option to list all machines of a type

terraform/projects/app-elasticsearch5/main.tf
Elasticsearch doesn't just look at the files in the bucket to know
what snapshots there are, it maintains a metadata file.  Expiring old
files results in this metadata file getting out of sync, which results
in a 500 error when trying to do anything other than take a new
snapshot.
There doesn't seem to be a way to regenerate the metadata based on the
real data, so automatic expiration has to go.  Perhaps we could have a
daily task on the search machines which deletes the oldest snapshot or
something.
To fix the bad state I'll need to unregister the buckets from elasticsearch, delete their contents, and re-register them.
---
[Trello card](https://trello.com/c/rsePSAB9/90-fix-the-flakey-data-sync)
=> Remove expiration rule from elasticsearch manual snapshot bucket

terraform/projects/app-elasticsearch5/README.md, terraform/projects/app-elasticsearch5/main.tf
Add an additional data node in each availability zone.
This reduces the query queue length and CPU utilisation.
Trello card: https://trello.com/c/Ywbe0luG/117-spike-es-data-instances-have-enough-resource
=> Increase the Elasticsearch data nodes from 3 to 6

terraform/projects/fastly-datagovuk/main.tf
This was previously served through the old data.gov.uk frontend but has been lost since we migrated to the new CKAN.
[Trello Card](https://trello.com/c/T1aZMkTy/933-make-contracts-archive-accessible-on-former-url)
=> Add a proxy for contracts finder archive on data.gov.uk

terraform/projects/fastly-datagovuk/main.tf
Fastly uses a cache key of 'req.url, req.http.host' when deciding which key to store a cache under. So we should set the host when proxying to services other than the main data.gov.uk service so that they don't get cached over data.gov.uk. This happens because we rewrite the URLs to remove the prefix part of the URL for the proxy service. Setting the host doesn't change the host of the backend origin service we're connecting to, it just changes the value of the header sent to the origin service.
[Trello Card](https://trello.com/c/T1aZMkTy/933-make-contracts-archive-accessible-on-former-url)
=> Set the host for proxied services

terraform/projects/app-calculators-frontend/README.md, terraform/projects/app-calculators-frontend/main.tf
We will be redirecting extra traffic to finder-frontend from whitehall finders over the next few days/weeks.  
Elasticsearch / search-api should behave similarly to before, as they were both in the whitehall finder dependency tree, so it should just be finder-frontend that needs to increase spec.
Note that the current asg size in live is `4` not `3` as this PR would suggest.  This is because of last week's remedial work.
https://trello.com/c/NMLcme88/110-add-additional-calculators-search-api-boxes-to-create-additional-capacity
=> Add another calculators_frontend machine

terraform/projects/infra-security-groups/remote_state.tf
The new Training environment is provisioned in a different region. We need to use
the `aws_region` variable to configure the networking remote_state file, or Terraform
fails.
=> Use aws_region variable in remote_state

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/calculators-frontend.tf, terraform/projects/infra-security-groups/content-store.tf, terraform/projects/infra-security-groups/frontend.tf, terraform/projects/infra-security-groups/mapit.tf, terraform/projects/infra-security-groups/variables.tf
We have made entering the Carrenza IPs optional.
These can now be blank if they are not needed in your
particular environment
=> Updated infra-security-group terraform files

doc/guides/certificate-validation.md, doc/guides/environment-provisioning.md, terraform/projects/infra-certificates/README.md, terraform/projects/infra-certificates/main.tf, terraform/projects/infra-certificates/training.govuk.backend, terraform/projects/infra-root-dns-zones/README.md, terraform/projects/infra-root-dns-zones/main.tf
The environment certificates have so far been created manually in AWS and
validated with Email: https://github.com/alphagov/govuk-aws/blob/master/doc/guides/certificate-validation.md
Now we want to manage these certificates with Terraform and use DNS validation (originally this
was not an option).
We need to create a public Route53 zone for the private domain to be able to validate the
certificate. The certificates will be managed in a new project called `infra-certificates` that
requires `infra-root-dns-zones` outputs.
`infra-certificates` contains outputs resources that ensure the certificate has been successfully validated:
https://www.terraform.io/docs/providers/aws/r/acm_certificate_validation.html
These outputs could be used by other projects to get the certificate ARN instead of …
=> Manage environment certificates with Terraform

terraform/projects/app-elasticsearch5/README.md, terraform/projects/app-elasticsearch5/main.tf
- We were still seeing performance issues with the cluster
- AWS recommends to keep the cluster size under 10
solo: @schmie
=> Bump elasticsearch data node size to r4.xlarge

terraform/projects/infra-fastly-logs/main.tf
We were still seeing errors of "HIVE_CURSOR_ERROR: Row is not a valid
JSON Object - JSONException: Unterminated string at 227 [character 228
line 1]" when querying athena. Some tracing indicates that this occurs
when a log entry terminates early, therfore outputting invalid JSON.
In OpenX JSON SerDe there is an option to ignore malformed JSON [1],
this commit applies this to our tables so these erroneous results can be
ignored.
[1]: https://docs.aws.amazon.com/athena/latest/ug/json.html#openxjson
Runs of [plan](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1137/) and [apply](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1138/) to test environment. Note the fails for apply are due to s3 user already existing, …
=> Ignore malformed JSON on fastly logs tables

tools/govukcli
Added training item to CONTEXTS array, gdscli aws
command can now be used with the new training environment,
ssh training option will need to be updated after we have set up
the jumpbox.
=> Added training environment option

terraform/projects/app-puppetmaster/README.md, terraform/projects/app-puppetmaster/main.tf
We want to start provisioning the Training environment app projects
without the `blue` or stack-based DNS/LB infrastructure, but the code
has to be able to support the current design in integration/staging/production
and the new one at the same time.
Already, the training doesn't have a stack Route53 zone (`infra-stack-dns-zones`
hasn't been applied), so the remote_state data resource `infra_stack_dns_zones`
can't be used in the code.
This new solution uses the `aws_route53_zone` data resource instead of the remote
state files to make it easier to understand what the code needs to implement. The
variables that determine the domain/zone name are required, which
forces the user to add the correct configuration in the data repository.
=> app-puppetmaster add support for non-blued infrastructure

tools/govuk-puppetmaster-integration-bootstrap.sh, tools/govuk-puppetmaster-production-bootstrap.sh, tools/govuk-puppetmaster-staging-bootstrap.sh, tools/govuk-puppetmaster-training-bootstrap.sh
In the Puppetmaster bootstrap we need to override the `apps/production_credentials.yaml`
datasource with the equivalent environment file. Otherwise, Puppet tries to decrypt
the production file with the wrong key.
This process is already implemented in the Puppet deployments:
https://github.com/alphagov/govuk-secrets/blob/master/puppet_aws/config/deploy.rb#L45-L47
=> Configure apps datasource in Puppetmaster bootstrap script

doc/guides/getting-started.md
Tfenv is the recommended way to manage Terraform versions locally, there is a
terraform-version file that has been maintained in this repo for quite a long
time now. Chtf was compatible only with Brew.
=> Update provisioning documentation

jenkins.sh
This will be handy for testing, in exactly the same way that being able to plan or apply a branch of govuk-aws (which is functionality we already have) is.
=> Allow jenkins to deploy a branch of govuk-aws-data

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
The SOPS KMS key has been created manually in the past. We want to add this resource
to `infra-security` to remove manual steps from an environment bootstrap.
We'll need to import the KMS resources into the existing environments
=> Manage SOPS KMS key

terraform/projects/app-elasticsearch5/main.tf
Terraform doesn't seem to pick up code changes if the hash isn't explicitly given.
=> Add explicit source code hash for ES lambda

terraform/projects/infra-artefact-bucket/README.md, terraform/projects/infra-artefact-bucket/main.tf, terraform/projects/infra-artefact-bucket/training.govuk.backend
We changed the bucket policy from inline to a terraform data
object, this way it's easier to implement empty variables.
We also changed the aws_s3_access_account variable to
a list to make it more flexible, because the integration environment
needs access from more than a single aws account.
We also removed a variable that was no longer in use "deployer_role".
Finally we added the terraform backend file.
Co-authored-by: @afda16
=> Added infra-artefacts-bucket project to training environment

terraform/projects/infra-artefact-bucket/README.md, terraform/projects/infra-artefact-bucket/main.tf
The SNS suscription is region specific. We have added a new
provider block to the main.tf file to solve a permissions
error.
=> Add fix for training infra-artefact-bucket SNS subscription

terraform/projects/app-monitoring/main.tf, terraform/projects/infra-security-groups/monitoring.tf
For the CDN logs migration to AWS, we need to add the listeners to the ELB of the monitoring box so that fastly can reach these boxes.
1. add listeners for fastly to monitoring elb
=> add the fastly listeners to monitoring box elb

terraform/modules/aws/cloudwatch_log_exporter/main.tf
Deleted value in aws_region current block. According to the
documentation "aws_region" now defaults to the current provider
region:
https://www.terraform.io/docs/providers/aws/d/region.html
=> Fix terraform cloudwatch_log_exporter module deprecation warning

terraform/projects/app-puppetmaster/main.tf
To avoid the internal loadbalancer being destroyed and recreated
we have swapped the resource's position in the "instance_elb_ids" list. Please
see below for an in-depth explanation on why this was necessary.
When setting up a new environment, we run the app-puppet master project
twice. The first time we run the project the "enable_bootstrap" variable
needs to be set to true. This will create a bootstrap ELB that will allow
us to access the puppetmaster instance and check that everything is
configured correctly. An internal ELB will also be created by default.
When we are happy that the puppet master instance is set up
and working, we then run the app-puppetmaster terraform project
again, this time with the "enable_bootstrap" variable set to false. This will
remove the bootstrap ELB as it …
=> Fix to app-puppet master module ELB list

doc/guides/environment-provisioning.md
These apps were never migrated to AWS, so have been deleted
from the list:
app-email-alert-api-db-admin
app-publishing-api-db-admin
The app-content-data-api-db-admin was missing, so we haved added
it to the list.
=> Update Environment Provisioning Guide

terraform/projects/app-deploy/README.md, terraform/projects/app-deploy/main.tf, terraform/projects/app-deploy/training.govuk.backend
Update the app-deploy project to support non-blued infrastructure in
the new Training environment:
- We need to retrieve Route53 zones from variables instead of remote state files
- Make the creation of the external ELB optional. By default the external ELB is
created, this is the expected behaviour in the existing environments. In Training,
we can choose not to create this ELB.
=> Update app-deploy for Training and make external ELB optional

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
We need a new variable to select the value of the app stackname on
each environment. Defaults to previous static value, there should be
no changes in the existing environments.
=> Add Training to infra-public-services

terraform/projects/app-apt/README.md, terraform/projects/app-apt/main.tf, terraform/projects/app-apt/training.govuk.backend
Add backend to build app-apt in the Training environment.
This project doesn't have a second public ALB in `infra-public-services`, because
the apt service in Production is common to all the infrastructure and it hasn't
been migrated to AWS yet.
=> Update app-apt for Training environment

terraform/projects/app-db-admin/README.md, terraform/projects/app-db-admin/main.tf, terraform/projects/app-db-admin/training.govuk.backend
Add backend to build app-apt in the Training environment.
does not use the stack domain). app-db-admin doesn't have external ELB/DNS record.
=> Update app-db-admin for Training environment

terraform/projects/app-monitoring/README.md, terraform/projects/app-monitoring/main.tf, terraform/projects/app-monitoring/training.govuk.backend
Add backend to build app-monitoring in the Training environment.
does not use the stack domain). app-monitoring doesn't have external ELB/DNS record
=> Update app-monitoring for Training environment

terraform/projects/app-transition-db-admin/README.md, terraform/projects/app-transition-db-admin/main.tf, terraform/projects/app-transition-db-admin/training.govuk.backend
Add backend to build app-transition-db-admin in the Training environment.
does not use the stack domain). app-transition-db-admin doesn't have external ELB/DNS record
=> Update app-transition-db-admin for Training environment

terraform/projects/app-monitoring/main.tf
The size of the root partition of the monitoring box should be increased to take into account the logs.
1. increase the root partition size from 20gb to 40gb
=> increase the size of the monitoring box

doc/guides/environment-provisioning.md
Remove reference to app-warehouse-db-admin as it is no longer used.
Please see this pull request for more information:
https://github.com/alphagov/govuk-aws/pull/929
=> Update Environment Provisioning Doc

terraform/projects/app-content-data-api-db-admin/main.tf, terraform/projects/app-content-data-api-db-admin/training.govuk.backend
Add terraform backend file for training environment
app-content-data-api-db-admin.
Update the database backups buckets to use the current aws region
automatically.
=> Update app-content-data-api-db-admin for training environment

terraform/projects/app-content-data-api-postgresql/main.tf
Terraform/AWS doesn't like this:
Error: aws_db_parameter_group.content_data_api: only lowercase
alphanumeric characters and hyphens allowed in parameter group
"name_prefix"
=> Remove disallowed . from the aws_db_parameter_group name_prefix

terraform/projects/app-content-data-api-postgresql/main.tf
For the Content Data API parameter group. It's listed as "Apply_Type"
static on the AWS docs page, so I'm guessing this is causing issues
when attempting to apply this change.
=> Set apply_method = "pending-reboot" for autovacuum_max_workers

terraform/projects/app-search/main.tf
- We have been seeing search-api instances run out of CPU credits. At
the moment they are manually set to be "unlimited".
- Using c5 removes CPU credits. As we seem to be using burst mode 30-40
percent of the time, this change should not increase cost.
solo: @schmie
=> Bump the search-api instance size from t2 to c5

terraform/policies/s3_aws_secondary_logging_write_policy.tpl, terraform/policies/s3_govuk_mirror_replication_policy.tpl, terraform/policies/s3_govuk_mirror_replication_role.tpl, terraform/projects/app-mirrorer/README.md, terraform/projects/app-mirrorer/main.tf, terraform/projects/infra-mirror-bucket/README.md, terraform/projects/infra-mirror-bucket/integration.govuk.backend, terraform/projects/infra-mirror-bucket/main.tf, terraform/projects/infra-mirror-bucket/mirror-crawler-write-policy.tf, terraform/projects/infra-mirror-bucket/mirror-read-policy.tf, terraform/projects/infra-mirror-bucket/production.govuk.backend, terraform/projects/infra-mirror-bucket/staging.govuk.backend, terraform/projects/infra-monitoring/README.md, terraform/projects/infra-monitoring/secondary.tf
New mirror project of gov.uk where the mirror buckets are in AWS. 
1. the main mirror s3 bucket should be in London and the replica in Ireland.
2. s3 buckets should be browsable from the office IPs as well as fastly and
pingdom
3. infra-monitoring should have a bucket in London to store the logs of
s3 mirror bucket located in london
4. the bucket write policy should be attached to the mirrorer ec2 instance
role
5. the retention period for non-current version of whole bucket is set to
5 days and the www.gov.uk/government/uploads should be set to 8 days
=> Infra mirror setup

terraform/projects/app-mongo/README.md, terraform/projects/app-mongo/main.tf, terraform/projects/app-mongo/training.govuk.backend
Add backend to build app-mongo in the Training environment.
=> Update app-mongo for Training

terraform/projects/app-backend-redis/README.md, terraform/projects/app-backend-redis/main.tf, terraform/projects/app-backend-redis/training.govuk.backend
Add new terraform backend file for app-backend-redis
=> Update app-backend-redis for training environment

terraform/projects/app-rabbitmq/README.md, terraform/projects/app-rabbitmq/main.tf, terraform/projects/app-rabbitmq/training.govuk.backend
Add backend to build app-rabbitmq in the Training environment.
=> Update app-rabbitmq for Training environment

terraform/projects/infra-datagovuk-organogram-bucket/README.md, terraform/projects/infra-datagovuk-organogram-bucket/main.tf
We currently have an issue where organograms are not showing for
data links. Adding CORS rules to allow data.gov.uk fixes this.
Paired with @AlanGabbianelli 
Trello card: https://trello.com/c/wh8pUMOm/982-fix-display-of-organogram-visualisations-on-datagovuk
=> Add CORS rules for datagovuk-organogram S3 bucket

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
There are too many people in the govuk-administrators role, some AWS
limit is being hit.
Therefore, create a new govuk-internal-administrators role for
administrators from within the GOV.UK Publishing program.
I was going to create a govuk-external-administrators role, and remove
people external to GOV.UK from the existing govuk-administrators role,
but this would affect far more people (who would have to change their
configuration files), so just pull out the internal people instead.
=> Add a govuk-internal-administrators role

doc/guides/redeploying-applications-on-rebuild.md, tools/migration-hosts.sh
The Content Performance Manager has been renamed to the Content Data
API.
Also add the Content Data Admin in to these lists, as that seems
sensible.
=> Update references to the Content Data * apps

terraform/policies/s3_govuk_mirror_read_policy.tpl, terraform/projects/infra-google-mirror-bucket/README.md, terraform/projects/infra-google-mirror-bucket/main.tf, terraform/projects/infra-google-mirror-bucket/staging.govuk.backend, terraform/projects/infra-google-monitoring/README.md, terraform/projects/infra-google-monitoring/main.tf, terraform/projects/infra-google-monitoring/staging.govuk.backend, terraform/projects/infra-mirror-bucket/main.tf
As part of the govuk mirror redesign project, there was a decision to have a 3rd bucket in another provider GCP as a second provider backup to AWS in case that AWS goes down.
1. create terraform code to create a multi-regional EU Google/GCS mirror bucket that
will sync with its master govuk-{environment}-mirror bucket in AWS S3.
2. Since the GCS mirror bucket needs a logging bucket where it can store its log,
a GCS monitoring bucket must be created too
3. configure the google transfer tool to sync on a daily basis
the GCS bucket with its AWS S3 bucket source.
4. create a AWS restricted user to give to google transfer tool in order to access the AWS S3 bucket to be sync from.
The data counterpart for this PR is in: https://github.com/alphagov/govuk-aws-data/pull/432
=> terraform code for google mirror and monitoring bucket

terraform/modules/aws/iam/role_user/main.tf
As this informs Terraform there's a dependency between the two
resources, so it'll create the role prior to attempting to attach the
policy.
=> Use the iam_role name attribute when defining the policy attachment

doc/guides/deploying-google-terraform.md, doc/guides/deploying-terraform.md
There are now some terraform projects which deploy to the
Google Cloud Platform (GCP) rather than AWS. Hence, we include
some documentation and guidance about deploying such
projects.
1. include GCP deployment documentation
=> Created some documentation for Google Cloud Platform deployment

terraform/projects/app-router-backend/README.md, terraform/projects/app-router-backend/main.tf, terraform/projects/app-router-backend/training.govuk.backend
Add backend to build app-router-backend in the Training environment.
=> Update app-router-backend for Training

terraform/projects/app-transition-postgresql/README.md, terraform/projects/app-transition-postgresql/main.tf, terraform/projects/app-transition-postgresql/training.govuk.backend
Add backend to build app-transition-postgresql in the Training environment.
=> Update app-transition-postgresql for Training

terraform/projects/app-elasticsearch5/README.md, terraform/projects/app-elasticsearch5/main.tf, terraform/projects/app-elasticsearch5/training.govuk.backend
Add backend to build app-elasticsearch5 in the Training environment.
Training app-elasticsearch5 runs with fewer instances and t2.smalls to save
on costs.
=> Update app-elasticsearch5 for Training environment

tools/govukcli
I broke it when adding in the --context argument.
=> Fix govukcli get-context

terraform/projects/app-db-admin/main.tf
Previously this policy disallowed staging and integration to read from
production backup buckets and instead only their own environments, for
example integration could read from integration and staging
could read from staging.
However this does not work where backups are configured to read from
production, which is the case of the only database using this:
content_data_admin. Therefore this follows the same precedence of
app-content-data-api-db-admin [1] of allowing all environments to read
from production and all to write to their own environment.
[1]: https://github.com/alphagov/govuk-aws/blob/cb4d427c8ece83f69ae0a7cf8abf8c635e8e3519/terraform/projects/app-content-data-api-db-admin/main.tf
=> Switch db-admin to read from only production S3 buckets

terraform/projects/infra-security/main.tf
The govuk-internal-administrators role is intended to be the same as
the govuk-administrators role, except from the name. Ana pointed out
that the Role ARN was missing here.
=> Update the kms_sops_policy for the internal_admin role

terraform/modules/aws/lb_listener_rules/README.md, terraform/modules/aws/lb_listener_rules/main.tf, terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
Update the original `lb_listener_rules` module, that hasn't been used so far,
to support a more specific case, where we want to add a target group and listener
rule for that target based on host headers. Each target group has its own health
check, so we can ensure traffic is only routing when the application is up and
healthy.
We are testing this module with the backend LB. We can choose when to use the
application healthchecks and target groups with the `enable_lb_app_healthchecks`
variable. By default the LBs continue using the default target group. When
we set `enable_lb_app_healthchecks` to true, we are creating the LB forward rules
from the service cnames variable.
This expression:
```
rules_host = ["${compact(split(",", var.enable_lb_app_healthchecks ? join(",", …
```
=> Add support for ALB routing with specific application health checks - Option2

terraform/modules/aws/lb_listener_rules/README.md, terraform/modules/aws/lb_listener_rules/main.tf
Updates 5a79836
In Puppet we already configured the application health check path as
`/_healthcheck_` instead of `/_healthcheck-`.
This is the first time we are using this module, it's ok to update
here.
=> Update path of LB listener healthcheck module

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
The corresponding resources have now been removed, as the Content
Performance Manager has not been migrated over to AWS, under the new
Content Data API name.
=> Remove warehouse related entries from infra-public-services
