alphagov/govuk-aws

doc/architecture/decisions/0010-terraform-directory-structure.md
doc/architecture/decisions/0015-dns-infrastructure.md
doc/architecture/decisions/0017-terraform-data-structure.md

This fixes the number of ADRs and updates their titles/links.
Closes #94

Fix ADR numbering & links

---

terraform/projects/app-monitoring/main.tf

Remove white line to pass format check

Remove white line

---

terraform/projects/app-api-redis/main.tf

- Add aws_migration variable and tag

Refactor app-api-redis

---

terraform/projects/app-backend-redis/main.tf

- Add aws_migration variable and tag

Refactor app-backend-redis

---

terraform/projects/app-logs-redis/main.tf

- Add aws_migration variable and tag

Refactor app-logs-redis

---

terraform/projects/infra-security-groups/outputs.tf

- Do let me know if there are any other files like this that could do with alphabetizing.

Alphabetize terraform/projects/infra-security-groups/outputs.tf

---

tools/build-terraform-project.sh
tools/update-puppet.sh

This adds getopts to the terraform build tool and a simple script for updating the puppet code on the puppetmaster (for debugging)

More tools

---

terraform/projects/app-deploy/additional_policy.json
terraform/projects/app-deploy/main.tf
terraform/projects/infra-security-groups/management.tf

Jenkins needs to be able to access all machines to be able to deploy things.

Allow SSH from Deploy

---

doc/architecture/step-by-step.md
doc/guides/environment-provisioning.md
tools/aws-push-puppet.sh

Also update the script that does the initial push to be in line with:
https://github.com/alphagov/govuk-secrets/pull/2

Update references to depoyment repo

---

terraform/projects/app-mapit/main.tf

The plan didn't pick this up, but when it came to create it errored.

Clashing keys caused an error

---

Jenkinsfile
terraform/projects/app-apt/main.tf
terraform/projects/app-mysql-primary/main.tf
terraform/projects/infra-security-groups/mysql-primary.tf

Adding these tests ensure our code is formatted correctly and has correct syntax.
We need to specify the node to ensure we get the correct version of Terraform.
Depends on https://github.com/alphagov/govuk-puppet/pull/6155

Add terraform tests to CI

---

doc/architecture/step-by-step.md
doc/guides/environment-provisioning.md
tools/aws-copy-puppet-setup.sh
tools/aws-push-puppet.sh

Changes to initial puppet deploy

---

terraform/projects/app-puppetmaster/main.tf

We are seening OOM issues and high load so match the specs to our current
puppetmaster hosts

Upgrade the puppetmaster specs

---

terraform/projects/infra-security-groups/api-postgres.tf
terraform/projects/infra-security-groups/mysql-primary.tf

We need to allow DB admin to the RDS instances to manage the databases.

Allow DB admin to RDS

---

terraform/userdata/00-base

Update resolvconf base configuration to always append our internal
search domain

Add internal search domain to resolvconf

---

terraform/projects/app-monitoring/main.tf
terraform/projects/infra-security-groups/monitoring.tf
terraform/projects/infra-security-groups/outputs.tf

Add internal ELB to access the ncsa service. Add internal DNS service record.
Update security groups to add access to internal ELB

Monitoring add internal ELB

---

terraform/projects/app-backend-lb/main.tf

only alphanumeric characters and hyphens allowed in "name":

---

terraform/projects/app-performance-backend/main.tf
terraform/projects/app-publishing-api/main.tf
terraform/projects/app-whitehall-backend/main.tf

- performance-backend
- whitehall-backend
- publishing-api

Update ELBs and DNS records to be internal

---

terraform/projects/app-backend-lb/main.tf

Add missing ttl field to DNS record

---

terraform/projects/app-apt/main.tf

Apt record is public, Gemstash record is private

Update Apt DNS config

---

terraform/projects/infra-security-groups/exception-handler.tf

Port 3029 is for internal to the host only traffic

Use port 443 for incoming traffic

---

terraform/projects/app-api-mongo/main.tf
terraform/projects/app-api/main.tf
terraform/projects/app-backend/main.tf
terraform/projects/app-bouncer/main.tf
terraform/projects/app-content-store/main.tf
terraform/projects/app-draft-content-store/main.tf
terraform/projects/app-elasticsearch/main.tf
terraform/projects/app-logs-elasticsearch/main.tf
terraform/projects/app-mapit/main.tf
terraform/projects/app-mongo/main.tf
terraform/projects/app-publishing-api/main.tf
terraform/projects/app-whitehall-backend/main.tf
terraform/projects/app-whitehall-frontend/main.tf

Now we're starting to deploy apps we need more resources on the instances.

Scale instance types

---

doc/architecture/step-by-step.md
doc/guides/environment-provisioning.md
tools/build-terraform-project.sh

* Add help about using environment variables to build tool. 
* Add the ability to pass arguments to Terraform.

Improve build tool

---

terraform/projects/app-postgresql/main.tf

It should use the address rather than the endpoint.

Update DNS record for PostgreSQL primary

---

terraform/projects/app-deploy/main.tf
terraform/projects/app-graphite/main.tf
terraform/projects/app-monitoring/main.tf
terraform/projects/infra-security-groups/deploy.tf
terraform/projects/infra-security-groups/graphite.tf
terraform/projects/infra-security-groups/monitoring.tf

This adds the certs and updates the security rules for:
- Monitoring
- Jenkins Deploy
- Graphite

Add certs for services

---

terraform/projects/app-cache/main.tf
terraform/projects/app-calculators-frontend/main.tf
terraform/projects/app-draft-cache/main.tf
terraform/projects/app-draft-content-store/main.tf
terraform/projects/app-draft-frontend/main.tf
terraform/projects/app-performance-backend/main.tf
terraform/projects/app-performance-frontend/main.tf
terraform/projects/app-whitehall-backend/main.tf
terraform/projects/app-whitehall-frontend/main.tf
terraform/projects/infra-security-groups/cache.tf
terraform/projects/infra-security-groups/calculators-frontend.tf
terraform/projects/infra-security-groups/draft-cache.tf
terraform/projects/infra-security-groups/draft-content-store.tf
terraform/projects/infra-security-groups/draft-frontend.tf
terraform/projects/infra-security-groups/performance-backend.tf
terraform/projects/infra-security-groups/performance-frontend.tf
terraform/projects/infra-security-groups/whitehall-backend.tf
terraform/projects/infra-security-groups/whitehall-frontend.tf

- We're moving from using local certificates to using Amazon Certificate
Manager.

Add certificates in front of more machines' ELBs

---

terraform/projects/infra-security-groups/router-backend.tf

Also remove some notes that do not belong

Allow draft_cache to router_backend

---

terraform/projects/app-logs-cdn/integration.blue.backend
terraform/projects/app-logs-cdn/main.tf

This requires https://github.com/alphagov/govuk-aws-data/pull/6

Add cdn logs backend

---

terraform/projects/app-logs-elasticsearch/main.tf

Now they're receiving lots of logs they need some resources.

Upgrade logs-elasticsearch

---

terraform/projects/app-frontend-lb/main.tf
terraform/projects/app-search/main.tf
terraform/projects/app-whitehall-backend/main.tf
terraform/projects/app-whitehall-frontend/main.tf
terraform/projects/infra-security-groups/search.tf

A few updates in my quest to get frontend apps working. See commits for detail.

Frontend updates

---

terraform/projects/infra-security-groups/cache.tf
terraform/projects/infra-security-groups/draft-cache.tf

Router API needs to be able to talk to the router to reload routes.

Allow router-api to speak to router

---

doc/architecture/decisions/0025-use-elasticache-for-redis.md

https://trello.com/c/VNID5ncy/676-adr-for-using-elasticache

Add ADR for elasticache

---

terraform/projects/app-cache/main.tf
terraform/projects/app-content-store/main.tf
terraform/projects/app-exception-handler/main.tf
terraform/projects/app-frontend-lb/main.tf
terraform/projects/infra-security-groups/cache.tf
terraform/projects/infra-security-groups/frontend.tf

This removes the frontend-lb tier from AWS. Please see commits for detail.
https://trello.com/c/O7RiQxH2/714-remove-aws-frontend-lb-machines

Update DNS for publicapi

---

doc/guides/redeploying-applications-on-rebuild.md

This requires https://github.com/alphagov/govuk-puppet/pull/6441 to work.

Doc to redeploy apps on rebuild

---

terraform/projects/app-whitehall-backend/main.tf
terraform/projects/infra-security-groups/publishing-api.tf

Set correct resource names to avoid conflicts

Remove lbs bug fixes

---

terraform/modules/aws/node_group/main.tf

This will bring the default inline with carrenza

Increase default disk size to 20GB

---

terraform/projects/app-draft-content-store/main.tf

- Fix ELB name length (max 32 characters)
- Fix service record resolution

draft-content-store various fixes

---

terraform/projects/app-draft-frontend/main.tf

Add service records to draft-frontend. The applications env.d service domain will
need to be updated in Plek.
Use internal certificate.

Add draft-frontend service records

---

doc/guides/redeploying-applications-on-rebuild.md

- Something was wrong with the spacing, maybe? Serves me right for not previewing this, I suppose.

Fix the Markdown for the "Draft Frontend" heading

---

terraform/projects/app-apt/main.tf
terraform/projects/infra-security-groups/apt.tf

Update the ELB configuration with internal and external certificates
and instance port/protocols

Apt update ELB config and add certs

---

terraform/projects/app-deploy/additional_policy.json
terraform/projects/app-deploy/main.tf

Add external disk to store Jenkins data.

Add EBS to deploy

---

terraform/modules/aws/node_group/main.tf

Output the autoscaling group name variable so we can generate
autoscaling alerts.

Add autoscaling_group_name to node_group outputs

---

terraform/modules/aws/rds_instance/main.tf
terraform/projects/app-postgresql/main.tf

https://trello.com/c/F6UQeeiN/777-design-rds-replicas-and-backups
Please see detail in commits.
This updates the module with some sane defaults, and assigns a replica for app-postgresql.

Update RDS module and add replica

---

terraform/modules/aws/alarms/natgateway/README.md
terraform/modules/aws/alarms/natgateway/main.tf

Add module to monitor NAT Gateway instances.

Add AWS module larms NAT Gateway

---

terraform/projects/app-apt/main.tf
terraform/projects/app-backend/main.tf
terraform/projects/app-bouncer/main.tf
terraform/projects/app-cache/main.tf
terraform/projects/app-calculators-frontend/main.tf
terraform/projects/app-content-store/main.tf
terraform/projects/app-db-admin/main.tf
terraform/projects/app-deploy/main.tf
terraform/projects/app-docker-management/main.tf
terraform/projects/app-draft-cache/main.tf
terraform/projects/app-draft-content-store/main.tf
terraform/projects/app-draft-frontend/main.tf
terraform/projects/app-frontend/main.tf
terraform/projects/app-graphite/main.tf
terraform/projects/app-jumpbox/main.tf
terraform/projects/app-logs-cdn/main.tf
terraform/projects/app-mapit/main.tf
terraform/projects/app-monitoring/main.tf
terraform/projects/app-publishing-api/main.tf
terraform/projects/app-puppetmaster/main.tf
terraform/projects/app-rabbitmq/main.tf
terraform/projects/app-router-backend/main.tf
terraform/projects/app-rummager-elasticsearch/main.tf
terraform/projects/app-search/main.tf
terraform/projects/app-transition-db-admin/main.tf
terraform/projects/app-whitehall-backend/main.tf
terraform/projects/app-whitehall-frontend/main.tf
terraform/projects/infra-aws-logging/main.tf

- Update the prefix as per Logit's request
- Update permissions for the logit-read user

Update ELB logs

---

terraform/projects/app-apt/main.tf
terraform/projects/app-backend/main.tf
terraform/projects/app-bouncer/main.tf
terraform/projects/app-cache/main.tf
terraform/projects/app-calculators-frontend/main.tf
terraform/projects/app-content-store/main.tf
terraform/projects/app-db-admin/main.tf
terraform/projects/app-deploy/main.tf
terraform/projects/app-docker-management/main.tf
terraform/projects/app-draft-cache/main.tf
terraform/projects/app-draft-content-store/main.tf
terraform/projects/app-draft-frontend/main.tf
terraform/projects/app-frontend/main.tf
terraform/projects/app-graphite/main.tf
terraform/projects/app-jumpbox/main.tf
terraform/projects/app-logs-cdn/main.tf
terraform/projects/app-mapit/main.tf
terraform/projects/app-monitoring/main.tf
terraform/projects/app-publishing-api/main.tf
terraform/projects/app-puppetmaster/main.tf
terraform/projects/app-rabbitmq/main.tf
terraform/projects/app-router-backend/main.tf
terraform/projects/app-rummager-elasticsearch/main.tf
terraform/projects/app-search/main.tf
terraform/projects/app-transition-db-admin/main.tf
terraform/projects/app-whitehall-backend/main.tf
terraform/projects/app-whitehall-frontend/main.tf

I made a fundamental error in my previous commit, so revert and add it to the correct place.
https://trello.com/c/YnzOGMp7/773-ship-logs-from-elbs-to-the-aws-infrastructure-logging-bucket

Add ELB prefix in the correct place

---

terraform/projects/app-transition-postgresql/main.tf

- Bouncer uses the database secondary (here, standby) to read its data, so we set one up.

Add an RDS replica to Transition PostgreSQL database

---

terraform/projects/app-rummager-elasticsearch/README.md

- I forgot to do this in #348.

Document the rummager_elasticsearch_{1,2,3}_backups_enabled variables

---

doc/guides/environment-provisioning.md

We have a bunch of new infra stacks that need to be deployed before applications are deployed. Add these into the guide.

Update environment provisioning guide

---

terraform/modules/aws/network/nat/README.md
terraform/modules/aws/network/nat/main.tf
terraform/modules/aws/network/private_subnet/README.md
terraform/modules/aws/network/private_subnet/main.tf
terraform/modules/aws/network/public_subnet/README.md
terraform/modules/aws/network/public_subnet/main.tf
terraform/modules/aws/network/vpc/README.md
terraform/modules/aws/network/vpc/main.tf

Fix comments and descriptions and generate README for network
modules.

Add documentation for network modules

---

terraform/modules/aws/lb/README.md
terraform/modules/aws/lb/main.tf

Add AWS lb module to create application and network Load Balancers.
It requires aws module > 1.2.0

Add AWS lb module

---

terraform/projects/app-deploy/main.tf
terraform/projects/infra-security-groups/deploy.tf
terraform/projects/infra-security-groups/outputs.tf

Create an internal ELB for deploy, and create the security groups that
allow this from all machines.

Allow internal deploy access

---

doc/guides/environment-provisioning.md
terraform/projects/app-puppetmaster/main.tf

- Ensure that when no resource is set to still apply the changes
- Update docs to pass in variable explicitly
See commits for detail.

Enable bootstrap fixes

---

terraform/modules/aws/rds_instance/README.md
terraform/modules/aws/rds_instance/main.tf
terraform/projects/app-mysql/README.md
terraform/projects/app-mysql/main.tf
terraform/projects/app-postgresql/README.md
terraform/projects/app-postgresql/main.tf
terraform/projects/app-transition-postgresql/README.md
terraform/projects/app-transition-postgresql/main.tf

Add an option to create a db instance from a previous snapshot.

Add RDS snapshot_identifier option

---

terraform/modules/aws/lb/README.md
terraform/modules/aws/lb/main.tf
terraform/modules/aws/lb_listener_rules/README.md
terraform/modules/aws/lb_listener_rules/main.tf
terraform/projects/app-apt/main.tf

Update app-apt to use the lb module. Classic LBs are
migrated to ALBs.
https://trello.com/c/bKqwIbOi/840-refactor-elbs-to-lbs

Update lb modules and add apt example

---

doc/guides/environment-provisioning.md

- The stacks 'delana', 'deana' and 'issam' still have data in the bucket,
but 'blue' and 'green' are in common use.

Update the example bucket contents in the environment provisioning docs

---

terraform/projects/infra-public-services/main.tf

After reviewing DNS entries for integration.publishing.service.gov.uk,
we found that the following services don't need to be user facing:
- content-store
- draft-content-store
- publishing-api

Removed unused public services

---

terraform/projects/infra-security/main.tf

Currently this will be read only, with Tom Natt being our guinea pig.

Add govuk-user role

---

doc/guides/pre-migration-testing.md

I'm brain dumping info to help us enable testing.

Add notes on Smokey

---

terraform/modules/aws/lb/README.md
terraform/modules/aws/lb/main.tf

Add a new parameter to customise the health check match response code.

LB module add health check matcher parameter

---

terraform/modules/aws/alarms/rds/main.tf

Fix splat syntax warning and convert output to string.

Update module alarms RDS to 0.11.1

---

doc/guides/pre-migration-testing.md
tools/migration-hosts.sh

I have written this with future proofing in mind, for new environments and if we rebuild the stack. It does a lookup of the current assigned DNS record and adds it to your hosts file.

Add tool to update hosts

---

terraform/userdata/00-base

This reverts commit 26eb9f0a0660108bbb30a2348cfb315d3c486538.
When we tried to rebuild machines couldn't communicate with the master.

Revert "Remove stackname from search domain"

---

terraform/modules/aws/alarms/cloudtrail/README.md
terraform/modules/aws/alarms/cloudtrail/main.tf
terraform/policies/cloudtrail_assume_policy.json
terraform/policies/cloudtrail_cloudwatch_logs_policy.tpl
terraform/policies/cloudtrail_s3_policy.tpl
terraform/projects/infra-security/README.md
terraform/projects/infra-security/main.tf

CloudTrail settings and alarms

Add cloudtrail

---

doc/guides/environment-provisioning.md

This is WIP because as we rebuild the environment, we'll probably find broken things.

Update envrionment provisioning docs

---

terraform/projects/infra-artefact-bucket/staging.govuk.backend
terraform/projects/infra-database-backups-bucket/staging.govuk.backend
terraform/projects/infra-monitoring/staging.govuk.backend
terraform/projects/infra-networking/staging.govuk.backend
terraform/projects/infra-public-services/staging.govuk.backend
terraform/projects/infra-root-dns-zones/staging.govuk.backend
terraform/projects/infra-security-groups/staging.govuk.backend
terraform/projects/infra-security/staging.govuk.backend
terraform/projects/infra-vpc/staging.govuk.backend

Looking in the wrong place for the state file
Solo: @jljalderman

BAU - Fix path for statefile

---

terraform/modules/aws/lb/README.md

By running the tools/update-docs.sh script.

Update some docs

---

doc/guides/deploying-terraform.md
doc/guides/getting-started.md
doc/guides/styleguide.md

Update docs slightly

---

terraform/projects/infra-security/README.md
terraform/projects/infra-security/main.tf

work in combination with: https://github.com/alphagov/govuk-aws-data/pull/85
https://trello.com/c/h7CNr5H5/51-dev-vm-replication

Add poweruser role

---

doc/architecture/decisions/0003-aws-networking-outline.md
terraform/projects/infra-monitoring/test.govuk.backend
terraform/projects/infra-networking/test.govuk.backend
terraform/projects/infra-vpc/test.govuk.backend

Add backend files for monitoring, vpc and network projects in the
test environment.
Update networking ADR to reflect ip range in the test environment.

Set up infra test environment

---

terraform/projects/app-backend/main.tf
terraform/projects/app-bouncer/main.tf
terraform/projects/app-content-store/main.tf
terraform/projects/app-draft-cache/main.tf
terraform/projects/app-draft-content-store/main.tf
terraform/projects/app-draft-frontend/main.tf
terraform/projects/app-frontend/main.tf
terraform/projects/app-publishing-api/main.tf
terraform/projects/app-whitehall-backend/main.tf
terraform/projects/app-whitehall-frontend/main.tf

New variable asg_size to store the same value for asg_max_size, asg_min_size, and asg_desired_size

Introduced new variable asg_size

---

tools/govukcli

Please someone stop me adding to this script. I'm hooked.
This adds an error function, in which you pass in the error message, and adds some friendly colour to help highlight the error.

Add error function in govukcli

---

jenkins.sh

Jenkins has the ability to fetch repos using SSH.

Git clone using SSH

---

jenkins.sh

- My bash isn't good, but square brackets were needed in previous ifs.

Fix if statement syntax in the jenkins.sh that runs Terraform

---

jenkins.sh

The variable was not being assigned correctly.
Change to a case statement to be more concise.

Fix build script

---

doc/guides/environment-provisioning.md

This causes ambigious errors if it is not completed about missing functions.

Add note about Puppet librarian

---

terraform/projects/app-graphite/main.tf
terraform/projects/infra-database-backups-bucket/main.tf

Creating an S3 bucket and the policy and role to receive the backups from graphite
https://trello.com/c/H9rrNIZc/987-graphite-backups-to-s3-directly-with-whisper-backup-or-similar

Graphite backup

---

terraform/policies/s3_backup_replica_policy.json
terraform/policies/s3_backup_replica_role.tpl
terraform/projects/infra-database-backups-bucket/README.md
terraform/projects/infra-database-backups-bucket/main.tf

https://trello.com/c/dvhWJzhr/1049-ensure-that-at-least-the-staging-and-production-s3-backup-buckets-in-aws-are-cross-region-replicated-to-another-aws-region-and-v

AWS S3 Backup cross region replication

---

terraform/projects/app-backend/README.md
terraform/projects/app-bouncer/README.md
terraform/projects/app-content-store/README.md
terraform/projects/app-draft-cache/README.md
terraform/projects/app-draft-content-store/README.md
terraform/projects/app-draft-frontend/README.md
terraform/projects/app-email-alert-api/README.md
terraform/projects/app-frontend/README.md
terraform/projects/app-graphite/README.md
terraform/projects/app-publishing-api/README.md
terraform/projects/app-whitehall-backend/README.md
terraform/projects/app-whitehall-frontend/README.md
terraform/projects/infra-database-backups-bucket/README.md
terraform/projects/infra-networking/README.md
terraform/projects/infra-public-services/README.md
terraform/projects/infra-security-groups/README.md

We get this by running `tools/update-docs.sh`.

Update terraform docs

---

Jenkinsfile
jenkins.sh
terraform/userdata/00-base
terraform/userdata/10-associate-eni
terraform/userdata/10-attach-volumes
terraform/userdata/10-db-admin
terraform/userdata/20-puppet-client
terraform/userdata/20-puppetmaster
terraform/userdata/30-deploy-apps
tools/adr-check.sh
tools/aws-copy-puppet-setup.sh
tools/aws-push-puppet.sh
tools/build-terraform-project.sh
tools/govukcli
tools/json-check.sh
tools/update-puppet.sh

Check the scripts in the tools directory, including govukcli, and userdata scripts.
I'm a bit wary of merging this as it changes things that could be problematic, but I also have faith in `shellcheck` and the documentation that comes with it. It caught a few things that I was surprised at and on the whole I think it makes it a better set of scripts.

Add shellcheck

---

terraform/projects/app-mongo/main.tf

Adding ebs volume to mongo instances

add_mongo_ebs_volume

---

terraform/projects/infra-security-groups/backend-redis.tf

Use the correct resource type (a rule not a whole SG) and make the
resource name unique.

Fix the ingress rule from db-admin to redis

---

terraform/projects/app-logs-cdn/main.tf

Moving the encryption endpoint on the ELB level for app-logs-cdn

Aws cert for logs cdn

---

terraform/projects/infra-security-groups/bouncer.tf

It looks like these are configured the wrong way around, the source should be set to bouncer.

Configure the source security group for bouncer

---

terraform/projects/app-mongo/additional_policy.json
terraform/projects/app-mongo/main.tf

Add ebs volume for mongo db.
Also needs govuk-aws-data PR
Solo: @jljalderman

Add additional EBS volume for mongo

---

terraform/projects/app-mongo/main.tf

device name not allowed, need to use /dev/xvdf

fix_mongo_mount

---

terraform/projects/app-logs-cdn/README.md
terraform/projects/app-mirrorer/README.md

- We're bad at keeping these up to date on every pull-request if needed,
so bulk-correct all the things.

Update docs for main.tf files

---

doc/guides/environment-provisioning.md

- We didn't experience a clean puppetmaster deployment. Hence, we are
including the error that we had to resolve, to the documentation.
https://trello.com/c/nr8kuCOv/1170-aws-staging-puppet-is-broken

Puppetmaster Deployment

---

terraform/projects/app-ckan/main.tf
terraform/projects/infra-public-services/README.md
terraform/projects/infra-public-services/main.tf
terraform/projects/infra-security-groups/backend-redis.tf
terraform/projects/infra-security-groups/ckan.tf
terraform/projects/infra-security-groups/postgresql.tf

- Some security group changes to allow enough access
- Create public service to allow ingress to the app

CKAN infrastructure fixes

---

terraform/projects/app-mysql/README.md
terraform/projects/app-mysql/main.tf

- We are replacing the hardcoded storage size to a variable. This will
help us to change the storage size per environment.

AWS RDS MySQL - Storage Size Variable

---

terraform/projects/infra-govuk-repo-mirror/production.govuk.backend
terraform/projects/infra-govuk-repo-mirror/staging.govuk.backend
terraform/projects/infra-govuk-repo-mirror/test.govuk.backend

https://trello.com/c/TX8kPxzK/319-start-backing-up-our-code-in-aws-codecommit-not-gitlab
cc @boffbowsh

Add test, staging and production backend envs for govuk-repo-mirror

---

terraform/projects/infra-security-groups/README.md
terraform/projects/infra-security-groups/backend-redis.tf
terraform/projects/infra-security-groups/management.tf
terraform/projects/infra-security-groups/mongo.tf
terraform/projects/infra-security-groups/mysql.tf
terraform/projects/infra-security-groups/outputs.tf
terraform/projects/infra-security-groups/pentesters.tf
terraform/projects/infra-security-groups/postgresql.tf
terraform/projects/infra-security-groups/transition-postgresql.tf
terraform/projects/infra-security-groups/warehouse-postgresql.tf

These resources are deliberatly being added out of sequence so they are
more visually disturbing

Allow pentesters to touch everything

---

terraform/projects/app-warehouse/main.tf

Replicates https://github.com/alphagov/govuk-provisioning/pull/63.

Increase storage space for warehouse RDS instance

---

terraform/projects/infra-content-publisher/production.govuk.backend

https://trello.com/c/63nq4r30/138-setup-an-s3-bucket-to-store-assets

Fix content publisher prod typo (no state key)

---

terraform/projects/app-backend/main.tf

See Zendesk ticket #3107683
@szd55gds

Increasing the size of the root partition of backend from 30G to 60G

---

terraform/projects/app-mongo/main.tf
terraform/projects/infra-database-backups-bucket/reader.tf
terraform/projects/infra-database-backups-bucket/writer.tf

Add permission to read mongo bucket from mongo machines

Add permission to read mongo bucket from mongo machines

---

terraform/projects/app-mongo/main.tf

Fix the policy names and counts per-environment for app-mongo

---

terraform/projects/infra-monitoring/main.tf

Add name to policy attachment

---

tools/govuk-puppetmaster-bootstrap.sh

- I somehow broke this two days ago
solo: @schmie

Fix typo left in latest commit to puppetmaster-bootstrap

---

tools/govuk-puppetmaster-bootstrap.sh

- These were made staging-specific in the first instance, this needs to
change for general env access
solo: @schmie

Change puppetmaster bootstrap SSM key names

---

doc/guides/environment-provisioning.md

- Terraform version updated
- Alternative invocation (without $ENVVARS) of script elaborated
- Slightly more information on stack/app naming
solo: @schmie

[WIP] Docs refresh for provisioning 

---

terraform/projects/infra-security-groups/README.md
terraform/projects/infra-security-groups/ckan.tf
terraform/projects/infra-security-groups/variables.tf

Trello card: https://trello.com/c/CGEGLLGY/91-prep-checklist-of-things-to-do-before-pen-test

Allow SSH access to CKAN machine from tester's IP addresses

---

terraform/projects/infra-security-groups/README.md
terraform/projects/infra-security-groups/ckan.tf
terraform/projects/infra-security-groups/offsite_ssh.tf
terraform/projects/infra-security-groups/variables.tf

This reverts commits ed12fbf113747cd6aba8ed453e077e8949df5ff8, 549c27a3b6e7b1585346fc102fc9b0e2848846c5 and 485dad582b8c00aff8c20ce827dd080f0cad2f95.
Trello card: https://trello.com/c/mTPiQtaB/357-gds-leaver-commissum-associates-ltd-ckan-it-health-check-contractor

Remove SSH access for CKAN IT Health Check contractor

---

terraform/projects/infra-carrenza-vpn/staging.govuk.backend

- We want to control the Carrenza VPN config in staging via TF after
all
solo: @schmie

Add staging backend for infra-carrenza-vpn

---

terraform/README.md
terraform/projects/app-backend/main.tf
terraform/projects/infra-security-groups/README.md
terraform/projects/infra-security-groups/outputs.tf
terraform/projects/infra-security-groups/variables.tf
terraform/projects/infra-security-groups/vpn.tf

- Add access to AWS for HTTP, HTTPS and ICMP. This should permit on-prem subnets.

Add SG to permit access link-checker-api

---

terraform/projects/infra-content-publisher/env_sync.tf
terraform/projects/infra-env-sync-and-backup/s3_sync_policy.tpl

https://trello.com/c/NTr4JsF2/513-investigate-syncing-s3-production-to-staging-integration

Add missing PutObjectAcl permission for sync

---

terraform/projects/infra-csw/README.md
terraform/projects/infra-csw/integration.govuk.backend
terraform/projects/infra-csw/main.tf
terraform/projects/infra-csw/production.govuk.backend
terraform/projects/infra-csw/staging.govuk.backend

Create a role and policy to grant access to a lambda function
implemented by cloud security watch
https://github.com/alphagov/csw-client-role

Add project infra-csw

---

terraform/projects/infra-csw/README.md
terraform/projects/infra-csw/main.tf

Change var name : region to aws_region

Change var name : region to aws_region

---

terraform/projects/infra-env-sync-and-backup/asset_manager.tf
terraform/projects/infra-env-sync-and-backup/content_publisher.tf
terraform/projects/infra-env-sync-and-backup/main.tf
terraform/projects/infra-env-sync-and-backup/s3_assets_sync_policy.tpl

https://trello.com/c/NTr4JsF2/513-investigate-syncing-s3-production-to-staging-integration

Add existing writer policy for asset manager sync

---

terraform/projects/infra-monitoring/tools.govuk.backend
terraform/projects/infra-networking/tools.govuk.backend
terraform/projects/infra-root-dns-zones/tools.govuk.backend
terraform/projects/infra-security-groups/tools.govuk.backend
terraform/projects/infra-stack-dns-zones/tools.govuk.backend
terraform/projects/infra-vpc/tools.govuk.backend

This commit adds new backends for the govuk-tools account to projects that need to be applied in govuk-tools.

Add govuk-tools backends

---

terraform/projects/infra-artefact-bucket/main.tf
terraform/projects/infra-assets/remote_state.tf
terraform/projects/infra-carrenza-vpn/main.tf
terraform/projects/infra-content-publisher/remote_state.tf
terraform/projects/infra-database-backups-bucket/main.tf
terraform/projects/infra-datagovuk-organogram-bucket/main.tf
terraform/projects/infra-datagovuk-static-bucket/main.tf
terraform/projects/infra-email-alert-api-archive/remote_state.tf
terraform/projects/infra-env-sync-and-backup/remote_state.tf
terraform/projects/infra-fastly-logs/remote_state.tf
terraform/projects/infra-govuk-cdn-logs-monitor-bucket/remote_state.tf
terraform/projects/infra-govuk-repo-mirror/remote_state.tf
terraform/projects/infra-mirror-bucket/main.tf
terraform/projects/infra-networking/main.tf
terraform/projects/infra-public-services/remote_state.tf
terraform/projects/infra-root-dns-zones/main.tf
terraform/projects/infra-security-groups/main.tf
terraform/projects/infra-stack-dns-zones/main.tf
terraform/projects/infra-support-api/remote_state.tf
terraform/projects/infra-vpc/main.tf
terraform/projects/infra-wal-e-warehouse-bucket/main.tf

This commit changes references to all remote states to make the region read from a variable. This variable will be set to the same region that the project is located in.

Make remote state region a variable

---

terraform/projects/app-data-science/main.tf

This commit adds security groups to the data science machines to allow ingress SSH access and all egress access.

Add data science machine security groups

---

terraform/projects/app-data-science/main.tf

Instance types are all lowercase.

Fix instance type for data science machines

---

terraform/projects/app-data-science/README.md
terraform/projects/app-data-science/main.tf

This commit adds an ELB for the data science machines to allow access via office IPs.

Add ELB for the data science machines

---

terraform/projects/infra-public-services/README.md
terraform/projects/infra-public-services/main.tf

govuk-aws-data PR: https://github.com/alphagov/govuk-aws-data/pull/313

Add elasticsearch5 and search-api DNS records

---

terraform/projects/app-db-admin/main.tf

This has been modified already so this commit reflects the change in code.

Update root volume for db-admin

---

terraform/projects/fastly-datagovuk/main.tf

data.gov.uk is the canonical host name, so we should redirect the www version.

Add www to non-www redirect for data.gov.uk

---

terraform/projects/fastly-datagovuk/main.tf

All VCL needs to use double quotes.

Use nested double quotes

---

terraform/projects/app-elasticsearch5/main.tf

Trello card: https://trello.com/c/ut3wIgN6/31-set-up-new-managed-elasticsearch-cluster-in-awshttps://trello.com/c/ut3wIgN6/31-set-up-new-managed-elasticsearch-cluster-in-aws

Fix two issues in provision of managed Elasticsearch 5.6 cluster

---

terraform/projects/app-data-science/main.tf

This commit adds two data science machines to reflect the ones that have been created manually.

Add data science machines

---

terraform/projects/app-elasticsearch5/main.tf

Trello card: https://trello.com/c/jc1LM6nM/58-set-up-export-of-error-logs-from-elasticsearch-to-cloudwatch

Fix typo in Elasticsearch logging options

---

terraform/projects/app-elasticsearch5/main.tf

Trello card: https://trello.com/c/jc1LM6nM/58-set-up-export-of-error-logs-from-elasticsearch-to-cloudwatch

Fix a further two typos in ES5 configuration

---

terraform/projects/app-elasticsearch5/main.tf

This creates an access policy that allows the logs to be written
Trello card: https://trello.com/c/jc1LM6nM/58-set-up-export-of-error-logs-from-elasticsearch-to-cloudwatch

Add a access policy for Elasticsearch logs

---

terraform/modules/aws/cloudwatch_log_exporter/main.tf

Trello card: https://trello.com/c/44CAPD5j/57-set-up-export-of-logs-from-cloudwatch-to-s3

Remove non-permitted slash characters from lambda permission name

---

terraform/projects/app-elasticsearch5/README.md
terraform/projects/app-elasticsearch5/main.tf

Trello card: https://trello.com/c/nLemuXWJ/62-update-es5-cluster-configuration-based-on-architecture-decision

Change variable elasticsearch5_dedicated_master_enabled to a string

---

doc/guides/redeploying-applications-on-rebuild.md

Application deploys are now automatic, so mention this, as well as a
bit of information about how it works.

Update the information on the Redeploying docs page

---

terraform/projects/infra-public-services/main.tf

- Should not merge after 6 pm
solo: @schmie

Fix copy-paste error

---

terraform/projects/app-elasticsearch5/main.tf

Add a bucket policy which grants the S3 permissions we want to our
three (prod, staging, integration) AWS root accounts.
---
[Plan](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/888/console)
[Trello card](https://trello.com/c/QQHOpt56/75-update-data-sync-for-elasticsearch-5)

Fix es5 manual snapshot bucket cross-account access

---

terraform/projects/infra-monitoring/training.govuk.backend
terraform/projects/infra-networking/training.govuk.backend
terraform/projects/infra-public-services/training.govuk.backend
terraform/projects/infra-root-dns-zones/training.govuk.backend
terraform/projects/infra-security-groups/training.govuk.backend
terraform/projects/infra-security/training.govuk.backend
terraform/projects/infra-vpc/training.govuk.backend

Context:
We are setting up a new training environment and need new
terraform backend files
Decision:
Added terraform backend files for training environment.

Created Terraform Backends for Training Environment

---

terraform/userdata/20-puppetmaster-training
tools/govuk-puppetmaster-training-bootstrap.sh

Duplicated integration userdata and bootstrap puppet scripts
for use in training environment

Added puppet setup scripts for training environment

---

terraform/projects/app-elasticsearch5/main.tf

https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1154/console

Fix indexing upstream_bucket_arn list

---

doc/guides/environment-provisioning.md

Update Puppetmaster provisioning guide

---

terraform/projects/infra-database-backups-bucket/training.govuk.backend

This is needed for the training environment

Add training infra-database-backups-bucket terraform backend

---

terraform/projects/app-monitoring/main.tf

We need a monitoring.* public dns name for fastly to contact the monitoring classic load balancer. We can't use the existing alert.blue because the blue stack will be removed/merged later.
1. add the `monitoring.*` public dns name in the app-monitoring project

add monitoring.* public dns name to monitoring classic load balancer

---

terraform/projects/app-graphite/README.md
terraform/projects/app-graphite/main.tf
terraform/projects/app-graphite/training.govuk.backend

Configure Route53 resources from variable files and make external ELB
optional.

Update app-graphite for Training

---

terraform/projects/app-content-data-api-postgresql/main.tf

Previously there have been problems with autovacuuming for the Content
Data API database (although this was when running on Carrenza).
The following changes should potentially help with general
performance, and also the autovacuuming. The additional logging around
autovacuuming should also help refine the configuration further in the
future.
There isn't a lot of specific reasoning behind these changes, rather
they're slightly more sensible values that hopefully can be better
refined in the future.
Currently m4large instances are in use which have 8 GiB of
memory. Currently the work_mem value is 4MB, and here it's being
increased to 512MB (1/16 of the overall memory). A larger value should
permit PostgreSQL to do more in memory for large queries.
The maintainance_work_mem is currently …

Tune the Content Data API PostgreSQL parameters

---

terraform/projects/app-elasticsearch5/README.md
terraform/projects/app-elasticsearch5/main.tf
terraform/projects/app-elasticsearch5/register-snapshot-repository.py

I should probably commit this rather than just have it sitting on my laptop.

Commit elasticsearch snapshot repository script

---

terraform/projects/app-postgresql/README.md
terraform/projects/app-postgresql/main.tf
terraform/projects/app-postgresql/training.govuk.backend

Add new terraform backend file for app-postgresql

---

terraform/projects/app-mysql/README.md
terraform/projects/app-mysql/main.tf
terraform/projects/app-mysql/training.govuk.backend

Add new terraform backend file for app-mysql

Update app-mysql for training environment

---

jenkins.sh

As it's good to get an idea of what's going to be destroyed, before
going ahead and destroying things.

Support planning destroy operations

---

terraform/projects/app-mirrorer/README.md
terraform/projects/app-mirrorer/main.tf

- We test including assets in the mirrors and will need more local disk
space
solo: @schmie

Make mirrorer EBS disk size variable

---

terraform/projects/infra-mirror-bucket/main.tf

We've imported existing resources and detected a couple or errors in the
code.

Fixes infra-mirror-bucket cloudfront

---

tools/deploy.rb

This commit adds the new training environment to the `deploy.rb` script.

Add training environment to deploy script

---

terraform/projects/app-govuk-attachments/README.md
terraform/projects/app-govuk-attachments/integration.govuk.backend
terraform/projects/app-govuk-attachments/main.tf
terraform/projects/app-govuk-attachments/policy.tf
terraform/projects/app-govuk-attachments/production.govuk.backend
terraform/projects/app-govuk-attachments/staging.govuk.backend
terraform/projects/app-govuk-attachments/test.govuk.backend

Migrate govuk_attachments to this repository:
https://github.com/alphagov/govuk-terraform-provisioning/tree/master/old-projects/govuk_attachments

Migrate govuk_attachments project from govuk-terraform-provisioning

---

terraform/projects/app-mysql-xtrabackups/README.md
terraform/projects/app-mysql-xtrabackups/main.tf
terraform/projects/app-mysql-xtrabackups/policy.tf
terraform/projects/app-mysql-xtrabackups/production.govuk.backend
terraform/projects/app-mysql-xtrabackups/staging.govuk.backend

Migrated from:
https://github.com/alphagov/govuk-terraform-provisioning/tree/master/old-projects/mysql_xtrabackups

Migrate mysql-xtrabackups from govuk-terraform-provisioning

---

terraform/projects/app-custom-formats-mapit-storage/README.md
terraform/projects/app-custom-formats-mapit-storage/main.tf
terraform/projects/app-custom-formats-mapit-storage/policy.tf
terraform/projects/app-custom-formats-mapit-storage/production.govuk.backend

Migrated from:
https://github.com/alphagov/govuk-terraform-provisioning/tree/master/projects/custom_formats_mapit_storage

Migrate custom-formats-mapit-storage from govuk-terraform-provisioning

---

terraform/projects/app-wal-e-backups-postgresql/README.md
terraform/projects/app-wal-e-backups-postgresql/main.tf
terraform/projects/app-wal-e-backups-postgresql/policy.tf
terraform/projects/app-wal-e-backups-postgresql/production.govuk.backend
terraform/projects/app-wal-e-backups-postgresql/staging.govuk.backend

Migrated from:
https://github.com/alphagov/govuk-terraform-provisioning/tree/master/old-projects/wal-e_backups_postgresql

Migrate wal-e-backups-postgresql from govuk-terraform-provisioning

---

terraform/policies/s3_govuk_content_publisher_activestorage_replication_policy.tpl
terraform/policies/s3_govuk_content_publisher_activestorage_replication_role.tpl
terraform/projects/infra-content-publisher/README.md
terraform/projects/infra-content-publisher/main.tf

This change ensures that this bucket now has cross region replication.

Add S3 Replication to govuk-production-content-publisher-activestorage Bucket

---

terraform/policies/s3_backup_replica_policy.json
terraform/projects/app-custom-formats-mapit-storage/README.md
terraform/projects/app-custom-formats-mapit-storage/main.tf

This change ensures that this bucket now has cross region replication.

Add S3 Replication to custom-formats-mapit-storage bucket

---

terraform/projects/app-rabbitmq/README.md
terraform/projects/app-rabbitmq/main.tf
terraform/projects/infra-security-groups/README.md
terraform/projects/infra-security-groups/rabbitmq.tf
terraform/projects/infra-security-groups/variables.tf

We only want a rabbitmq federation in staging and production

Make the terraforming of the necessary resources for a rabbitmq federation conditional depending on the environment

---

terraform/projects/app-licensify-backend/production.blue.backend
terraform/projects/app-licensify-backend/staging.blue.backend

The bucket is in eu-west-1 not eu-west-2

Change region to eu-west-1 for app-licensify-backend backends

---

terraform/projects/infra-dev_vm/main.tf

Otherwise, I think the wrong region is used.

Add a provider bit of config to infra-dev_vm/main.tf

---

terraform/projects/infra-ukcloud-vpn/README.md
terraform/projects/infra-ukcloud-vpn/integration.govuk.backend
terraform/projects/infra-ukcloud-vpn/main.tf
terraform/projects/infra-ukcloud-vpn/production.govuk.backend
terraform/projects/infra-ukcloud-vpn/staging.govuk.backend

This allows us to circumvent Civica's IP restrictions.

Add VPN between AWS and UKCloud

---

terraform/projects/app-search/main.tf

Currently sitemaps are served from search machines.  This means that if a new machine comes up, any sitemap requests sent to it will 404 until the rake task to generate the files is run.  That's not good.  Additionally, generating identical sitemap files on every machine is kind of silly.
So, we want to change the process to:
- At midnight, Jenkins picks *one* search machine (randomly), runs the task to generate sitemaps, and copies them to this bucket.
- Whenever a sitemap is requested from search-api, it proxies the request to s3.
This solves both of our problems.
---
[Plan](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2470/console)
[Trello card](https://trello.com/c/KuBZtH1v/1002-generate-sitemaps-when-a-new-search-machine-is-provisioned)

Add an S3 bucket for sitemaps

---

terraform/projects/infra-ukcloud-vpn/README.md
terraform/projects/infra-ukcloud-vpn/main.tf

Add pre-generated key to tunnel2 of VPN.
Change naming of VPN resources to be more consistent.

Amend UKCloud VPN Settings

---

terraform/projects/infra-dev_vm/main.tf

As I believe this was set incorrectly.

Manage the public access for the Dev VM bucket

---

terraform/projects/app-prometheus/README.md
terraform/projects/app-prometheus/main.tf

Integration is already on t3, but let's make Staging and Prod the same.

Switch prometheus instances from t2.micro to t3.micro.

---

terraform/projects/app-publishing-api/main.tf

We have added an alias to allow apps in Carrenza/6DG to
talk to the Publishing Api in AWS.
Co-authored-by: Chris Banks <chris.banks@digital.cabinet-office.gov.uk >

Add Alias for Publishing-Api Migration Work

---

terraform/projects/app-knowledge-graph/main.tf

This PR adds a new govuk-data-infrastructure bucket as part of the Knowledge Graph project (meaning that this is only for integration) and adds a new policy to allow the Knowledge Graph role to read/write from/to this bucket.

Add data infrastructure S3 bucket and associated policy for Knowledge Graph

---

terraform/projects/app-search/main.tf

We want to store search api relevancy judgement data in CSV files in S3 for use in ranking evaluation.
Ranking evaluation is currently only done locally against local files, but once we're able to fetch these from S3 we can have the relevancy monitoring jobs run in AWS.
This will create a bucket like `govuk-<environment>-search-relevancy`
Trello: https://trello.com/c/xys5Wp6o.

Add S3 bucket for search relevancy

---

terraform/projects/infra-email-alert-api-archive/main.tf

https://trello.com/c/z3REh76h/178-export-regular-data-on-email-subscriptions-for-insights-team

Support messages in Email Alert API archive

---

terraform/policies/aws_iam_check_policy.json
terraform/projects/infra-monitoring/main.tf

Create an IAM user and policy for Icinga AWS IAM check

IAM user for AWS IAM check

---

terraform/projects/app-graphite/README.md
terraform/projects/app-graphite/main.tf

This allow the volume size to be customisable
between different environments.

Add Variable For EBS Volume Size

---

terraform/projects/app-shared-documentdb/README.md
terraform/projects/app-shared-documentdb/remote_state.tf

need to add the infra-security remote backend for the kop key

need to add the infra-security remote backend for the kms key

---

terraform/projects/app-search/main.tf

SageMaker needs to be able to access the S3 bucket.
---
[Plan](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3494/console)

Allow SageMaker to assume LTR role

---

doc/guides/getting-started.md

- Before, this said "_maybe_ do this thing".

doc/guides/getting-started: Recommend `tfenv` outright

---

terraform/projects/app-search/main.tf

Delete training data and models after 7 days

---

Jenkinsfile
jenkins.sh
pipeline.yml
terraform/userdata/05-tag-mapit-volume
terraform/userdata/10-associate-eni
terraform/userdata/10-attach-volumes
terraform/userdata/10-db-admin
terraform/userdata/20-puppet-client
terraform/userdata/20-puppetmaster
terraform/userdata/20-puppetmaster-integration
terraform/userdata/20-puppetmaster-production
terraform/userdata/20-puppetmaster-staging
terraform/userdata/20-puppetmaster-training
terraform/userdata/30-deploy-apps
tools/build-terraform-project.sh
tools/terraform-format.sh
tools/update-docs.sh

Reverts alphagov/govuk-aws#1236 to restore to alphagov/govuk-aws#1233.
We're done deploying the cache and calculators-frontend ASG increases now, we can deploy this tomorrow when Issy has a laptop again.

Revert "Revert "Migrate shellcheck CI check from Jenkins to Concourse""

---

terraform/projects/app-search/main.tf

We need this for the healthcheck.
---
[Plan](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3817/console)

Let search-api describe SageMaker endpoints

---

terraform/policies/specialist_publisher_s3_writer_policy.tpl

This was left out of https://github.com/alphagov/govuk-aws/pull/1254

Add s3 policy missed from previous specialist-publisher PR

---

terraform/projects/app-shared-documentdb/README.md
terraform/projects/app-shared-documentdb/main.tf

Add human readable CNAME for shared-documentdb endpoint

Add human readable CNAME for shared-documentdb endpoint

---

terraform/projects/app-gatling/README.md
terraform/projects/app-gatling/main.tf

The recent wave of load-testing has now completed so we can turn off the Gatling machine.
[Trello](https://trello.com/c/Mqpj06X5/1871-2-turn-off-the-gatling-machine-after-loadtesting)

Reset Gatling load-testing machine ASG to 0

---

terraform/projects/app-prometheus/README.md
terraform/projects/app-prometheus/main.tf

We are seeing errors to do with running out of memory.

Increase prometheus instance from t3.small->t3.medium

---

docs/guides/environment-provisioning.md

Fix links in env provisioning doc

---

tools/govuk-puppetmaster-test-bootstrap.sh

Our puppetmaster seems to be hanging instead of coming up. Maybe we can
work out why with some more verboseness.

WIP: Make bundle verbose to debug hanging issue

---

docs/guides/bootstrap-aws.md
docs/guides/environment-provisioning.md

- I don't like individual `brew install` commands littered across a doc.
- Some of the markdown was incorrect.
- These probably need more tweaks, but we can make them once we've done
the thing for the first time in years.

guides: Modernize guides for environment provisioning

---

terraform/projects/app-data-science-data/userdata.tpl
terraform/projects/app-knowledge-graph/userdata.tpl

The knowledge graph requires python 3.7 for some key packages

Upgrade python to version 3.7

---

terraform/projects/app-gatling/README.md
terraform/projects/app-gatling/main.tf

This PR sets the Gatling machine auto scaling group to 1, to enable load-testing to take place.

Make Gatling loadtesting machine ASG 1

---

terraform/projects/app-gatling/README.md
terraform/projects/app-gatling/main.tf

This load testing has now finished and we can scale down the machine.
Reverts alphagov/govuk-aws#1349

Revert "Make Gatling loadtesting machine ASG 1"

---

terraform/projects/app-gatling/README.md
terraform/projects/app-gatling/main.tf

Set Gatling loadtesting machine ASG to 1

Set Gatling loadtesting machine ASG to 1

---

terraform/projects/app-gatling/README.md
terraform/projects/app-gatling/main.tf

Load testing complete so resetting ASG to 0
Reverts alphagov/govuk-aws#1352

Revert "Set Gatling loadtesting machine ASG to 1"

---

terraform/projects/app-gatling/README.md
terraform/projects/app-gatling/main.tf

This PR sets the Gatling ASG to 1 to allow loadtesting.

Set Gatling ASG to 1

---

terraform/projects/app-gatling/README.md
terraform/projects/app-gatling/main.tf

Reverts alphagov/govuk-aws#1370 because we finished using gatling

Revert "Set Gatling ASG to 1"

---

terraform/projects/app-gatling/README.md
terraform/projects/app-gatling/main.tf

Load testing has now finished.
This reverts commit 5264a09efce8374efd6cfa8af7d961e1eb46eba2.

Revert "Set Gatling ASG to 1 for load-testing"

---

.github/workflows/ci.yml

Also adding some caching, following some of the guidance in https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-with-github-actions.html#simple-ruby-application

Actions: Add --deployment to bundle install

---

terraform/projects/app-data-feedback-pipelines/main.tf

This PR allows the Concourse role to deploy the feedback pipeline Lambdas. To do this it needs to be able to upload the deployment package to S3, then access it and use it to update the underlying code version used by the Lambdas.

Allow Concourse role to deploy feedback pipeline Lambdas

---

terraform/projects/app-knowledge-graph/main.tf
terraform/projects/app-knowledge-graph/userdata-sandbox.tpl

A sandbox of the Knowledge Graph for Data Scientists to continue their experiments, while providing
users with a slightly more stable Knowledge Graph of their own.
See also https://github.com/alphagov/govuk-knowledge-graph/pull/289
Trello card https://trello.com/c/P3yquf4l

Create a sandbox of the Knowledge Graph for Data Scientists

---

terraform/projects/app-mapit/main.tf

This was missed in https://github.com/alphagov/govuk-aws/pull/1418.
Trello card: https://trello.com/c/rm2WTeqk

Remove Mapit instance 5-12 IAM role policy attachment

---

docs/guides/redeploying-applications-on-rebuild.md

Trello card: https://trello.com/c/4Sz5s78X/2400-epic-retire-the-calculators-app

Remove calculators app from list

---

terraform/projects/app-knowledge-graph/main.tf

To accomodate the clock changes to BST and match working hours.

Update knowledge graph startup time

---

terraform/projects/app-data-science-data/userdata.tpl
terraform/projects/app-knowledge-graph/userdata-sandbox.tpl
terraform/projects/app-knowledge-graph/userdata.tpl

Add libicu-dev to data science and knowledge graph instances

---

terraform/userdata/00-base

Update gpg key for the Puppetlabs repository

Update gpg key for the Puppetlabs repository

---

terraform/projects/app-mapit/README.md
terraform/projects/app-mapit/main.tf

Temporarily add a new mapit ASG. This change will be run in integration only, and then reverted.
As per the [developer docs](https://docs.publishing.service.gov.uk/manual/scale-mapit.html)

Temporarily scale mapit

---

terraform/projects/app-mapit/README.md
terraform/projects/app-mapit/main.tf

Reverts alphagov/govuk-aws#1463

Revert "Temporarily scale mapit"

---

terraform/projects/infra-security/README.md
terraform/projects/infra-security/main.tf

- Fix step functions role - so that it can actually be used to create step functions
- add event bridge role that datascience role users can use to schedule step functions

Datas science related roles policies update

---

terraform/projects/app-govuk-rds/db_admin.tf
terraform/projects/app-govuk-rds/rds.tf

See commits for details.  I've already manually applied this branch to integration.
---
[Trello card](https://trello.com/c/rB7CoPoG/42-terraform-up-all-the-new-rds-instances-and-db-admin-ec2-instances)

Fix creating RDS instances

---

terraform/projects/infra-security-groups/postgresql.tf

- In a subsequent PR this file will be removed.
https://trello.com/c/ewzHAr6A/56-remove-postgresql-primary-and-postgresql-standby-infrastructure-and-configuration

Remove all postgresql resources from the infra-security-group

---

terraform/projects/infra-assets/README.md
terraform/projects/infra-assets/main.tf

Add output for asset manager bucket arn to enable adding policy in EKS terraform

Output asset_manager_bucket_arn

---

terraform/projects/app-locations-api/main.tf

Trello: https://trello.com/c/gPRVvLXh/2848-set-up-remaining-infrastructure-for-locations-api-5

Define healthcheck path for Locations API

---

jenkins.sh

This has now been updated to `main`.
Trello card: https://trello.com/c/Ms8fjnrD/2857-3-audit-and-rename-default-branches-to-main

Update default branch in Jenkins file

---

docs/guides/redeploying-applications-on-rebuild.md

Trello:
https://trello.com/c/OtjBZRjL/1131-manuals-deprecate-manuals-frontend

Manuals Frontend is now retired

---

terraform/projects/infra-public-services/README.md
terraform/projects/infra-public-services/main.tf

Reverts https://github.com/alphagov/govuk-aws/pull/1610

Revert removal of licensify-frontent public LB

---

terraform/projects/app-data-science-data/README.md
terraform/projects/app-data-science-data/main.tf
terraform/projects/app-data-science-data/userdata-dev.tpl
terraform/projects/app-data-science-data/userdata.tpl
terraform/projects/app-knowledge-graph/README.md
terraform/projects/app-knowledge-graph/main.tf
terraform/projects/app-knowledge-graph/userdata.tpl

Also, clean up some unused terraform settings, add some documentation in the `main.tf` files.
The dev versions mostly differ from the production versions in that they don't have a schedule to be created every day. Instead they will be run manually as needed.

Create dev versions of app-knowledge-graph and app-data-science-data

---

docs/architecture/decisions/0039-non-govuk-domain-policy.md

See https://docs.google.com/document/d/18kIgL2F0PPCZSjSCLH5z0hOq3Gn8wmCwxrlR1bOPric/edit

Add ADR 39: Non-GOV.UK domain policy

---

terraform/projects/infra-security-groups/README.md
terraform/projects/infra-security-groups/jumpbox.tf

Based on #1185.
Relies on https://github.com/alphagov/govuk-aws-data/pull/1111
Trello: https://trello.com/c/OapOcUjZ/3006-manage-the-it-health-check

Give pentesters SSH access to the Jumpbox machine in Staging

---

terraform/projects/infra-mirror-bucket/README.md
terraform/projects/infra-mirror-bucket/main.tf

Reverts alphagov/govuk-aws#1693
See https://github.com/alphagov/govuk-aws/pull/1693#issuecomment-1398256944
Trello: https://trello.com/c/PMsAXSoT/3029-review-govuks-usage-of-node-2

Revert "Reference different certificate for Cloudfront Production"

---

terraform/projects/fastly-datagovuk/datagovuk.vcl

Uses the [same approach as other gov.uk services](https://github.com/alphagov/govuk-cdn-config/pull/456/commits/aba1e7797fe2380d0e302f6d18d8fa310599a4a4)
During the vcl_recv subroutine, we check to see whether the request is for one of the usual options for security.txt. If so, we throw a custom error (805) which is then processed by the vcl_error subroutine.
vcl_error then catches the custom error code, changes it to a redirect and sets the correct headers.
The user's browser will then redirect to the Cabinet Office's vulnerability disclosure program security.txt.
https://trello.com/c/VLBjBTMe/313-put-securitytxt-on-bouncer-and-dgu

Add security.txt for data.gov.uk

---

terraform/projects/infra-fastly-logs/main.tf

Trello: https://trello.com/c/ozft3OLU/3272-upgrade-psr-owned-python-dependencies-to-v38-3

Update lambda to python 3.8

---

terraform/projects/infra-datagovuk-organogram-bucket/main.tf

Allow access to the bucket from the datagovuk EKS cluster

Update main.tf datagovuk-organogram bucket

---

terraform/projects/app-publishing-amazonmq/variables.tf

We'll need to update further once this has run.
[Trello](https://trello.com/c/CTUqZLUX/1373-update-amazonmq-to-313)

Bump AmazonMQ broker version to 3.12

---

terraform/projects/app-publishing-amazonmq/variables.tf

[Trello](https://trello.com/c/CTUqZLUX/1373-update-amazonmq-to-313)

Bump amazonmq to the latest version
