alphagov/govuk-aws

terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/reader.tf, terraform/projects/infra-database-backups-bucket/writer.tf
This configuration related to the "warehouse" related to the Content
Performance Manager. This has now been renamed to the Content Data
API, so this configuration is now redundant.
=> Remove redundant configuration from infra-database-backups-bucket

terraform/projects/infra-database-backups-bucket/reader.tf
This configuration related to accessing the Content Performance
Manager database backup from Carrenza, in AWS, as part of the
migration to AWS.
This migration has now happened, with the application being called the
Content Data API in AWS, so this configuration is no longer necessary.
=> Remove access to the warehouse-postgresql files

doc/guides/bootstrap-aws.md
Originally created in https://github.com/alphagov/reliability-engineering/pull/87
we are adding this document here until we decide how to organise GOVUK RE documentation.
We need a few instructions to explain how to bootstrap a new AWS environment and
which documents to read.
Pair: @camdesgov @afda16
=> Add AWS bootstrap doc

terraform/projects/app-calculators-frontend/README.md, terraform/projects/app-calculators-frontend/main.tf
Add an ALB to app-calculators-frontend to be able to implement application
specific forward rules and health checks.
We use the enable_alb variable to update the target of the
service DNS record to resolve to the ALB instead of the original
ELB.
=> Add ALB and app health checks to app-calculators-frontend

terraform/projects/app-draft-frontend/README.md, terraform/projects/app-draft-frontend/main.tf
We want to send traffic to each instance only when the application
has been deployed and is healthy. The draft-frontend class only
has an internal ELB to receive traffic. In order to use application
specific health check paths from a LB, we need to use an ALB instead
of ELB and create application specific target groups/health checks
with the lb_listener_rules module.
We initially create a new ALB, and we can move traffic to this new LB
with the `enable_alb` parameter. This parameter updates the ALIAS of
the main service record to point to the ALB instead of the original ELB.
Once we have migrated all the traffic to ALBs, we can remove the code and
resources of the original ELB.
=> Add ALB and app health checks to app-draft-frontend

terraform/modules/aws/lb_listener_rules/main.tf
The LB target group name can't be longer than 32 characters. We are using
`format` to ensure we don't pass that limit, but sometimes this can result
in the `-` character appearing at the end of the string, which is also
not allowed an causes an error. For instance:
```
aws_lb_target_group.tg.6: Error creating LB Target Group: ValidationError:
Target group name 'draft-fron-draft-service-manual-' cannot begin or end with '-'
```
We are going to explicity remove this character if it appears at the end
of the generated string.
=> Remove bad character at the end of the target group name

terraform/projects/app-frontend/README.md, terraform/projects/app-frontend/main.tf
Add an ALB to app-frontend to be able to implement application
specific forward rules and health checks.
We use the `enable_alb` variable to update the target of the
service DNS record to resolve to the ALB instead of the original
ELB.
=> Add ALB and app health checks to app-frontend

terraform/projects/infra-cyber-security-audit/README.md, terraform/projects/infra-cyber-security-audit/integration.govuk.backend, terraform/projects/infra-cyber-security-audit/main.tf, terraform/projects/infra-cyber-security-audit/production.govuk.backend, terraform/projects/infra-cyber-security-audit/staging.govuk.backend
This was requested by cyber to provide access to TrustedAdvisor
resources to them across the GDS estate
solo: @schmie
=> Add Cyber security audit role

terraform/projects/app-publishing-api/README.md, terraform/projects/app-publishing-api/main.tf, terraform/projects/app-publishing-api/training.govuk.backend
Add backend to build app-publishing-api in the Training environment.
=> Update app-publishing-api for Training environment

terraform/projects/app-content-store/README.md, terraform/projects/app-content-store/main.tf, terraform/projects/app-content-store/training.govuk.backend
Add backend to build app-content-store in the Training environment.
=> Update app-content-store for Training environment

terraform/projects/app-search/README.md, terraform/projects/app-search/main.tf, terraform/projects/app-search/training.govuk.backend
Add backend to build app-search in the Training environment.
=> Update app-search for Training environment

terraform/projects/infra-monitoring/secondary.tf
The aws terraform plugin version is now set to 1.60.0 in the main.tf and therefore all tf files in this project should be set to 1.60 to avoid mixing versions and causing an error.
1. set 1.40.0 in the secondary.tf file.
=> set terraform version to be the same as in main.tf i.e. 1.60

terraform/projects/app-whitehall-backend/main.tf
Looks like this was removed from other projects but
missed here... Removing now for consistency and to prevent
errors:
https://github.com/alphagov/govuk-aws/commit/50b8c7baf35fae6c7de63a46910575e6101934d4
=> Remove vpc_id variable from whitehall-backend module

doc/guides/deploying-google-terraform.md, terraform/projects/infra-google-mirror-bucket/prerequisites.md, terraform/projects/infra-google-mirror-bucket/production.govuk.backend, terraform/projects/infra-google-monitoring/production.govuk.backend
infra-google-mirror-bucket is now ready for production so we add the production backend to the project as well as the infra-google monitoring which is used to store bucket logs.
The google terraform deployment documentation is also updated.
1. add production backend definitions for infra-google monitoring and infra-google-mirror-bucket
2. update documentation for clarity
=> add backend for production version of infra-google-mirror-bucket

terraform/projects/app-whitehall-backend/README.md, terraform/projects/app-whitehall-backend/main.tf, terraform/projects/app-whitehall-backend/training.govuk.backend
Add backend to build app-whitehall-backend in the Training environment.
=> Update app-whitehall-backend for Training environment

terraform/projects/app-whitehall-frontend/README.md, terraform/projects/app-whitehall-frontend/main.tf, terraform/projects/app-whitehall-frontend/training.govuk.backend
Add backend to build app-whitehall-frontend in the Training environment.
=> Update app-whitehall-frontend for Training environment

terraform/projects/infra-mongodb-backup/README.md, terraform/projects/infra-mongodb-backup/integration.govuk.backend, terraform/projects/infra-mongodb-backup/main.tf, terraform/projects/infra-mongodb-backup/production.govuk.backend, terraform/projects/infra-mongodb-backup/staging.govuk.backend, terraform/projects/infra-mongodb-backup/templates/readwrite_policy.tpl
As a Reliability Engineer
I would like code for these AWS resources to exist in a current repo
So that I can make changes as expected, using an active repo.
These resources were initially created from a deprecated repo. To correct this
the code needed to be moved to the current repo, a new terraform state file 
created with an S3 backend, existing resources imported and a `terraform
apply` run to confirm what is essentially a no-op.
This has been tested and completed in staging but not yet in the other
environments.
solo: jstandring-gds
=> Move code from old deprecated repo for mongodb-backup buckets

terraform/projects/infra-public-services/main.tf
Route traffic to Cache apps based on Host header rules. Each rule uses
its own target port and health check path to ensure we only send traffic
to instances where the app is healthy.
=> Add Cache public ALB healthchecks

terraform/projects/app-draft-frontend/README.md, terraform/projects/app-draft-frontend/main.tf
Add new variable to main.tf to allow for a custom volume size.
One of the instances in the autoscaling group is running out of inodes
There doesn't seem to be anything significant we can delete, so we
are increasing the volume size.
=> Enlarge volume for app-draft-frontend instances

terraform/modules/aws/s3_bucket_lifecycle/README.md, terraform/modules/aws/s3_bucket_lifecycle/main.tf, terraform/projects/infra-s3-mirrors/main.tf
This module expects a logging bucket. To allow multiple things to log to the
same bucket a different prefix should be available. Currently this module is
only in use in one location and this commit includes the changes to the module
and the usage of that module.
=> Add target_prefix to module

terraform/projects/infra-datagovuk-organogram-bucket/main.tf
This will allow the staging environment to access the production organogram S3 bucket.
Trello card: https://trello.com/c/Vx11ucIl/1043-fix-display-of-organogram-visualisations-on-stagingdatagovuk
=> Allow staging env to access prod organogram bucket

terraform/projects/app-jumpbox/README.md, terraform/projects/app-jumpbox/main.tf, terraform/projects/infra-public-services/main.tf
We want to make the creation of the external ELB in the `app-jumpbox`
project optional. The `infra-public-services` project didn't have
any alarms for this same Jumpbox ELB , so that needs to be added too.
=> Make Jumpbox external ELB optional for Training

terraform/projects/app-email-alert-api/README.md, terraform/projects/app-email-alert-api/main.tf, terraform/projects/app-email-alert-api/training.govuk.backend
Add backend to build app-email-alert-api in the Training environment.
=> Update app-email-alert-api for Training environment

terraform/projects/app-mapit/README.md, terraform/projects/app-mapit/main.tf, terraform/projects/app-mapit/training.govuk.backend
Add backend to build app-mapit in the Training environment.
=> Update app-mapit for Training environment

terraform/projects/app-frontend/README.md, terraform/projects/app-frontend/main.tf, terraform/projects/app-frontend/training.govuk.backend
Add backend to build app-frontend in the Training environment.
=> Update app-frontend for Training environment

terraform/projects/app-monitoring/additional_policy.json
We want to start monitoring the number of healthy hosts on ELB/ELBv2
resources. The Icinga machine needs to be able to run Describe actions
to perform the check.
=> Add monitoring policy for ELBs

terraform/projects/infra-cyber-security-audit/main.tf
- The policies implemented for the original role did not work as
intended and required updating
- support:Describe* does not work as intended and had to be changed to
support:*
- Planned and applied cleanly in integration:
https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1483
https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1484
solo: @schmie
=> Update Cyber security audit role module

terraform/modules/aws/lb_listener_rules/README.md, terraform/modules/aws/lb_listener_rules/main.tf, terraform/projects/infra-public-services/main.tf
Update infra-public-services listener rules forempty ASGs:
In the Training environment, some of the ASGs don't exist yet. This was
causing an error when passing the parameter `autoscaling_group_name` to
the `_public_lb_rules` modules, because Terraform wasn't able to identify
the type of `names[0]` when the data resource returned no items.
The `aws_autoscaling_group` returns a single item instead of a list, which
is easier to evaluate to cover the cases when nothing is returned. We never
expect to have more than an ASG with a given name per environment, so both
data resources provide the same data.
The `rules_host_domain` in `backend_public_lb_rules` needs to remove the
environment variable in preparation for the deployment on Production, because
the Host headers are using the …
=> Fix empty public asg

terraform/projects/app-calculators-frontend/README.md, terraform/projects/app-calculators-frontend/main.tf, terraform/projects/app-calculators-frontend/training.govuk.backend
Add backend to build app-calculators-frontend in the Training environment.
=> Update app-calculators-frontend for Training environment

terraform/projects/app-calculators-frontend/main.tf, terraform/projects/app-draft-frontend/main.tf, terraform/projects/app-frontend/main.tf
We have applied the changes to enable the new ALBs on the frontend app
projects. The `instance_target_group_arns_length` and `instance_target_group_arns`
are actually irrelevant if the alb is enabled or disabled, because those
setting only attach the default group of the new ALB to the ASG.
Just in case we need to rollback the change, it's actually easier to
understand the plan, if the only relevant change when setting `enable_alb`
to false is a change in the DNS record ALIAS value to point to the original
ELB.
For these reasons we are going to update the code and always do the
attachment of the ALB default group.
=> Update enable_alb implementation in frontend apps

terraform/projects/infra-mirror-bucket/pingdom_probe_ips.sh
Update the pingdom script so that it is the same as the one in `terraform/projects/infra-s3-mirrors/pingdom_probe_ips.sh` which has been fixed previously.
1. change `pingdom_probe_ips.sh` of infra-mirror-bucket to match that of infra-s3-mirrors
=> fix the pingdom script which retrives pingdom IPs for S3 access policy

terraform/projects/app-publishing-api-db-admin/README.md, terraform/projects/app-publishing-api-db-admin/main.tf, terraform/projects/app-publishing-api-db-admin/training.govuk.backend
Add backend to build app-publishing-api-db-admin in the Training environment.
=> Update app-publishing-api-db-admin for Training environment

terraform/projects/app-mongo-api/README.md, terraform/projects/app-mongo-api/main.tf, terraform/projects/app-mongo-api/training.govuk.backend
Add backend to build app-mongo-api in the Training environment.
=> Update app-mongo-api for Training environment

terraform/projects/app-email-alert-api-db-admin/README.md, terraform/projects/app-email-alert-api-db-admin/main.tf, terraform/projects/app-email-alert-api-db-admin/training.govuk.backend
Add backend to build app-email-alert-api-db-admin in the Training environment.
=> Update app-email-alert-api-db-admin for Training environment

terraform/projects/app-cache/README.md, terraform/projects/app-cache/main.tf, terraform/projects/app-cache/training.govuk.backend
Add backend to build app-cache in the Training environment.
=> Update app-cache for Training environment

terraform/projects/app-backend/README.md, terraform/projects/app-backend/main.tf, terraform/projects/app-backend/training.govuk.backend
Add backend to build app-backend in the Training environment.
=> Update app-backend for Training environment

terraform/projects/app-mongo/main.tf
The Mongo machines in the Training environment need read access to
the Mongo backups Integration S3 bucket for the data sync to work.
This change allow that.
=> Add Mongo Read Policy for Training Data Sync

terraform/projects/app-backend/main.tf
One of the instances in the autoscaling group is running out of space
There doesn't seem to be anything significant we can delete, so we
are increasing the volume size.
=> Enlarge volume for app-backend instances

terraform/projects/app-calculators-frontend/main.tf
This prevents Terraform reporting that an unnecessary change needs
to be made to the CNAME. AWS automatically adds a dot to the end of
a CNAME if none exists.
=> Add Dot to End of CNAME Record for Consistency

terraform/projects/app-related-links/main.tf
This PR upgrades the instance type used for related links generation in the `app-related-links` project from `m5.2xlarge` to `m5.4xlarge`. An `m5.4xlarge` was used during development for the testing of the related links algorithm and it was thought that a downgrade might be possible to a lesser instance type, however this has been proven false so reverting back to the original instance type.
=> Upgrade instance type for app-related-links generation instance

terraform/projects/infra-mirror-bucket/README.md, terraform/projects/infra-mirror-bucket/main.tf, terraform/projects/infra-mirror-bucket/mirror-read-policy.tf
We want to be able to switch to a secondary CDN provider in case our
primary one is having issues. Here we are creating a new CloudFront
distribution able to serve the content in the primary S3 mirror bucket.
=> Add Mirror Cloudfront configuration

terraform/projects/infra-mirror-bucket/main.tf
The default_root_object setting in the Assets Cloudfront distribution is
not required because we always request specific objects. We can remove
the setting from the configuration.
=> Assets Cloudfront distribution remove default_root_object

terraform/projects/infra-mirror-bucket/main.tf
We are seeing this error:
```
aws_cloudfront_distribution...._distribution: error updating CloudFront Distribution
InvalidArgument: The parameter Logging Bucket does not refer to a valid S3 bucket.
```
The `bucket` setting needs to be the bucket domain.
https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#logging-config-arguments
=> Cloudfront fix logging settings

terraform/projects/infra-mirror-bucket/README.md, terraform/projects/infra-mirror-bucket/main.tf, terraform/projects/infra-mirror-bucket/mirror-read-policy.tf
We are going to run Smokey tests from our platform, that require
read access to the content in the mirror buckets. Outbound traffic uses
NAT gateways, we can use infra-networking state to retrieve the list of
NAT ip addresses to whitelist.
=> Enable read access to mirror buckets from NAT IPs

terraform/projects/infra-dev_vm/README.md, terraform/projects/infra-dev_vm/main.tf, terraform/projects/infra-dev_vm/policy.tf, terraform/projects/infra-dev_vm/test.govuk.backend
Migrate `dev_vm` to this repository:
https://github.com/alphagov/govuk-terraform-provisioning/tree/master/old-projects/dev_vm
=> Migrate dev_vm project from govuk-terraform-provisioning

terraform/projects/infra-security-groups/backend-redis.tf
This is needed for the emergency banner to work in the draft environment. Without it, static returns a 500 error when trying to render a page.
=> Allow draft-frontend to talk to backend-redis

terraform/projects/infra-public-services/main.tf, terraform/projects/infra-public-services/waf.tf
adds an example acl rule that blocks requests containing an
`X-Always-Block: true` header and associates it with the public cache alb.
so that we have an entrypoint for addiing web acl rules if required
https://github.com/alphagov/smokey/pull/564
=> adds an example web acl rule to the cache alb

terraform/projects/infra-artefact-bucket/main.tf
This is required to maintain idempotency when doing terraform plan and no changes are expected.
=> add ID to replication rule for artefact bucket

.gitignore, terraform/lambda/WAFLogTrimmer/README.md, terraform/lambda/WAFLogTrimmer/lambda.js, terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-public-services/waf.tf
Adds a firehose for forwarding web acl logs to splunk and wires up the
"default" ACL to test shipping is working as expected
WAF ACL Logs -> Firehose -> WAFLogTrimmer() -> Splunk
We add a lambda function to trim any logs that are not an explicit ALLOW or BLOCK (ie we do not want every single gov.uk request in this log index, we only want things that have matched an ACL).
long term cyber will be collecting all these kinds of logs for threat
intelligence and will be doing it by exposing a cross-account firehose
destination that we could ship directly to. However at time of writing
this method is not quite ready for prime-time and so we are deploying a
firehose that will ship directly to splunk
The cyber managed Splunk instance  will ingest the logs and make them
available both to GOV.UK …
=> adds waf log shipping to splunk

terraform/projects/infra-public-services/waf.tf, terraform/projects/infra-public-services/waf_sqli_rule.tf, terraform/projects/infra-public-services/waf_test_rule.tf, terraform/projects/infra-public-services/waf_xss_rule.tf
Adds rules to the `default` web application firewall ACL (connected to the frontend/cache load balancer) that:
* Attempts to detect SQL injection attempts in cookies/querystrings/uris/body of requests
* Attempts to detect Cross Site Scripting attempts in cookies/querystrings/uris/body of requests
The rules are currently marked to `ALLOW` so will not affect traffic.
The rules have been broken out into their own tf flies to make them easier to maintain.
So that we can monitor the impact these rules will have against the production traffic before moving into `BLOCK` mode to gain the basic protection these rules will provide against these extremely common attack vectors.
Once deployed matched requests can be viewed either from Splunk or from the AWS console.
=> Adds SQLInjection and XSS application firewall rules in ALLOW mode

terraform/projects/infra-public-services/main.tf
the "default" web ACL provides basic detection of potentially malicious
XSS/SQLi requests, and is currently assigned to the public frontend
cache ALB.
In the future we wish to protect the backend/whitehall apps behind
similar rules too, but these are not yet on the AWS side of the bridge.
To prepare for any false positives and to begin evaluating the impact of the ACL on the backend/whitehall applications we associate the default rule to the ALBs in front of these application in the integration environment in AWS.
=> adds "default" web ACL to backend/whitehall ALBs

terraform/projects/infra-public-services/main.tf
GDS have purchased AWS Shield Advanced which provides us with extended
support/protection against layer 3/4 attacks.
This marks the public cache ALB (frontend) as a "protected resource"
under the scheme.
=> enable shield advanced protection of cache ALB

terraform/projects/fastly-datagovuk/datagovuk.vcl, terraform/projects/fastly-datagovuk/datagovuk.vcl.tmp, terraform/projects/fastly-datagovuk/datagovuk.vcle, terraform/projects/fastly-datagovuk/fastly.sh, terraform/projects/fastly-datagovuk/main.tf
The fastly vcl `datagovuk.vcl` was static but fastly IPs do change with time. We therefore make the vcl `datagovuk.vcl` dynamic by using a template `datagovuk.vcl.tmp` which is then filled in at terraform `apply`/`plan` time.
The template `datagovuk.vcl.tmp` is filled by using a terraform external data source which runs a bash script `fastly.sh`. `fastly.sh` makes a query to fastly to get the latest fastly subnets and then uses these values to insert into the `datagovuk.vcl.tmp` to make the `datagovuk.vcl`.
In addition, there was a need to replace the condition type from `request` to `REQUEST` because of a change in fastly accepted types.
----
@schmie:
Frederic is OOO for the next week due to a family commitment, so I am taking over this PR.
Tested the branch in integration and added a …
=> Make fastly vcl `datagovuk.vcl` customisable for fastly IPs

terraform/projects/app-documentdb/README.md, terraform/projects/app-documentdb/main.tf
This was used in app-mongo, but does not appear to be needed here. We are going to
connect using the AWS generated domain name. If we add the CNAME back later we will
need to generate a certificate for it.
=> Remove DocumentDB CNAME

terraform/projects/infra-security-groups/documentdb.tf
This is needed for migrating the router app from Mongo to
DocumentDB. Both these machines need to communicate with
the DocumentDB cluster.
=> Give Cache and Router-Backend Machines Access To DocumentDB Cluster

terraform/projects/infra-security-groups/documentdb.tf
This is needed so the router and router-api apps can
communicate with the new DocumentDB cluster.
=> Allow Draft-Cache Machine to Access DocumentDB Cluster

terraform/projects/app-licensify-backend/main.tf, terraform/projects/app-licensify-frontend/main.tf, terraform/projects/infra-public-services/main.tf
These are the same paths as currently used by the Icinga healthchecks.
`licensify-frontend` serves both the frontend UI and the `uploadlicense`
service. There is therefore one target group and one healthcheck for
`licensify-frontend`. In other words, we are treating the app instance
as the failure domain for the purpose of LB healthchecking.
`licensify-feed` is not load-balanced (because it's a single-master,
manual-failover architecture).
=> Set load balancer healthcheck paths for Licensify.

terraform/projects/infra-security-groups/documentdb.tf
Added to ensure that AWS Database Migration Service
will work with MongoDB on the router-backend machines in
future.
=> Allow Resources in Mongo Security Group to Access Themselves

terraform/projects/app-licensify-backend/README.md, terraform/projects/app-licensify-backend/main.tf
licensify-feed requires a single master instance. Failover to a
non-master instance requires a manual config change. In AWS, since we
have automated deployments, it is quicker to let the failed instance
be recycled by the autoscaler than to make the manual config change to
swap the master over.
For now, we therefore plan to put up with running a single instance of the
backend VM (which runs licensify-feed and licensify-admin). If need be,
we could do further work to separate out licensify-admin so that it can
have two instances.
=> Don't try to run two master instances of licensify-feed.

terraform/projects/app-bouncer/README.md, terraform/projects/app-bouncer/main.tf
In Production, only ~1.3GB of memory is being used on these machines,
and the CPU's don't look particularly pressured either, so I think a
smaller instance type is better suited. A t3.medium would probably
work, but I've chosen to just step it down gradually at the moment.
=> Downsize the bouncer machines to a t3.large by default

terraform/projects/app-licensify-backend/main.tf, terraform/projects/app-licensify-frontend/main.tf
This is to match what we currently have in Carrenza / UKCloud.
=> Increase root volume size on Licensify VMs from 20 to 50 GB.

terraform/projects/app-licensify-documentdb/README.md, terraform/projects/app-licensify-documentdb/main.tf
Companion PR which sets these variables: https://github.com/alphagov/govuk-aws-data/pull/553
No diffs from Terraform plan in Integration: https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2014/console
=> Add vars for configuring TLS and snapshot retention on Licensify DocDB.

terraform/modules/aws/lb/main.tf
This change means that more target groups have proper names, rather
than the Terraform defaults. I've been looking at bouncer, so this
change means that instead of something like
tf-20181031151047476700000001, you get blue-bouncer-internal-HTTP-80.
=> Give the lb module target groups better names

terraform/projects/app-rabbitmq/README.md, terraform/projects/app-rabbitmq/additional_policy.json, terraform/projects/app-rabbitmq/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/rabbitmq.tf, terraform/projects/infra-security-groups/variables.tf, terraform/userdata/10-associate-eni
For the AWS migration we create a federation from Carrenza.
This make the federation going both ways, services should then be
able to use rabbitmq from carremza or AWS.
=> Federate rabbitmq from Carrenza

terraform/projects/app-db-admin/main.tf, terraform/projects/infra-database-backups-bucket/main.tf, terraform/projects/infra-database-backups-bucket/reader.tf, terraform/projects/infra-database-backups-bucket/writer.tf
The permissions should be as followed for db_admin in:
1. integration: read integration, staging and production & write integration
2. staging: read staging and production & write staging
2. production: read none & write production
=> fix licensify s3 permissions

terraform/projects/infra-carrenza-vpn/main.tf
We now use the govuk_reserved_ips_private subnet to host the
additional interfaces we need to create a rabbitmq federation from
carrenza to AWS for the migration of publishing API to AWS.
=> Add vpn route propagation to govuk_reserved_ips_private subnets

terraform/modules/aws/lb/main.tf
This means that Terraform will create replacement target groups prior
to deleting the old ones. This avoids trying to delete target groups
when they're still used by the listener.
=> Create load balancer target groups before destroying

terraform/projects/infra-public-services/main.tf
Enable the AWS web application firewall for licensify-admin.
=> Enable WAF for Licensing backend (licensify-admin).

terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/licensify-backend.tf
This already exists in UKCloud (on the licensify_lb nginx) and we need
to preserve the behaviour when migrating to AWS. The HTTPS redirect is
essential in rare cases, because HSTS preload cannot be relied upon
universally.
We add an ALB listener on port 80 with a default rule which serves
redirects to the same URL but with the https protocol. This way we don't
have to allow any HTTP traffic to be forwarded to the backend and we
keep the backend nginx config simple.
While we're there, also remove some superfluous entries from the ingress
ACL for the public LB. (It already allows port 443 from any source, so
it's not helpful to also list the office IP addresses in that rule. This was
copied from whitehall-admin I believe.)
=> Add HTTP->HTTPS redirect at the LB for licensify-admin.

terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/licensify-frontend.tf, terraform/projects/infra-security-groups/main.tf
As part of the AWS migration of licensify, review the security groups linked with licensify frontend.
1. allow licensify frontend internal load balancer to access the
licensify frontend hosts
2. for production environment, allow any IP to access the
licensify frontend external load balancer. For integration and
staging, this should be closed to only office IPs so far
3. add a http/80 listener on licensify frontend external load
balancer to redirect to https/443
4. enable waf on the licensify frontend external load balancer
=> modifying security groups and load balancers for licensify-frontend

terraform/projects/app-gatling/README.md, terraform/projects/app-gatling/main.tf
Changes to 2 instances, both `m5.2xlarge`, for increased load testing power
[Trello](https://trello.com/c/PKUKehXX/1241-3-investigate-having-2-clustered-gatling-machines)
=> Add additional gatling instance and increase machine size

terraform/projects/app-related-links/README.md, terraform/projects/app-related-links/main.tf
This commit places `aws_iam_policy_attachment`s with `aws_iam_role_policy_attachment`s, as the former only allows a policy to be associated with one role exclusively across projects.
From the Terraform docs:
_The aws_iam_policy_attachment resource creates exclusive attachments of IAM policies. Across the entire AWS account, all of the users/roles/groups to which a single policy is attached must be declared by a single aws_iam_policy_attachment resource._
See https://www.terraform.io/docs/providers/aws/r/iam_policy_attachment.html for more info.
Secondly, this commit adds the ARNs of policies `read_content_store_backups_bucket_policy` and `read_write_related_links_bucket_policy` as outputs, so that they can be reused by the upcoming knowledge-graph project.
=> Use aws_iam_role_policy_attachment for related link roles

terraform/projects/app-gatling/README.md, terraform/projects/app-gatling/main.tf
This bucket can be used to store Gatling load testing results for a longer period of time, as currently the results get wiped whenever we need to reprovision the machine.
It's configured to allow static website access from office IP addresses meaning we can view the results directly either in the office or by using the VPN rather than having to download them first.
[Trello Card](https://trello.com/c/Juuu8OvE/1251-5-host-the-gatling-reports-graphs-somewhere)
=> Add an S3 bucket to store Gatling results

terraform/projects/app-search/main.tf, terraform/projects/infra-public-services/main.tf
This makes two changes, I'm not sure if both are necessary.
1. Change the ELB healthcheck to check for `/_healthcheck_search-api` over HTTP.  This means that requests will not be sent to an instance until the search-api healthcheck is passing.  This is fine, as search-api is the only app on the app-search machines.
2. Uses per-app healthchecks for external DNS - which is what Carrenza things (whitehall, search-admin) use to communicate with search-api.  I don't know if this is necessary with (1) in place.
I think we could use per-app healthchecks for internal DNS as well (rather than doing (1)), but I think that would require more restructuring, to set up a search-api ALB.
Plans:
- [app-search](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2217/cons …
=> Use search-api healthcheck, rather than nginx healthcheck

terraform/projects/app-licensify-backend/production.blue.backend, terraform/projects/app-licensify-backend/staging.blue.backend
As part of the migration of licensify to AWS
=> Add backends for staging and production for app-licensify-backend

tools/deploy.rb
In the deploy.rb script. This means you can run the script without
using the `govukcli`, for example by using the `gds-cli`:
`gds aws govuk-integration-internal-admin -- ruby ./tools/deploy.rb plan integration blue app-backend`
=> Support using the AWS credentials from the environment

terraform/projects/app-whitehall-backend/README.md, terraform/projects/app-whitehall-backend/main.tf, terraform/projects/infra-public-services/main.tf
This replaces the Classic ELBs for `whitehall-admin` with ALBs and
uses the healthcheck which goes through to the application instead of
the generic nginx healthcheck which succeeds even when the app is not
running.
The healthcheck and ALB setup is described in
https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0037-alb-health-checks.md
We also remove some unused domain names which refer to
`whitehall_backend`. Nothing is configured to serve traffic for these
hostnames, so their existence only leads to confusion and surprise.
=> Fix and clean up load balancer configs for whitehall-admin.

terraform/projects/infra-security/main.tf
The permissions were already removed from these buckets in
https://github.com/alphagov/govuk-aws/pull/1070.
=> Delete duplicate S3 buckets for CloudTrail.

terraform/projects/infra-security-groups/postgresql.tf
This commit adds a new ingress rule for the `knowledge-graph` SG to access the PostgreSQL `primary` node (in integration) for the purposes of querying the Publishing API database directly. We run this query at present to generate a dataset of people and of roles, which we're experimenting with to improve the Knowledge Graph and the use cases we're testing off the back of it.
This change is temporary (for the lifetime of the Knowledge Graph), after which if we move forward with a knowledge graph then we will do so from the ground-up and not necessarily productionise what we already have in integration at present.
Trello: https://trello.com/c/jXF0o7bT
=> Add ingress rule for Knowledge Graph SG to access PostgreSQL

terraform/projects/app-elasticsearch6/main.tf
The same role is used by ES5 and ES6, so we need to move the config and import it.
=> Move ES service role config to app-elasticsearch6

terraform/projects/app-whitehall-backend/main.tf
This fixes a mistake in #1119. I failed to notice that the internal
names for whitehall-admin are created in infra-public-services.
=> Remove duplicate DNS record for whitehall-admin.

terraform/projects/infra-fastly-logs/main.tf
Setting a lifecycle policy to ensure we honour our privacy policy correctly.
[Trello](https://trello.com/c/UBvLjmWy/1304-5-set-lifecycle-policy-of-30-days-on-s3-buckets-with-logs)
=> Review s3 lifecycle policy

terraform/projects/app-knowledge-graph/main.tf
This PR adds missing SSM parameters to the `knowledge-graph_read_ssm_policy_document` policy for querying BigQuery to create the functional network and querying Publishing API to build the people / roles dataset.
=> Add missing SSM parameters to Knowledge Graph policy

tools/deploy.rb
- Using this to deploy some infra-security changes in all the
environments got tedious as I had to left-arrow scroll all the way to
the beginning of the arguments every time (or use ^plan^apply) to change
"plan" to "apply", and the same for the environment across all of
them.
- Move the more frequently changed arguments to the end to save time
scrolling.
=> Order the tools/deploy.rb arguments by least to most changed

terraform/projects/infra-monitoring/main.tf, terraform/projects/infra-monitoring/secondary.tf
The intention of setting the prefix to "/" was to apply to all objects but S3 object keys don't start with a / so the rule ends up applying to no objects. The prefix field is optional and removing it means the lifecycle rule will apply to the entire bucket.
=> Remove prefix from lifecycle_rule

terraform/projects/app-gatling/README.md, terraform/projects/app-gatling/main.tf
No longer needed for load testing and having those instances is causing an
unknown "At least 1 machine requires reboots due to apt updates" alert in
icinga because they don't have a govuk_safe_to_reboot value specified.
=> Remove gatling instances

terraform/modules/aws/node_group/README.md, terraform/modules/aws/node_group/main.tf, terraform/projects/app-mapit/README.md, terraform/projects/app-mapit/additional_policy.json, terraform/projects/app-mapit/main.tf, terraform/userdata/05-tag-mapit-volume
When autoscaling, new Mapit instances are currenly not created with new EBS volumes.
This is the present state of the mapit machines:
There are two autoscaling groups each containing only one instance. If this singular instance
is terminated, a new one is launched without an EBS volume to take it’s place. Then the old EBS
volume is attached to the new node (the EBS volume contains the database for the postcode lookup).
There are two problems with the current setup:
1. The service cannot be scaled up. The current set up relies on a the single instance being
terminated so that the new instance can use the old/original volume.
2. Any new nodes that are launched are currently unhealthy and require manual intervention to
make them work. This is caused by a Postgres issue. If Postgres detects …
=> Ensure New Mapit Nodes Are Healthy

tools/bulk-plan.rb
The `tools/deploy.rb` script allows more easily running Terraform for
a single project, but what if you want to potentially apply changes to
more than one project. Also, if you want to find out what unapplied
Terraform changes there are, how would you do that?
This script aims to meet those needs, it automates taking one or more
projects and running the `tools/deploy.rb` script for those
projects (taking in to account the stacks for the environment).
It's limited to running Terraform to plan, as I don't think it's
sensible to apply in bulk, that should only be done on a project by
project basis. Planning is safe to do in bulk, as it's just inspecting
the state of the infrastructure.
=> Add tools/bulk-plan.rb

terraform/projects/app-db-admin/elasticache_policy.json, terraform/projects/app-db-admin/main.tf
As part of the incident review to test the resilience of apps with respect to the reboot of redis cluster, we add the necessary iam permissions for the db_admin machines in AWS integration to trigger the reboot of the redis cluster.
1. add the iam policy to the db_admin to describe and reboot elasticache clusters
Additional [PR](https://github.com/alphagov/govuk-puppet/pull/9668) where a cron job is added to the db_admin machines in AWS Integration to describe and reboot the redis elasticache
=> add elasticache reboot rights for db-admin

terraform/projects/app-publishing-api/main.tf
This switches the load balancer healthchecks for publishing-api from TCP
healthchecks (which only test the nginx proxy) to HTTP healthchecks
which are routed through to the app instance.
This is in line with ADR 37: https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0037-alb-health-checks.md
Co-authored-by: Camille Descartes <camille.descartes@digital.cabinet-office.gov.uk>
=> Change publishing-api ELB healthchecks to hit the app, not the nginx.

terraform/projects/infra-security-groups/publishing-api.tf
This allows traffic from the 6DG egress addresses into the
external-facing Classic ELB for Publishing API in AWS.
This is a prerequisite for migrating Publishing API to AWS.
=> Allow apps in Carrenza/6DG to talk to Publishing API in AWS.

terraform/projects/app-postgresql/main.tf
We have seen postgres primary in AWS integration
run out of memory during the data sync from production
Although integration and production have the same
allocated storage (the lowest at 190 GB), integration
uses substantially more. This is because some dbs in
production don't use AWS yet.
This change increases the allocated storage to 209 GB,
the next lowest available.
It makes the increase across all environments. At the
moment production is hugely overprovisioned (and this
adds an extra 19GB). Let me know if we don't want this
extra storage on production. This will be an extra
~$2.50 per instance per environment per month ($5 total).
=> Increase storage allocated to postgres RDS instances

terraform/policies/s3_govuk_aws_logging_replication_policy.tpl, terraform/policies/s3_govuk_aws_logging_replication_role.tpl, terraform/projects/infra-monitoring/README.md, terraform/projects/infra-monitoring/main.tf
As part of an incident action, there is a need to replicate the logs of the ckan public elb into the cyber s3 bucket for processing by splunk.
It should be noted that the replication rule is only enabled for the production stack as Cyber is only interested in that. Unfortunately, the way that terraform 0.11.x works is we can't set a count for an nested resource. Hence, the replication rule is created for all environments but only enabled for the production environment.
In addition, we set the version to enabled as replication requires that. This would not have effect on the size of the s3 bucket because AWS writes new log files with new timestamp as the part of the file name so each log files is unique.
data component of this PR: https://github.com/alphagov/govuk-aws-data/pull/599
=> replicate ckan elb s3 logs to cyber s3 bucket

terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/main.tf, terraform/projects/infra-database-backups-bucket/reader.tf
The govuk-integration-database-backups S3 Bucket has over 30TB of
data in it. As we do not need long term backups of Integration
databases this PR reduces the time they are stored for
(from 30 days to 3). This PR also disables Glacier Backups
in Integration. To do this, two new lifecycle rules have been added.
They will be created in all environments, but only enabled in Integration.
=> Reduce Storage Time of S3 Database Backups in Integration

terraform/projects/infra-database-backups-bucket/main.tf
This PR adds a new lifecycle rule for mysql backups (this was missing from the original commit).
This PR also changes the expiration values back to hardcoded ones to prevent the following error,
which was seen when applying terraform ( AWS requires the expiration value to be
greater than a transition value in a lifecyle rule, even if the rule is disabled ):
"aws_s3_bucket.database_backups: Error putting S3 lifecycle: InvalidArgument: 'Days' in the Expiration action for filter '(prefix=mysql/)' must be greater than 'Days' in the Transition action"
=> Amend S3 Storage Reduction

terraform/projects/app-knowledge-graph/main.tf, terraform/projects/app-knowledge-graph/userdata.tpl
This PR passes the data infrastructure bucket name as a parameter to the Knowledge Graph provisioning script, which will be used to store data generated as part of the graph provisioning on a daily basis.
=> Pass data bucket name to provisioning script

terraform/projects/app-email-alert-api/README.md, terraform/projects/app-email-alert-api/main.tf, terraform/projects/infra-public-services/main.tf
Load balancer healthchecks for email-alert-api were checking the default
vhost config on the nginx instead of being routed through to the app
itself. (See https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0037-alb-health-checks.md)
Also remove the external-facing Classic ELB since this has never been used.
Now is a good time to clean this up, before we migrate Staging and Production
email-alert-api to AWS.
=> Fix email-alert-api LB healthchecks and remove disused ELB.

terraform/projects/app-knowledge-graph/main.tf
This PR updates the knowledge graph scheduled action start times, which control when the instance is spin up and spun down. This is necessary to maintain the current availability of the knowledge graph given the recent switch from BST to GMT.
=> Update knowledge graph scheduled action start times

terraform/projects/infra-database-backups-bucket/main.tf
Add Lifecycle Rule to entire "govuk-integration-database-backups" S3
bucket that deletes any objects that are not matched by more specific
rules after 3 days.
=> Delete Objects In Integration Backups Bucket After 3 Days

terraform/projects/app-calculators-frontend/README.md, terraform/projects/app-calculators-frontend/main.tf
- Brexit is delayed, so we're restoring to pre-spike ASG sizings.
- The pre-spike production instance size was 4, defined in
`govuk-aws-data` for each environment. Let's bump the default down to
4 for fewer lines of code to have to find to do things consistently.
https://trello.com/c/Ndw3s8Jj/1502-2-reduce-number-of-machines-to-pre-brexit-resilience-levels
=> Set default ASG size to 4 for calculators_frontend instances

tools/deploy.rb
- It's good if people watch what their commands do, without having to
think hard about which Jenkins this uses.
=> Terraform deploy script: Add a link to the Jenkins job

terraform/projects/app-router-backend/main.tf
Load balancer healthchecks for router-api were checking the default
vhost config on the nginx instead of being routed through to the app
itself.
See https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0037-alb-health-checks.md
=> Fix router-api LB healthchecks to check the app itself.

terraform/projects/app-developer-docs/README.md, terraform/projects/app-developer-docs/main.tf, terraform/projects/app-developer-docs/production.govuk.backend, terraform/projects/app-developer-docs/templates/read_write_user.tpl
- These should live here as they're currently used.
No idea if this works, but raising for visibility.
=> Import the govuk-developer-docs resources from the old Terraform repo

terraform/projects/infra-security-groups/elasticsearch6.tf
[Trello card](https://trello.com/c/P5Zs7zIg/1148-use-correct-elasticsearch-host-header)
=> Allow https ingress to Elasticsearch

terraform/projects/app-shared-documentdb/main.tf
Reverts alphagov/govuk-aws#1173 because it is safer to not apply changes immediately but we want to temporarily apply the password immediately.
=> Revert "apply changes immediately for shared-documentdb"

terraform/projects/infra-artefact-bucket/README.md, terraform/projects/infra-artefact-bucket/main.tf, terraform/projects/infra-content-publisher/README.md, terraform/projects/infra-content-publisher/main.tf
Disable replication of the govuk-integration-content-publisher-activestorage
S3 bucket, as it is not needed.
Disable replication of the govuk-integration-artefact S3 bucket, as it is not
needed.
Add lifecycle rules to buckets to ensure old objects are permanently deleted.
=> Disable Unnecessary Replication in Integration for S3 Buckets To Save Costs

terraform/projects/infra-artefact-bucket/main.tf
This setting was present in all environments but was not present in
the terraform code. The role appears to be essential.
=> Add Role To Policy Attachment / Update Terraform Code To Match Present State of AWS

terraform/projects/app-calculators-frontend/README.md, terraform/projects/app-calculators-frontend/main.tf
As we're seeing high CPU usage for Finder Frontend, so we probably
could do with a bit of extra capacity.
=> Add an extra calculators_frontend machine

terraform/projects/infra-fastly-logs/main.tf
- The pre-existing `cache_hit` column's description was incorrect, so
fix it.
- We want to find out which paths are served from the cache and how.
This includes more Fastly-specific variables as per
https://docs.fastly.com/en/guides/useful-variables-to-log#cache-related-logging-variables.
https://trello.com/c/FZoxuRQ5/1536-3-log-to-athena-whether-a-request-was-served-from-cache
=> InfraFastlyLogs: Add a `cache_response` log column

tools/govukcli
- As part of the working group on developer tooling, and as part of an
ongoing approach to standardize tooling and make things more secure and
better for new people joining GOV.UK, we are standardising on the GDS
CLI for *AWS*-related tasks (signing into the Console, generating
access keys for Terraform runs, etc).
- It's a CLI that's developed by RE and is secure in its approach to
dealing with AWS credentials. It's substantially less code for *us* to
maintain, and doesn't involve copying and pasting credentials into
`~/.aws/config` and `~/.aws/credentials` files as part of an
onboarding process. Credential rotation is also easier in the event of
a compromise.
- We don't anticipate this to cause much friction (famous last words)
given that most developers on GOV.UK don't interact with …
=> Deprecate `govukcli aws` functionality and signpost users to the GDS CLI

terraform/projects/app-knowledge-graph/main.tf, terraform/projects/app-knowledge-graph/userdata.tpl, terraform/projects/infra-security-groups/knowledge-graph.tf
This PR adds support for the journey visualisation tool, hosted as part of the knowledge graph and using it to power searches of analytics between content pages. 
Specifically, this PR adds new rules to the knowledge graph SG and knowledge graph ELB SG, in addition to calling a new script within userdata to start the tool.
This PR also makes a small change to the ASG scheduled actions to ensure that we continue to generate base data at weekends.
=> Add support for journey visualisation tool

tools/deploy.rb
- This stops us falling back to the now deprecated and non-functional
`govukcli aws` commands in the event of missing envvars.
- The developer docs have been updated with instructions for how we run
this in the new `gds-cli`-shaped world.
=> tools/deploy: Remove references to deprecated `govukcli aws` commands

terraform/projects/infra-security/main.tf
This police is for attaching to a role to allow 2ndline users to rotate IAM Access Keys.
=> Policy to Allow Users to Rotate IAM AccessKeys

terraform/projects/infra-security-groups/ckan.tf, terraform/projects/infra-security-groups/email-alert-api.tf
Grants SSH access to ckan and email-alert-api boxes when `ithc_access_ips` is defined. Applying https://github.com/alphagov/govuk-aws/pull/1047 to more machines.
=> Allow ITHC access to CKAN and Email Alert

terraform/projects/infra-mirror-bucket/main.tf, terraform/projects/infra-public-services/waf.tf
The `nodejs8.10` runtime reaches end of life on Dec 31.
=> Update Node.js lambdas to the nodejs10.x runtime.

terraform/projects/app-knowledge-graph/main.tf
This PR updates the Knowledge Graph SSM policy to read the HTTPS endpoint. This is used when rendering the custom GOV.UK guide on the Neo4j start page.
=> Update Knowledge Graph SSM policy to read HTTPS endpoint

terraform/projects/app-email-alert-api/main.tf, terraform/projects/app-publishing-api/main.tf
Make these match what's in Carrenza. We don't want the migration to
increase the risk of running out of disk space.
=> Increase AWS root volumes for email-alert-api/publishing-api.

terraform/projects/app-graphite/main.tf
This is to support the monitoring machine having access to Grafana's
API as part of a new alert about dashboards.
https://github.com/alphagov/govuk-puppet/pull/9894
=> Add internal DNS record Grafana

terraform/projects/app-knowledge-graph/userdata.tpl
This PR moves the `csvkit` install to happen inside the Python virtualenv. It isn't needed by anything other than the Python build scripts and a recent dependency chain change has broken the installation of this package on the machine itself.
=> Move csvkit install to happen inside Python virtualenv

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
This PR adds a new role `govuk-datascienceusers` to allow data scientists to assume access integration. This role has the same level of access as govuk-users, but with additional permissions to create, update and delete resources in AWS Glue (related to jobs for running ETL on our databases) and AWS SageMaker (related to Jupyter notebook instances for experimentation).
We plan to test the new role with data scientists to ensure that it provides them with access to everything they need, specifically within AWS Glue and AWS SageMaker, so it is likely that we will be amending the associated policies once we know any additional permissions that are required.
=> Add policies for data science access

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
Unfortunately licensify-admin has some clients which don't support SNI and can't upgrade yet. This allows them to continue working for now.
Using the combined cert is less messy that swapping the primary and secondary certs.
=> Use combined TLS cert for licensify-admin, to work with non-SNI clients.

terraform/projects/app-asset-master/main.tf, terraform/projects/app-whitehall-backend/main.tf, terraform/projects/app-whitehall-frontend/main.tf
We don't want to introduce unnecessary risk to the AWS migration by shrinking resources at the same time.
=> Increase root volume sizes to match Carrenza for Whitehall/Assets.

terraform/projects/infra-fastly-logs/main.tf
- We need to temporarily keep more logs.
=> Bump the Fastly logs S3 bucket retention period

terraform/projects/app-mysql/README.md, terraform/projects/app-mysql/main.tf
Amazon recommends at least 100 GB of allocated storage when using
General Purpose IOPS, otherwise the I/O will be underprovisioned. Since
we're about to migrate Whitehall to this RDS deployment, we want to
avoid any potential performance issues.
Also enable autoscaling up to 800 GB (the same limit that we have for
the Postgres RDS instances). This reduces the risk of running out of
space and reduces unnecessary work in managing the storage allocation
manually.
Fix the `replica` instance so that it has the same allocated storage as
the primary. Previously this was erroneously set to 10 GB and would have
failed if the Terraform had been applied.
=> Increase MySQL RDS storage to recommended minimum and auto-scale.

terraform/projects/app-mysql/README.md, terraform/projects/app-mysql/main.tf
`m5`s provide better performance for slightly less money. Doing this
before the Whitehall migration is easier than doing it after.
Changing the default rather than overriding per environment because
we'll be upgrading all the environments within a day or so.
=> Upgrade MySQL RDS instances from m4 to m5.

terraform/projects/app-email-alert-api/README.md, terraform/projects/app-email-alert-api/main.tf
From m5.large machines. Before the migration to AWS, the 3 machines in
Carrenza had 8 cores. The m5.large machines just have 2, so double the
number of cores to 4 as we're seeing high load on the machines when
lots of delivery receipts are being received from Notify.
=> Bump the email-alert-api machines to m5.xlarge

pipeline.yml
- Follows on from #1200.
- Homebrew [released version 2.2.2](https://github.com/Homebrew/brew/releases/tag/2.2.2), so Concourse containers can now run as root without needing the hacky `sed` and associated environment variables.
=> Remove `sed` hacks in the Concourse pipeline

terraform/projects/app-search/main.tf
The actual endpoint won't be managed by terraform so, rather than have
names in three places which need to be kept in sync (sagemaker
management code in concourse, search-api config, terraform), just
grant access to all endpoints.  We only have one at the moment, and
this can be revisited if need be.
Related to https://github.com/alphagov/search-api/pull/1887
---
[Plan](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3478/console)
[Trello card](https://trello.com/c/ugkVdcjW/1233-host-ltr-reranking-in-sagemaker)
=> Give search-api permission to invoke SageMaker endpoints

terraform/projects/app-search/README.md, terraform/projects/app-search/main.tf, terraform/projects/infra-security-groups/search-api.tf
This grants Concourse the permissions and access it needs for https://github.com/alphagov/search-api/pull/1871 to work.
---
[Plan (app-search)](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3479/console)
[Plan (infra-security-groups)](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3480/console)
=> Set up permissions and security groups for Concourse to orchestrate daily LTR

terraform/projects/app-search/main.tf
This is needed to deploy the endpoint.
---
=> Give LTR role sagemaker:BatchGetImage permission

terraform/projects/app-search/main.tf
The error message doesn't give the full name of the permission it's
missing, only the suffix.
Also, the AWS API will happily let you assign a permission which doesn't
exist.
---
[Plan](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3501/console)
=> BatchGetImage is an ecr: permission, not a sagemaker: one

terraform/projects/app-search/README.md, terraform/projects/app-search/main.tf
I've given up trying to find the minimal set of permissions, so use
this sledgehammer for now.  In the future we could try stripping this
down.
Also rename the role, because it's not just the role used by
Concourse, it's the role used by SageMaker too.
---
[Plan](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3503/console)
=> Use managed SageMaker full-access policy

terraform/projects/infra-fastly-logs/main.tf
We need to increase the retention period for fastly logs
[Trello](https://trello.com/c/HdqgecUO/1658-increase-retention-period-for-fastly-logs-to-120-days)
=> Increase log retention to 120 days

terraform/projects/infra-fastly-logs/main.tf
These parameters need to be wrapped in quotes in order to be valid JSON.
We'll need to apply this to the fastly configuration 
/cc @sengi @timblair
=> Fix the JSON syntax for AWS Glue

tools/govukcli.completion
The auto-completions for govukcli aws is no longer needed as aws
features were removed.
=> Remove redundant completions

terraform/projects/app-search/README.md, terraform/projects/app-search/main.tf
SageMaker *requires* its training images to be in ECR.  Docker Hub won't work.
---
[Plan](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3524/console)
=> Add an ECR repository for the SageMaker training image

terraform/projects/app-search/main.tf
Based on instructions in
https://medium.com/miq-tech-and-analytics/cross-account-how-to-access-aws-container-registry-service-from-another-aws-account-using-iam-b372796ede14
---
[Plan](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3527/console)
=> Properly set up cross-account access to ECR repository

terraform/projects/app-backend/main.tf
When new backend instances are created via the auto scaling group
they are receiving traffic too early from the internal load balancer.
This PR fixes this issue.
=> Stop Traffic Being Sent To New Backend Instances Before They Are Ready

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/outputs.tf, terraform/projects/infra-security-groups/whitehall-frontend.tf
This is needed because we moved Worldwide API from `whitehall-admin` to
`whitehall-frontend`. Client apps in Carrenza will be connecting to AWS over
the Internet once Whitehall moves to AWS.
Tips for reviewing:
* Please check that I haven't made any copy-paste errors, for example that there aren't any references to `backend` or `admin`. (I've checked this myself but please double-check.)
* Please check that the ACLs make sense to you.
* If the intent of this change isn't completely clear to you, please say so, because that in itself indicates a bug :)
=> Add an external-facing load balancer for whitehall-frontend.

terraform/projects/app-whitehall-frontend/main.tf
This changes the load balancer healthcheck for whitehall-frontend to
talk to the app itself rather than the nginx reverse proxy in front of
the app (which always returns healthy even if the app is down).
See https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0037-alb-health-checks.md
=> Fix internal load balancer healthcheck for whitehall-frontend.

terraform/projects/app-cache/README.md, terraform/projects/app-cache/main.tf
This is to make sure we have 3 cache machines in all environments.
The values were overridden on a per-environment basis in
https://github.com/alphagov/govuk-aws-data/tree/master/data/app-cache
and
https://github.com/alphagov/govuk-aws-data/tree/master/data/app-draft-cache
Since we want the same value for all environments, there is no need to
apply them separately for each one in the files present in the
directories linked above because we can use the general values here
instead.
This PR goes together with https://github.com/alphagov/govuk-aws-data/pull/674.
Trello card: https://trello.com/c/mEXejdjd/1683-2-reduce-the-number-of-cache-boxes-to-pre-brexit-levels
=> Reduce number of cache boxes to pre-Brexit levels

tools/deploy.rb
The `deploy` script accepts four fields: `stack`, `project`,
`environment` and `command`. For each of them, there are only specific
possible values.
For the `stack`, `environment` and `command` fields, these values were
specified in the script and there was logic to abort if different values
were given.
This introduces the same logic for the `project` field.
I also reordered the variables and the `abort` statements to reflect the
order in which the fields must be given in the command line.
=> Abort deploy script if an invalid project is given

terraform/projects/infra-mirror-bucket/README.md, terraform/projects/infra-mirror-bucket/main.tf
We have life cycle for the mirror bucket but not for its replica,
it doesn't really make sense to keep all this data.
=> Add life cycle rules to the mirror replica

terraform/projects/app-postgresql/README.md, terraform/projects/app-postgresql/main.tf
The equivalent machine in Carrenza had 16 cores, so up the AWS
instance to match.
App improvements to the Publishing API and Email Alert API would be
welcome, but this is more of a quick workaround to high CPU usage.
=> Change the PostgreSQL instance type m5.2xlarge -> m5.4xlarge

terraform/projects/app-content-data-api-postgresql/README.md, terraform/projects/app-content-data-api-postgresql/main.tf
This has never been used, as the Content Data API doesn't use it. It
was originally added because I copied the pattern for other projects,
and didn't understand RDS much at all.
=> Remove the replica RDS instance for the Content Data API

Jenkinsfile, jenkins.sh, pipeline.yml, terraform/userdata/05-tag-mapit-volume, terraform/userdata/10-associate-eni, terraform/userdata/10-attach-volumes, terraform/userdata/10-db-admin, terraform/userdata/20-puppet-client, terraform/userdata/20-puppetmaster, terraform/userdata/20-puppetmaster-integration, terraform/userdata/20-puppetmaster-production, terraform/userdata/20-puppetmaster-staging, terraform/userdata/20-puppetmaster-training, terraform/userdata/30-deploy-apps, tools/build-terraform-project.sh, tools/terraform-format.sh, tools/update-docs.sh
- This is hopefully easier to follow than having to [go to another repo and understand 35 lines of code](https://github.com/alphagov/govuk-jenkinslib/blob/60a7e9c3b6be83eead36987d7a9c04eaa90d7b09/vars/govuk.groovy#L1083-L1118).
- Use some YAML anchoring to avoid specifying the `homebrew/brew` Docker `image_resource` twice.
- Also some performance improvements in the Concourse pipeline, and a version bump.
=> Migrate shellcheck CI check from Jenkins to Concourse

terraform/projects/infra-monitoring/README.md, terraform/projects/infra-monitoring/secondary.tf
Missed this in #1232. There are no remaining occurrences of `2.33.0` in
the repo.
=> Update an AWS provider version in infra-monitoring.

terraform/projects/app-licensify-documentdb/README.md, terraform/projects/app-licensify-documentdb/main.tf, terraform/projects/app-shared-documentdb/README.md, terraform/projects/app-shared-documentdb/main.tf
* Enable slow query logs for the shared DocDB cluster in all environments.
* Enable slow query logs for the Licensify DocDB cluster in all environments.
* Make the profiler settings configurable via vars.
This can be rolled out now that https://github.com/terraform-providers/terraform-provider-aws/issues/10953 is fixed and we've upgraded to `terraform-provider-aws` 2.46.0.
=> Enable the DocumentDB slow query profiler.

terraform/projects/infra-database-backups-bucket/writer.tf
In order for the DocumentDB Asset Manager data sync to function correctly
we need the "blue-db-admin" role to be able to write to the "mongo-normal" prefix.
=> Change Policy To Allow DocDB Data Sync To Work in Integration and Staging

terraform/projects/app-knowledge-graph/main.tf
The Knowledge Graph is running out of memory on start-up when it generates the data it needs. Changing the instance type from `m5.2xlarge` to `r4.2xlarge` doubles the amount of RAM available (from 32GB to 64GB), whilst minimally increasing cost.
=> Change instance type to r4.2xlarge

pipeline.yml
- Homebrew 2.2.5 has improvements that reduce the time that `brew update(-reset)` takes from 2 minutes waiting for git to unshallow the clone of Homebrew/linuxbrew-core: https://github.com/Homebrew/brew/commit/243e703700fd0c06aea982e5b2b7f45b6dedcabb
=> Concourse CI: Use Homebrew 2.2.5 that has sped up `brew update`

terraform/projects/app-monitoring/main.tf
This is for alphagov/govuk-puppet#10113.
Relevant plan output (using Staging as an example):
```
+ aws_iam_policy.list_fastly_logs
id:                                        <computed>
arn:                                       <computed>
description:                               "Allows listing (but not reading) the fastly-logs buckets. For use by monitoring."
name:                                      "fastly-logs-staging-logs-lister-policy"
path:                                      "/"
policy:                                    "{\n    \"Version\": \"2012-10-17\",\n    \"Statement\": [\n        {\n            \"Effect\": \"Allow\",\n            \"Action\": \"s3:ListBucket\",\n            \"Resource\": [\n                \"arn:aws:s3:::govuk-staging-fastly-logs\",\n …
```
=> Allow monitoring to list (but not read) Fastly logs.

terraform/modules/aws/alarms/alb/README.md, terraform/modules/aws/alarms/ec2/README.md, terraform/modules/aws/alarms/elasticache/README.md, terraform/modules/aws/alarms/elb/README.md, terraform/modules/aws/alarms/natgateway/README.md, terraform/modules/aws/alarms/rds/README.md, terraform/modules/aws/cloudwatch_log_exporter/README.md, terraform/modules/aws/elasticache_redis_cluster/README.md, terraform/modules/aws/iam/role_user/README.md, terraform/modules/aws/iam/role_user/main.tf, terraform/modules/aws/lb/README.md, terraform/modules/aws/lb/main.tf, terraform/modules/aws/lb_listener_rules/README.md, terraform/modules/aws/network/private_subnet/README.md, terraform/modules/aws/network/private_subnet/main.tf, terraform/modules/aws/network/public_subnet/README.md, terraform/modules/aws/network/public_subnet/main.tf, terraform/modules/aws/node_group/README.md, terraform/modules/aws/rds_instance/README.md, terraform/projects/app-elasticsearch6/README.md, terraform/projects/app-shared-documentdb/README.md, terraform/projects/infra-artefact-bucket/README.md, terraform/projects/infra-artefact-bucket/main.tf, terraform/projects/infra-govuk-cdn-logs-monitor-bucket/README.md, terraform/projects/infra-monitoring/README.md, terraform/projects/infra-public-services/README.md, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security/README.md, terraform/projects/infra-stack-dns-zones/README.md
In #1245 I'm seeing a failed build due to docs not matching expected output. This failure seems to be because terraform-docs has had a new release (0.8.2) rather the PR contents so this is a separate commit to fix the issues we have with the new version.
/cc @sarahseewhy @sengi
=> Update docs for terraform-docs 0.8.2

terraform/policies/fastly_logs_athena_monitoring_policy.tpl, terraform/projects/infra-fastly-logs/main.tf
Trello: https://trello.com/c/93jgKiUX/1329-set-up-a-smoke-test-that-athena-is-still-operating-on-new-data
We want to have the means to monitor whether our fastly_logs athena
databases continue to return results, this is in response to a bad
deploy a few months ago where we discovered that the database was no
longer queryable.
To monitor Athena we need a user that has access to Athena, to AWS Glue
to access table details, to have read access to the bucket the data is
in and to have write access to a bucket to store results. The intention
is that this users credentials will be stored within Jenkins and
periodically a job will run that makes a query to Athena. This job will
be deemed successful if results can be pulled from the database.
This PR adds a new IAM user for this monitoring and …
=> Add ability to monitor fastly_logs Athena databases

terraform/projects/infra-fastly-logs/main.tf
These descriptions no longer reflected the reality of the Fastly data.
=> Fix outdated Athena database descriptions

terraform/projects/app-apt/README.md, terraform/projects/app-apt/main.tf
* We needed to increase the volume size in production as part of the Aptly migration.
* Aptly has more packages in Carrenza than in AWS and required a larger EBS volume to achieve feature parity.
=> Customise EBS volume size between environments

terraform/projects/app-knowledge-graph/main.tf
The load balancer should allow the connection to finish before terminating
the instance. This was raised by Trusted advisor and this change makes thie ELB match
all of our other ones.
=> Enable connection draining

terraform/projects/app-knowledge-graph/userdata.tpl
This PR installs `zip` and `unzip` on the Knowledge Graph machine. These will be used to unzip a JAR file, amend its contents, then re-zip back to a JAR file.
=> Install zip utilities on Knowledge Graph machine

terraform/projects/app-content-data-api-postgresql/main.tf, terraform/projects/app-postgresql/main.tf, terraform/projects/app-transition-postgresql/main.tf
Enable slow query logging on:
- content data api
- postgresql primary
- postgresql standby
- transition primary
- transition standby
This well log queries which run longer than 10 seconds, which will aid in diagnosis of problems.  This feature existed in pre-aws migration environments
Pair: @smford & @sarahseewhy
=> Adding slow query to postgres

terraform/projects/app-postgresql/main.tf, terraform/projects/app-transition-postgresql/main.tf
Fix param group settings for app-transition and app-postgresql RDS instances
- Remove generic parameter_group named parameter group
- Creating a shared parameter group for primary and secondary databases as we will want them to be the same
=> Fix rds param groups postgres

terraform/projects/app-content-data-api-postgresql/main.tf
A second param group was accidentally added to support slow query logs,
this is now being removed, and the slow query log configuration has
been moved to the main param group.
=> Fix content data api RDS instance Paramgroup

terraform/modules/aws/rds_instance/README.md, terraform/modules/aws/rds_instance/main.tf, terraform/projects/app-content-data-api-postgresql/main.tf, terraform/projects/app-mysql/README.md, terraform/projects/app-mysql/main.tf, terraform/projects/app-transition-postgresql/main.tf
This enables autoscaling of storage for compatible RDS instances.
This PR needs to be merged at the same time as: https://github.com/alphagov/govuk-aws-data/pull/695
Defining a default of 100GB for the upper limit for AWS to allow storage autoscaling growth, this needs to be set to instruct terraform to configure storage autoscaling.
- allocated_storage defines the initial provisioning size of the RDS instance
- max_allocated_storage defines the upper limit for AWS to allow autoscaling growth
Configure all existing RDS instances to support scalable storage
This requires max_allocated_storage to be defined to all instantiations of rds_instance
- define a max_allocated_storage for content-data-api-postgresql-primary_rds_instance
- apply terraform fmt to …
=> Enable storage autoscaling of RDS instances

terraform/projects/app-content-data-api-postgresql/main.tf
The value needs to be increased to allow autoscaling to occur properly.
=> Increase RDS max storage for content-data-api-postgresql

terraform/projects/infra-security-groups/cache.tf
What
---
We have [instrumented the router application](https://github.com/alphagov/router/pull/148)
We want prometheus to scrape it in integration, as this is where we will deploy our instrumented build of router
This PR adds a job to Prometheus, representing the router app. The job will exist in all environments but the service discovery will only find instances in the integration environment.
How to review
---
Code review
Check that 3055 is the correct port
=> Prometheus to scrape router metrics

terraform/projects/app-backend/README.md, terraform/projects/app-backend/main.tf
* Add an internal-facing Application Load Balancer (ALB/L7LB) for the `backend` apps, with per-app healthchecks configured.
* Switch `backend.*.govuk-internal` DNS names to point to the new internal ALB instead of the classic ELB.
* Remove the classic ELBs `blue-backend-external` and `blue-backend-internal` and their associated resources.
We need to use an ALB instead of a classic ELB in order to configure healthchecks correctly for each app, per https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0037-alb-health-checks.md. The same set of `backend` machines hosts many different apps whose instances need to be healthchecked independently in order to handle the failure of individual app instances correctly.
The motivation for addressing this healthcheck issue now …
=> Switch `backend` internal LB to ALB and remove classic ELBs.

terraform/projects/app-backend/README.md, terraform/projects/app-backend/main.tf
#1269 tries to create another 31 TGs and attach them to the `blue-backend` ASG. The limit is 50 TGs on any given ASG, so it's not possible to roll out. The TF provider isn't smart enough to validate that when running `terraform plan`.
Reverts alphagov/govuk-aws#1269.
=> Revert "Switch `backend` internal LB to ALB and remove classic ELBs."

terraform/projects/app-mapit/main.tf
This changes the load balancer healthcheck for MapIt to
talk to the app itself rather than the nginx reverse proxy in front of
the app (which always returns healthy even if the app is down).
See https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0037-alb-health-checks.md
=> Fix internal load balancer healthcheck for MapIt.

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/waf.tf
Allows other Terraform projects to attach their load balancers to the WAF. The shared `backend` ELB in `app-backend` will be the first to need this.
=> Add an output for the default WAF ACL.

terraform/projects/app-backend/README.md, terraform/projects/app-backend/main.tf
Remove the classic ELB `blue-backend-external` and its associated
resources, in all three environments.
This classic ELB is no longer used. Its request logs consist entirely of
AWS Security Scanner and bogus traffic where the Host header doesn't
match any of the services.
Previously tried this in 58e8439 as part of #1269, but reverted because
other changes in that PR proved infeasible to roll out. Hence breaking
it up into smaller changes.
alphagov/govuk-aws-data#699 cleans up the disused vars.
Deployed to Staging and ran Smokey in AWS and Carrenza; all tests passed.
=> Remove `blue-backend-external` classic ELBs.

terraform/projects/app-postgresql/README.md, terraform/projects/app-postgresql/main.tf
- We're seeing spiky CPU usage, going up to 99%, when scheduled publishing occurs at 0930, and emails are sent out at various points during the day.
- Tuning the apps would take longer and maybe not even be feasible as scheduled publishing has to happen, and so does sending urgent emails.
- We could investigate splitting the databases out into `publishing-api-postgresql` and `email-alert-api-postgresql`, but we attempted that before and [resolved to not do it](https://github.com/alphagov/govuk-aws/commit/c51e8bbf879dd867b73bec4f71ba7271703e1909) (also for [publishing-api](https://github.com/alphagov/govuk-aws/pull/1086/commits/3f7cc071b4361e5df15ac1dfb2a1e3c565bb8678)).
- According to https://www.ec2instances.info/rds/?region=eu-west-1&cost_duration=monthly, base cost for the old instance …
=> postgresql: Bump production database instance size to db.m5.8xlarge

terraform/projects/app-postgresql/README.md, terraform/projects/app-postgresql/main.tf
- We're using too old a Postgres version (9.6.old-patch) for Amazon to
let us use `db.m5.8xlarge`:
```
* module.postgresql-primary_rds_instance.aws_db_instance.db_instance: 1 error occurred:
* aws_db_instance.db_instance: Error modifying DB Instance blue-postgresql-primary: InvalidParameterCombination: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.m5.8xlarge, Engine=postgres, EngineVersion=9.6.11, LicenseModel=postgresql-license. For supported combinations of instance class and database engine version, see the documentation.
```
- Instead, we're upgrading to the next unrestricted database instance.
This costs an extra $2254/month compared to what we have _now_
(`db.m5.4xlarge`)
Related PRs (specifically relevant to costings): #1264.
=> postgres: Increase instance size to db.m5.12xlarge

terraform/projects/infra-monitoring/README.md, terraform/projects/infra-monitoring/main.tf
This just reflects what Amazon creates automatically when we enable Enhanced Monitoring on RDS instances. We need it in order to bring Terraform in sync with our production config.
=> Add IAM role for RDS Enhanced Monitoring.

terraform/modules/aws/rds_instance/README.md, terraform/modules/aws/rds_instance/main.tf, terraform/projects/app-content-data-api-postgresql/main.tf, terraform/projects/app-postgresql/README.md, terraform/projects/app-postgresql/main.tf, terraform/projects/app-transition-postgresql/main.tf
* Enable Enhanced Monitoring on all of our RDS Postgres instances.
* Keep the RDS Postgres standby instance at its current size.
We recently enabled Enhanced Monitoring on the shared Postgres RDS in production. This change reflects that, and also enables it on all the other Postgres RDS instances in all environments. The cost of doing so is negligible (just a modest amount of log storage) and the benefits are significant, as it gives us per-process history of CPU usage (and therefore per-query history of CPU usage, albeit sampled).
We also recently enlarged the shared Postgres RDS in production to 12xlarge. We want to avoid applying the same change to the standby instance, which appears to be disused. We'll want to confirm that it's disused and if so, decommission it in the near future - …
=> Enable Enhanced Monitoring on RDS Postgres.

terraform/projects/app-gatling/README.md, terraform/projects/app-gatling/main.tf
During a period of forthcoming load-testing we would like to maintain an active Gatling instance.
=> Update Gatling load-testing instances to 1

terraform/projects/app-search/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/elasticsearch6.tf, terraform/projects/infra-security-groups/outputs.tf, terraform/projects/infra-security-groups/search-api.tf, terraform/projects/infra-security-groups/search-ltr-generation.tf
This PR creates an ASG, where the node template uses the same role
as the regular search machines, so members will be able to access
Elasticsearch and S3 just as search-api currently does.
Currently training data is generated by sending an HTTP request to
search-api and waiting.  But we want to now start producing more
training data, which will significantly slow that down.  We don't want
to put lots of extra strain on a live search-api instance, so instead
here's how it's going to work:
1. Concourse will scale up the ASG to 1 member
2. Concourse will SSH in to the new instance, then:
1. Clone search-api from github
2. Install dependencies
3. Run the training data generation rake task
3. Concourse will scale down the ASG to 0 members
---
[Trello …
=> Create an ASG for concourse to use for search LTR data generation

terraform/projects/app-data-science-data/userdata.tpl
This PR copies the logs from the data science provisioning machine to S3.
Trello: https://trello.com/c/smgoD8Cm
=> Copy data science data generation logs to S3

terraform/projects/app-data-science-data/main.tf, terraform/projects/app-knowledge-graph/main.tf
This PR updates the scaling times of the Knowledge Graph auto scaling group to maintain the expected availability of the platform now that we are in UTC+1. Auto scaling group scheduled actions do not cater for any other timezone than UTC, so this is a necessary change to ensure the graph is available when people expect it to be (see https://docs.aws.amazon.com/autoscaling/ec2/userguide/schedule_time.html for more info).
=> Update the scaling times of the Knowledge Graph ASG

tools/govukcli
SSH:
- We sent out an email about deprecating `govukcli ssh`, pointing people
to the new way: `gds govuk connect`, as documented in the dev docs.
- This does the same deprecation as we did for the AWS command.
AWS:
- The `govukcli aws` command has been deprecated for 6 months - since
November (6cd2d59535749f14bfebe2b1008605b0152fb287).
- That's enough time for people to migrate to `gds aws`.
https://trello.com/c/ZBGHVlTr/132-deprecate-and-delete-govukcli
=> tools/govukcli: Deprecate SSH, and remove AWS features

terraform/projects/app-prometheus/README.md, terraform/projects/app-prometheus/main.tf
From a t3.micro, as it looks like with the addition of data for the
router, Prometheus requires more than 1GB of memory.
=> Change the prometheus instance type to t3.small

doc/guides/redeploying-applications-on-rebuild.md, terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/calculators-frontend.tf, terraform/projects/infra-security-groups/frontend.tf, terraform/projects/infra-security-groups/outputs.tf
This commit removes the security group rules allowing Carrenza access,
without adding equivalent rules for frontend (which is what now serves
the calendar pages).  I don't think the rules are needed, as
gds-api-adapters uses 'Plek.new.website_root' for calendars, which
points to the external URL.
---
[Plan (infra-public-services)](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/4298/console)
[Plan (infra-security-groups)](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/4299/console)
[Trello card](https://trello.com/c/SKT4BnIQ/1953-retire-the-calendars-app-%F0%9F%8D%90)
=> Remove calendars

terraform/modules/aws/lb_listener_rules/main.tf
Terraform doesn't seem to infer the necessary ordering when updating
these resources.
=> Add explicit dependency for listener rules on target group

terraform/modules/aws/lb_listener_rules/main.tf
See #1292 
> looks good, lets try it in staging or somewhere
> https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/4349/console 😞
> no option than manual then. These are the only 2 things I know can change the order. Sorry :-(
=> Revert "Add create_before_destroy to target groups"

terraform/projects/app-frontend/main.tf
Cyber have asked for this to be implemented so they can improve logging. This commit
adds the necessary policy to the Frontend instances. It has been set up in
accordance to the guidance in the AWS Docs:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/create-iam-roles-for-cloudwatch-agent-commandline.html
=> Allow Cloudwatch To Collect Data From Frontend Machines

terraform/projects/app-frontend/main.tf
Added the wrong policy initially when committing:
https://github.com/alphagov/govuk-aws/pull/1294
Should have added the AWS managed CloudWatchAgentServerPolicy
instead. Now corrected.
=> Correct Cloudwatch Policy Mistake

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/deploy.tf, terraform/projects/infra-security-groups/variables.tf
For continuous deployment:
1. AWS Integration Jenkins should be able to access AWS Staging Jenkins
2. AWS Staging Jenkins should be able to access AWS Production Jenkins
=> allow AWS jenkins for continuous deployment

.github/workflows/ci.yml
- The [GOV.UK repo
autoconfigurer](https://github.com/alphagov/govuk-saas-config) expects a
GitHub Actions workflow file at the following path
`.github/workflows/ci.yml`. Within it, it expects a job named `test` to
auto-configure. At the moment on PRs, there's a non-existent `test` task
that is a required status check. This fixes it so PRs are mergeable
again.
=> ci: Rename "lint" job to "test"

terraform/projects/infra-security/main.tf
This PR adds the missing action `CreatePresignedNotebookInstanceUrl` to the `data-science-access-sagemaker` policy, which allows anyone assuming the `govuk-datascienceusers` role to successfully open a Jupyter notebook hosted within SageMaker.
=> Add missing SageMaker action to policy

terraform/projects/app-email-alert-api/README.md, terraform/projects/app-email-alert-api/main.tf
From m5.xlarge instances, this provides less memory, but they should
be more performant. The Email Alert API doesn't need 16GiB of memory,
8GiB should be fine, and I'm planning to increase the number of
instances, which should spread the load.
=> Switch to c5.xlarge instances for the Email Alert API

terraform/projects/app-db-admin/README.md, terraform/projects/app-db-admin/main.tf, terraform/projects/infra-content-publisher/README.md, terraform/projects/infra-content-publisher/env_sync.tf
add the necessary permissions so the puppet govuk_env_sync running
on the db_admin machines can sync the content publisher s3
buckets
=> content-publisher-sync

terraform/projects/app-email-alert-api/README.md, terraform/projects/app-email-alert-api/main.tf
8GB of memory should be fine for the Email Alert API, but for the last
4 Fridays, some of the Sidekiq processes for the Email Alert API have
used lots of memory, beyond the limit set for the Icinga checks.
Until we've managed to address the excessive memory usage, and
reliability of the jobs (Sidekiq isn't exactly reliable), going back
to 16GB of memory might help to avoid issues with Sidekiq using all
the memory.
This reverts commit dae54679cf50585abddb6c4413b7b2a26b0492e5.
=> Revert "Switch to c5.xlarge instances for the Email Alert API"

terraform/projects/infra-content-publisher/README.md, terraform/projects/infra-content-publisher/env_sync.tf
changes:
1. allow only child environment to access parent environment bucket, e.g. integration should only access staging only.
2. aws accounts are put in govuk-aws-data
3. a given environment has all put rights to its bucket so that it can take ownership of the object. This is needed because integration would not be able to copy staging bucket objects if the objects are still owned by production.
=> Content publisher env sync refactor

docs/guides/environment-provisioning.md
This is required, otherwise it just says "No waiting certificate requests to sign". The other commands have sudo before them, so it's not implied by context.
=> Add sudo to puppet cert sign --all in the docs

.blue.integration.env
- This was added 3 years ago in https://github.com/alphagov/govuk-aws/pull/233 when we were building out the new AWS integration environment.
- Given we have better ways of deploying Terraform for existing enviromnments now, and it's telling that we don't have `.blue.staging.env` files or `.blue.production.env` files (and definitely not `.pink.test.env` for the new replatforming work), we don't need this. Also, as mentioned in the original PR, it's too easy to forget you've `source`d this and do things to the wrong environment.
=> git rm .blue.integration.env

terraform/policies/whitehall_s3_writer_policy.tpl, terraform/projects/app-whitehall-backend/README.md, terraform/projects/app-whitehall-backend/main.tf
As part of the migration to Notify, Whitehall needs to send emails as links rather than attachments. Following the example of specialist-publisher (alphagov/specialist-publisher#1576, alphagov/specialist-publisher#1625, #1254, #1256) this is being done by uploading them to s3 and then sending a link which will serve the file.
https://trello.com/c/5xKHcam8/2012-5-whitehall-replace-attachments-in-documentlistexport-so-that-notify-can-be-used
=> S3 bucket for email attachments from whitehall

terraform/projects/app-whitehall-backend/main.tf
Errors introduced in #1315. This points resources at correct role names rather than ones that have been removed.
https://trello.com/c/5xKHcam8/2012-5-whitehall-replace-attachments-in-documentlistexport-so-that-notify-can-be-used
=> Correct role names for whitehall s3 access

terraform/projects/app-whitehall-backend/main.tf
Fixing errors from #1315 and #1317.
https://trello.com/c/5xKHcam8/2012-5-whitehall-replace-attachments-in-documentlistexport-so-that-notify-can-be-used
=> Correct policy parameter for whitehall s3 access

docs/guides/environment-provisioning.md
The documentation has been updated to reflect the additional
steps required to provision a new environment, and more detail
where that is helpful.
Bringing up a new environment is challenging. We're looking at
how we can make bringing up a new environment faster as part
of our discovery on the replatforming team.
Closes #1306.
=> Update environment provisioning documentation

docs/guides/environment-provisioning.md
It's /etc/resolv.conf that sets the search domains, not /etc/hosts
=> Fix filename for DNS config

tools/govuk-puppetmaster-integration-bootstrap.sh, tools/govuk-puppetmaster-production-bootstrap.sh, tools/govuk-puppetmaster-staging-bootstrap.sh, tools/govuk-puppetmaster-training-bootstrap.sh
The puppet masters clone govuk-secrets, because govuk-secrets is now so
large it takes a very long time to provision a puppetmaster.
This change only pulls down the git repo to a depth of 1 rather than
everything back to the triassic period.  This greatly increases the speed
in which to provision a puppetmaster.
=> Speed up cloning govuk-secrets to puppetmasters

tools/govuk-puppetmaster-integration-bootstrap.sh, tools/govuk-puppetmaster-production-bootstrap.sh, tools/govuk-puppetmaster-staging-bootstrap.sh
To provision puppetmaster machines in AWS we run a bootstrap script
that will go through a bundle install at some point.
Recently this part of the process has started to fail with this
error : Retrying dependency api due to error (2/3):
Bundler::HTTPError Net::HTTPUnprocessableEntity: Too many gems
(use --full-index instead)
We can't be sure when this process broke since we provision
puppetmaster very rarely, I'm not sure what the underlying cause
of the problem is either, using --full-index seems to fix the issue
=> Add the --full-index flag to bundle install in bootstrap script

terraform/projects/app-ci-master/main.tf
without this, ci_master instance will not be able to finds its volume and attach it
=> fix typo in volume tag

terraform/projects/app-knowledge-graph/main.tf
This PR pins Neo4j Community Edition version `3.5.16` in the `app-knowledge-graph` project. 
A new major version has been released on 3rd September 2020 which is causing problems (the release seems to have quite a few bugs), so we should wait until these are fixed as well as testing our setup on the new major version before making the jump to it. 
Version `3.5.21` (released 26th August 2020) also contains a bug where the default password is not the instance id (according to the [docs](https://aws.amazon.com/marketplace/pp/Neo4j-Neo4j-Graph-Database-Community-Edition/B071P26C9D#pdp-usage) it should be), which is another reason why this commit uses a known stable version.
=> Pin Neo4j Community to 3.5.16 in app-knowledge-graph

terraform/projects/app-apt/main.tf, terraform/projects/infra-security-groups/apt.tf, terraform/projects/infra-security-groups/ci-agents.tf, terraform/projects/infra-security-groups/ci-master.tf, terraform/projects/infra-security-groups/outputs.tf
- allow external gemstash in aws production so that carrenza production can use it and shutdown its apt server
- fixes ci security groups so that they don't get created in production
- removes some ci master security group as there is no clear need for them
=> external gemstash in production and fix ci security groups

terraform/projects/app-apt/README.md, terraform/projects/app-apt/main.tf, terraform/projects/infra-security-groups/ci-master.tf
- no ci security groups in production as ci is in integration only
- add publishing.service.gov.uk to externla ELB of apt so that gemstash.publishing.service.gov.uk works.
=> final fixes to gemstash and ci

terraform/projects/app-ci-master/README.md, terraform/projects/app-ci-master/main.tf
we defined the public ALB for ci master in app-ci-master instead of infra-public-services because it is intended for this to be deployed in AWS integration only, rather than other environments.
=> public ALB for ci master in AWS integration

terraform/projects/infra-email-alert-api-archive/main.tf
Removes two columns from the email-alert-api archive schema. These are
`finished_sending_at_utc` and `sent`. The reason we are removing these
is they may change after an email has been archived, which
makes them misleading. For archiving purposes, it should be enough to
know when the email was created, since this is usually similar to when
it was sent.
Dependant on:
https://github.com/alphagov/email-alert-api/pull/1396
Trello:
https://trello.com/c/15eVh9Qg/482-stop-relying-on-notify-status-updates-to-archive-delete-emails
=> Remove sent and finished_sending_at from schema

terraform/projects/infra-security-groups/apt.tf, terraform/projects/infra-security-groups/licensify-backend.tf, terraform/projects/infra-security-groups/licensify-frontend.tf, terraform/projects/infra-security-groups/publishing-api.tf, terraform/projects/infra-security-groups/whitehall-backend.tf, terraform/projects/infra-security-groups/whitehall-frontend.tf
Allow ${var.ithc_access_ips} to Apt, Licensify, Publishing API and Whitehall. This enables testers access to machines without needing to be on the VPN.
=> Allow ${var.ithc_access_ips} SSH access

terraform/projects/infra-database-backups-bucket/main.tf
Holds production database backup for Coronavirus Find Support. Set
expiration for 1 year as our privacy policy states we would delete
data when no longer required.
=> Add coronavirus find support lifecycle rule

terraform/projects/app-mapit/main.tf
Unfortunately the Terraform config is currently hard coded for 2 instances, so to up it to 8, I've had to copy and paste the resources manually.
It's definitely worth refactoring this in the future, but for now we need to get the instances up relatively quickly, so I think this will do.
=> Add 6 more Mapit instances

terraform/projects/app-mapit/README.md, terraform/projects/app-mapit/main.tf
This was missed in https://github.com/alphagov/govuk-aws/pull/1351 and is required otherwise the Terraform is invalid.
=> Add variables for mapit subnets

terraform/projects/infra-database-backups-bucket/main.tf
Holds production database backup for Coronavirus Business Volunteer form.
Set expiration for 1 year as our privacy policy states we would delete
data when no longer required.
[Trello](https://trello.com/c/bn2EPyTa/559-take-backup-of-the-business-volunteering-database)
=> Add coronavirus business volunteer lifecycle rule

terraform/projects/infra-public-services/waf.tf
As requested by Cyber security :
"those fields are particularly useful when it comes to web attack
detection - so could we un-redact them please?"
=> Un-redact waf logs

terraform/projects/app-search/README.md, terraform/projects/app-search/main.tf
At the moment the search machines are `c5.large` which has 4 GB of memory. We seem to be pretty close to that limit at the moment as most machines are using around 3.5 GB of memory. We've also noticed that Ruby 2.7 seems to use slightly more memory than earlier versions so I think it makes sense to increase the memory on these machines in advance of that. The `c5.xlarge` instance type has 8 GB of memory available.
=> Change search instance type to c5.xlarge

terraform/projects/infra-security-groups/email-alert-api.tf
The GOV.UK Account Manager will need access to email-alert-api (until the email code is moved back into a GOV.UK application), so we need to permit ingress to requests from the GOV.UK PaaS.
Trello card: https://trello.com/c/U0P11cQc
=> Permit ingress to email-alert-api from GOV.UK PaaS

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/email-alert-api.tf, terraform/projects/infra-security-groups/variables.tf
This was missing, so the Terraform failed to apply.
Trello card: https://trello.com/c/U0P11cQc
=> Add variable block for GOV.UK PaaS egress IPs

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/email-alert-api.tf, terraform/projects/infra-security-groups/variables.tf
We added a security group to only permit ingress to email-alert-api from the GOV.UK PaaS, but there was already a security group permitting access from any IP.
This reverts commits 22434e0baa145f939ad46396ad70e648c0b4738a, 28fae7be6396a381a81eeeea2912e4265eb92c02 and e65340979dd8eac46b150e64513bd696bdcec501.
=> Remove email-alert-api ingress restriction

terraform/projects/infra-security-groups/knowledge-graph.tf
This PR adds a new rule to the Knowledge Graph security group, granting access to PaaS egress IPs to the Knowledge Graph over the Bolt protocol.
Trello: https://trello.com/c/LJunJhaU
=> Allow PaaS to talk to Knowledge Graph over Bolt protocol

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/variables.tf
This PR restores the PaaS egress IPs to `infra-security-groups` that were removed as part of PR https://github.com/alphagov/govuk-aws/commit/a4d33cc8b05f5875c4f9ff7eac1ed322c30afe9f.
The reason for this is that they are being relied upon in the later-merged PR https://github.com/alphagov/govuk-aws/pull/1361, so they should still be available in this project.
=> Restore PaaS egress IPs to infra-security-groups

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/knowledge-graph.tf, terraform/projects/infra-security-groups/variables.tf
This PR renames the variable `paas_egress_ips` to `paas_london_egress_ips` for the current London-region PaaS IPs, adds `paas_ireland_egress_ips` for Ireland region PaaS IPs and updates the Knowledge Graph security group to reflect these changes.
It also changes PaaS access to the Knowledge Graph from being over bolt to now being over https.
=> Update PaaS egress IPs and Knowledge Graph access

terraform/projects/app-knowledge-graph/main.tf
AWS does not allow timezones to be specified for scheduled actions of an auto-scaling group, so manually change the times that the Knowledge Graph spins up and spins down (in UTC) so that they're consistent with BST.
This commit also updates the desired capacity of the Knowledge Graph auto-scaling group to be `0` by default.
=> Update knowledge graph scheduled action times

terraform/projects/app-data-science-data/main.tf, terraform/projects/app-knowledge-graph/main.tf
This PR updates the scheduled action times for spinning-up and spinning-down instances of both `app-data-science-data` and `app-knowledge-graph`. The reason for doing this is because data that we rely on in GA as part of the data generation pipeline is often not created until 08:30 UTC daily, so we should hold off until then to ensure that it's available.
The Knowledge Graph uses the output of the data generation pipeline, so it is also moved back an hour to ensure that output exists when the machine spins-up.
=> Change scheduled action times for app-data-science-data and app-knowledge-graph

terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/main.tf
Remove the unnecessary and confusing var `integration_only` and add some TODOs for further cleanup.
This should make the upcoming [fixes to retention policies](https://trello.com/c/6Br21sKD/3916) easier.
Tested: verified no diffs with `terraform plan` in integration, staging and production. (e.g. `gds aws govuk-integration-admin -- tools/build-terraform-project.sh -c plan -d ../govuk-aws-data/data -e integration -s govuk -p infra-database-backups-bucket`)
alphagov/govuk-aws-data#801 removes the disused vars from the private repo.
=> Simplify confusing logic for S3 lifecycle rules.

terraform/projects/app-cache/README.md, terraform/projects/app-cache/main.tf
This updates the default AWS auto scaling group size for `cache` from 6
to 9. The only environment using 6 was staging, and this will align the
default to what production uses instead.
Follow up PR: https://github.com/alphagov/govuk-aws-data/pull/804
Co-authored-by: Alan Gabbianelli <Alan.Gabbianelli@digital.cabinet-office.gov.uk>
Co-authored-by: Rebecca Pearce <Rebecca.Pearce@digital.cabinet-office.gov.uk>
=> Edit app-cache ags_size

terraform/projects/app-frontend/README.md, terraform/projects/app-frontend/main.tf
This updates the default AWS auto scaling group size for `frontend` from
3 to 12. The only environment using 3 was staging, and this will align
the default to what production uses instead.
Follow up PR: https://github.com/alphagov/govuk-aws-data/pull/805
Co-authored-by: Alan Gabbianelli <Alan.Gabbianelli@digital.cabinet-office.gov.uk>
Co-authored-by: Rebecca Pearce <Rebecca.Pearce@digital.cabinet-office.gov.uk>
=> Edit app-frontend ags_size

terraform/projects/infra-email-alert-api-archive/README.md, terraform/projects/infra-email-alert-api-archive/main.tf
https://trello.com/c/UMGXUk5R/654-retire-archiving-emails
Previously we tried using the "force_destroy" flag, but this doesn't
seem to have the intended effect (nothing changes), and actually just
leaves Terraform thinking it's already deleted the bucket. Turns out
we can empty the bucket manually, so this just removes it.
Note that we will delete the project entirely in a future commit.
=> Empty bucket manually instead of force destroying

terraform/projects/infra-security-groups/bouncer.tf
This is required so that Jenkins can run smokey tests against Bouncer
for continuous deployment reasons. Jenkins will access Bouncer via
the internal ELB of Bouncer on HTTPS (port 443).
=> Allow Jenkins to send https to Bouncer internal ELB

terraform/projects/app-mapit/README.md, terraform/projects/app-mapit/main.tf
The architecture of mapit is different from that of other GOV.UK apps and more work is needed to scale it up and spin up more instances, including:
- making the changes in [this `govuk-aws` PR](https://github.com/alphagov/govuk-aws/pull/1385)
- making the changes in [this `govuk-aws-data` PR](https://github.com/alphagov/govuk-aws-data/pull/817)
- going through [the `Fix Mapit database not available` docs](https://docs.publishing.service.gov.uk/manual/mapit-database-not-available.html)
This would be the right time to refactor and DRY this up but, unfortunately, a time-sensitive constraint means there's no time for it today.
Inspired by:
- https://github.com/alphagov/govuk-aws/pull/1351
- https://github.com/alphagov/govuk-aws/pull/1353
=> Scale mapit up from 8 to 12 instances

terraform/projects/app-cache/main.tf
Having the minimum capacity be 1 less than the max/desired capacity enables us to move one instance into a standby state, without the ASG starting a new instance to replace the instance we are performing maintenance on.
This is helpful for rebooting an instance. We can follow the procedure to [place an ASG instance in a standby state](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-enter-exit-standby.html#standby-state) which lets us reboot a machine safely (preventing it from serving requests while it is rebooting).
=> Set cache asg_min_size to asg_desired_capacity - 1

terraform/projects/app-mapit/README.md, terraform/projects/app-mapit/main.tf
This is a refactor commit, it doesn't change any functionality.
Currently, we use one subnet variable for each mapit instance and EBS volume. This means for each new mapit instance we add here in `govuk-aws`, we add a new variable in `govuk-aws-data`. This makes scaling mapit up or down more time-consuming and more error prone (the more code we add or change, the higher the chance to introduce bugs).
https://github.com/alphagov/govuk-aws-data/pull/820 introduced `mapit_subnet_a`, `mapit_subnet_b` and `mapit_subnet_c`, and removed the numbered variables, making this change necessary.
This means in the future we'll only have to make changes to `govuk-aws` to scale mapit up or down.
=> Use one subnet per availability zone in AWS

terraform/projects/app-data-science-data/main.tf
This PR allows the `data-science-data` machine to invoke the SageMaker `govner` model, as part of the work around extracting entities from content.
=> Allow data-science-data machine to invoke SageMaker govner model

terraform/projects/infra-database-backups-bucket/main.tf
The backup has been transferred to another department and will no longer be stored. Cleaning up this extra lifecycle rules as its no longer needed.
=> Remove S3 lifecycle rule for business support database backup

terraform/projects/app-frontend/README.md, terraform/projects/app-frontend/main.tf, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/frontend.tf, terraform/projects/infra-security-groups/outputs.tf
The theory here is that having a shared rails cache should improve
performance of the frontend applications now that we've scaled them
up to a large number of instances.
We're particularly hoping to see improvements between `collections` and
`mapit`, as the responses from mapit are highly cacheable (postcodes
don't change local authority very often.
`infra-security-groups` will need to be applied first, as `app-frontend`
depends on a new output.
The `r6g` instance type is the default if you click through in the AWS
console. AWS suggest that the ARM based processers work well with
elasticache:
https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-elasticache-now-supports-m6g-and-r6g-graviton2-based-instances/
The choice between `m6g` and `r6g` is arbitrary - `r6g` comes first in
the …
=> Create a shared memcached cluster for Frontend

terraform/policies/ask_export_s3_writer_policy.tpl
This adds permissions to manage object ACLs because permission needs to be given to the cross account bucket owner to access the objects.
=> Update Ask Export IAM policy

terraform/projects/app-knowledge-graph/main.tf
This PR adds lifecycle rules within the `govuk-data-infrastructure-integration` bucket to keep only the last 30 days of data. This is necessary as we currently hold more data which is never used, so by only keeping the most recent month's worth of data we can reduce costs and remove noise.
=> Add lifecycle rules within govuk-data-infrastructure-integration bucket

terraform/projects/app-content-store/main.tf, terraform/projects/app-draft-content-store/main.tf, terraform/projects/infra-public-services/main.tf
https://trello.com/c/EADdQIOp/277-investigate-improving-healthchecks-for-content-store-and-other-lbs
This makes a couple of changes to the LB and Target Group
config, in response to an incident on Staging. Making these
changes brings the config for Content Store on a par with
most other apps. Please see the commits for more details.
=> Improve health detection for Content Store

terraform/projects/app-content-store/main.tf, terraform/projects/app-draft-content-store/main.tf, terraform/projects/infra-public-services/main.tf
Reverts alphagov/govuk-aws#1396
Referring to [this commit](https://github.com/alphagov/govuk-aws/pull/1396/commits/3f9393135177020393d79a993d053352b37d45f1), unfortunately this doesn't work because our Staging and Production environments don't have a "aws_migration" flag set, which means the "lb_healthchecks" file doesn't exist, which means we don't expose the app-specific healthcheck routes used in this PR.
We'll need to investigate exposing those routes in Puppet, first.
=> Revert "Improve health detection for Content Store"

terraform/projects/app-content-data-api-postgresql/main.tf, terraform/projects/app-postgresql/main.tf, terraform/projects/app-transition-postgresql/main.tf
See individual commits for more thorough details of each change.
This change is designed to help us debug issues with slow queries. Specifically, it came out of some work I've been doing to investigate timeouts in the Email Alert API.
These changes are mostly useful for Email Alert API, but I've decided to apply them across all our databases for consistency.
[Trello Card](https://trello.com/c/AHKVvZb2/2290-investigate-500-errors-in-email-alert-frontend)
=> Add logging for queries which are waiting on locks to be relased

terraform/projects/app-prometheus/README.md, terraform/projects/app-prometheus/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/outputs.tf, terraform/projects/infra-security-groups/prometheus.tf
See also https://github.com/alphagov/govuk-aws-data/pull/836 (which needs to be merged first).
This creates a new internal load balancer for Prometheus, and gives Grafana permission to access it. My previous attempt to allow Grafana to access Prometheus through its external load balancer (0ac9a0d) didn't work, so this PR does it "properly" (i.e. consistently with all the other applications).
To deploy this, we will need to apply three separate terraform deployments to three separate environments:
I love to apply terraform manually 9 times 😍
```
+ aws_security_group.prometheus_internal_elb
id:                       <computed>
arn:                      <computed>
description:              "Prometheus Internal LB"
egress.#:                 <computed>
ingress.#:                <computed> …
```
=> Allow grafana to use Prometheus

terraform/projects/app-content-store/main.tf, terraform/projects/app-draft-content-store/main.tf, terraform/projects/infra-public-services/main.tf
Reverts alphagov/govuk-aws#1402
This is good to go in Staging/Production, now that https://github.com/alphagov/govuk-puppet/pull/10910 is deployed.
=> Revert "Revert "Improve health detection for Content Store""

terraform/projects/app-ci-master/main.tf
CI Jenkins was regularly running out of IOPS quota ("burst balance") on its persistent data volume and this was impairing its performance.
As of Dec 2020, gp3 is the current generation general purpose EBS product and it comes with approximately 30 times the IOPS quota for (slightly less than) the same money. So it's a no-brainer.
The actual change has already been made (via `aws ec2 modify-volume --volume-id ... --volume-type gp3`). This commit just brings Terraform back into sync. I verified that there's no diff (and that there was the expected diff before).
This only exists in the integration environment, which is why I haven't parameterised the value.
=> Upgrade CI Jenkins EBS volume from gp2 to gp3.

terraform/projects/app-knowledge-graph/main.tf
This PR adds a lifecycle rule for the `lambdas` prefix of the `govuk-data-infrastructure-integration` bucket in the integration account. The lifecycle rule will delete all previous versions of files under this prefix 30 days after they are made non-current versions, which will happen as new versions of Lamda deployment packages are uploaded.
=> Add lifecycle rule for lambdas prefix in data bucket

terraform/projects/app-content-store/README.md, terraform/projects/app-content-store/main.tf
This changes the default instance size from m5.large to m5.2xlarge. The content store application currently runs with 15 workers and a large volume of requests quickly leads to CPU exhaustion ( as m5.large only has 2 vCPUs). This can cause increase latency in response times as requests wait for CPU cycles. An m5.2xlarge has 8 vCPUs which in load testing has improved throughput and latency.
=> Increase content store instance size

terraform/projects/app-mapit/main.tf, terraform/projects/infra-public-services/main.tf
This adds a query string so the health checks bypass the Ngnix cache and monitor the application.
=> Update Mapit ELB health checks

terraform/projects/infra-security/main.tf
fixes #1412 `role_platformhealth_poweruser_user_arns` is duplicated. The second instance of should have been `role_poweruser_user_arns`.
=> fix duplicated `role_platformhealth_poweruser_user_arns`

terraform/modules/aws/iam/gds_user_role/main.tf
The max default ttl is 1 hour but before roles could be up to 8 hours. This PR set the new gds roles to have the same ttl.
=> increase max ttl for new gds roles

terraform/projects/infra-google-mirror-bucket/main.tf
This PR syncs GCS mirror buckets from S3 mirror buckets later. The mirrorer machine is configured/dimensioned to finish mirroring before 08 00 in the morning. The S3 sync from the the mirrorer machine takes on average 8 hours.
Hence we should start no earlier than 16 00. We add some extra hours to take into account for undercertainty in the duration of the crawling and syncing and also increase in number of assets/web pages on GOV.UK.
=> sync gcs later

terraform/projects/app-mapit/README.md, terraform/projects/app-mapit/main.tf, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/mapit.tf, terraform/projects/infra-security-groups/outputs.tf
Mapit currently runs memcached per instance of mapit. This decreases our caching ability if we have instance number >= 2. Introducing a shared cache will allow us to scale Mapit if we need to handle load without impacting of cache. It also allows us to pre-warm our cache more easily, as we don't have to pre-warm every instance of Mapit.
=> Add a shared elasticache instance for Mapit

terraform/projects/app-mapit/README.md, terraform/projects/app-mapit/main.tf
Mapit currently runs with 12 workers and Postgres on each instance. CPU exhaustion can been seen when handling a high number of uncached requests. Increasing the instance size from 2vCPUs to 8vCPUs should improve the number of uncached requests handled.
To this we need to scale up the number of instances from 2 to 4, so we have can rotate the old instances without downtime.
=> Scale up Mapit instance size and number

terraform/projects/app-mapit/main.tf
This upgrade the EBS volume types fro gp2 to gp3, which provide better performance for less money.
=> Use gp3 EBS volume types for Mapit

terraform/projects/app-mapit/README.md, terraform/projects/app-mapit/main.tf
Upgrading the instance size from a burstable t3.xlarge to more reliable non-burstable c5.2xlarge instance type.
=> Scaling up Mapit instance size to c5.2xlarge

terraform/projects/app-data-science-data/main.tf, terraform/projects/infra-security/README.md, terraform/projects/infra-stack-dns-zones/README.md
The data generation process now takes longer
and the data wasn't ready in time for
knowledge-graph machines.
This fixes that by starting the data generation
process earlier
Trello: https://trello.com/c/6TnYiqdo/837-productionalise-external-link-extraction
=> Change time of data-science-data_schedule-spin-up

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
The account machine class is accessible as "account", but it'll also
be running the "account-api" application, which Plek will expect to
find at "account-api.{domain}":
```
irb(main):001:0> Plek.find("account-api")
=> "https://account-api.integration.govuk-internal.digital"
```
---
[Plan](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/924/console)
=> Add account_internal_service_cnames

terraform/projects/app-account/main.tf
This ensures that the app is up and running, not just that the
instance is.
```
michaelswalker@ec2-integration-blue-account-ip-10-1-4-18:~$ curl localhost/_healthcheck_account-api
{"status":"ok","checks":{"database_connectivity":{"status":"ok"}}}
```
---
[Plan](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/931/console)
=> Use app healthcheck for account ELB healthcheck

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/backend.tf, terraform/projects/infra-security-groups/outputs.tf, terraform/projects/infra-security-groups/sidekiq-monitoring.tf
Adds an application load balancer for the our Sidekiq Monitoring app.
Sidekiq monitoring resides on the backend instances, but we only want to
be able to access it externally via the VPN (office_ips).
Taken inspiration from: https://github.com/alphagov/govuk-aws/commit/6e60f91a27d40c886f39409e2a15887ff09dfeb7.
Trello:
https://trello.com/c/m8O8dC41/2414-add-dns-for-sidekiq-monitoring
=> Add Sidekiq Monitoring load balancer

terraform/projects/infra-security/README.md, terraform/projects/infra-security/hmggds.govuk.backend, terraform/projects/infra-security/main.tf
Previously this account did not have its IAM managed in code, which
means we tend to have to use the root account creds to access it.
This brings it into line with GOV.UK's other AWS accounts.
https://github.com/alphagov/govuk-aws-data/pull/862 needs to be merged first.
Note: I've already applied this terraform, so you can test that it works by using one of the new roles in the console (e.g. sign in to gds-users, then switch role to 605357578900 / `firstname.lastname-admin`). gds-cli doesn't have support for this account yet - I'll do a follow up PR for that.
=> Allow infra-security to run against the hmggds account

terraform/projects/app-data-science-data/main.tf
It's finishing after the knowledge graph
has started so not all data is being
imported. This should fix that.
=> Update data science data generation schedule

terraform/projects/app-account/main.tf, terraform/projects/app-bouncer/main.tf, terraform/projects/app-content-store/main.tf, terraform/projects/app-draft-content-store/main.tf, terraform/projects/app-email-alert-api/main.tf, terraform/projects/app-publishing-api/main.tf, terraform/projects/app-router-backend/main.tf, terraform/projects/app-search/main.tf, terraform/projects/app-whitehall-backend/main.tf, terraform/projects/app-whitehall-frontend/main.tf, terraform/projects/infra-public-services/main.tf
Currently govuk-aws healthchecks an app with the `/_healthcheck_app-name` endpoint, which is a liveness check (it always returns a status of 200) which communicates readiness data in the response body.  [RFC 141][] splits those responsibilities out, giving separate liveness healthchecks (which always return a 200) and readiness healthchecks (which return a 200 or a 500).
We use a mix of ELBs and ALBs in govuk-aws.  These have different behaviour in the case where every instance of an app fails its healthcheck:
- ELBs reject traffic until some instances become healthy again (fail-closed).
- ALBs ignore the healthcheck and send traffic to random instances (fail-open).
The fail-open behaviour is better, because it means that a misconfigured healthcheck or transient but non-critical problem …
=> Use liveness healthchecks for ELBs, readiness healthchecks for ALBs

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/backend.tf, terraform/projects/infra-security-groups/mapit.tf, terraform/projects/infra-security-groups/support-api.tf
The ITHC team have asked for access to content-data, mapit, and support-api via HTTPS.  There doesn't seem to be a file for content-data, but it runs on the backend machines.
I don't really understand how these security rules work (for instance, where does it specify what the ITHC security groups actually have access to?), so I'm not sure if these are right.
=> Give ITHC HTTPS access to content-data, mapit, and support-api

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/mapit.tf, terraform/projects/infra-security-groups/support-api.tf
HTTPS rules need to belong to a security group which is attached to a
load balancer, which the previous groups weren't.  Since we already
have security groups attached to the public load balancers (defined in
infra-public-services), I've added the rules to them.
=> Fix ITHC HTTPS access for mapit and support-api

terraform/lambda/ArtefactSync/main.py, terraform/projects/infra-artefact-bucket/main.tf
AWS are deprecating the support for lambdas running Python 2.7 on the 15th July 2021, so this lambda needs updating to Python 3.
All other Python 2.7 lambdas are no longer needed, so will be removed in https://github.com/alphagov/govuk-aws/pull/1439.
Trello card: https://trello.com/c/7uaFnYGD
=> Upgrade ArtefactSync lambda to Python 3.8

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
this fixes https://github.com/alphagov/govuk-aws/commit/404c03c45265f6b07ff29257bc25ccabdb37f16e where new mapit instances 3 and 4 were added to the infrastructure but no logic was included to add them to the Mapit load balancer/target group
=> fix new mapit 3 and 4 not being added to the Mapit loadbalancer/target group

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/account.tf
This is safe because all the API endpoints are protected by Signon
bearer tokens.
---
Plans:
- [infra-public-services](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1309/console)
- [infra-security-groups](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1308/console)
[Trello card](https://trello.com/c/6CsImbRT/817-make-account-manager-able-to-communicate-with-account-api)
=> Set up public load balancer for account-api

terraform/projects/infra-public-services/main.tf
This was previously using /metrics, which wasn't mapped through nginx so was always failing with 500 'fell through to default vhost'.
The internal LB is already set to use `/-/ready`.
Requires alphagov/govuk-puppet#11187.
=> Use the Prometheus readiness endpoint for the LB healthcheck.

terraform/projects/app-prometheus/README.md, terraform/projects/app-prometheus/main.tf
This enables us to add more timeseries storage space in prod, which was running out.
gp3 is cheaper and faster, so no reason not to use it.
=> Make Prometheus storage volume configurable and upgrade to gp3.

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/backend-redis.tf
This is necessary now that account-api is using sidekiq for background
job processing.
---
[Trello card](https://trello.com/c/uRW8OS61/907-move-expired-authrequest-deletion-to-sidekiq)
[Plan](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1350/console)
=> Give account access to the backend-redis

terraform/userdata/00-base
It might be a bit tinfoil hat to consider how downloading puppet's GPG
key over a plaintext connection could lead to a vulnerability, but it
seems like a good idea to download it over HTTPS since that seems to be
available.
Confirmed that it's the same key:
```
cmp <(curl --silent 'http://apt.puppetlabs.com/DEB-GPG-KEY-puppet-20250406') <(curl --silent 'https://apt.puppetlabs.com/DEB-GPG-KEY-puppet-20250406')
```
=> Download puppetlabs GPG key over https

terraform/projects/app-knowledge-graph/userdata-sandbox.tpl, terraform/projects/app-knowledge-graph/userdata.tpl
Newer versions drop support for python 2.7
We should migrate from python 2.7 as
its EOL
=> Pin awscli version

terraform/modules/aws/elasticache_redis_cluster/README.md, terraform/modules/aws/elasticache_redis_cluster/main.tf, terraform/projects/app-backend-redis/README.md, terraform/projects/app-backend-redis/main.tf
So that we can override for production with a different value in [govuk-aws-data](https://github.com/alphagov/govuk-aws-data/pull/889).
Due to increased memory usage caused by data.gov.uk recently which triggered an incident. This may get reduced once the underlying excessive memory consumption is addressed.
=> Add overrides for instance type and number of nodes for redis

terraform/modules/aws/elasticache_redis_cluster/README.md, terraform/modules/aws/elasticache_redis_cluster/main.tf, terraform/projects/app-backend-redis/README.md, terraform/projects/app-backend-redis/main.tf
This enables us to run different redis engine versions per environment.
I've kept the default in govuk-aws the same. There is a
corresponding govuk-aws-data PR to enable us to set the
parameter per environment: https://github.com/alphagov/govuk-aws-data/pull/893.
Once this is merged we'll be able to upgrade Redis in each environment.
Testing: 
```
gds govuk terraform -b bilbof/redis-version -d bilbof/redis-version -a plan -e integration -s blue -p app-backend-redis -r govuk-integration-admin -u <github_username>
```
Test output:
```
No changes. Infrastructure is up-to-date.
```
https://trello.com/c/ft2pX8p2/603-redis-cluster-upgrade
=> Parameterise app-backend-redis redis_engine_version

terraform/modules/aws/elasticache_redis_cluster/README.md, terraform/modules/aws/elasticache_redis_cluster/main.tf, terraform/projects/app-backend-redis/README.md, terraform/projects/app-backend-redis/main.tf
This was incorrectly ommitted when setting redis_engine_version in
a previous commit - we need to update both the parameter group name
and the engine version name at the same time.
=> Add redis_parameter_group_name variable to aws/elasticache_redis_cluster

terraform/modules/aws/iam/gds_user_role/README.md, terraform/modules/aws/iam/gds_user_role/main.tf, terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
This PR updates the `gds_user_role` module to output a map containing the role name and role ARN for each created role.
For example, creating a role of `*-admin` will output all of the generated role names and ARNs in a map of the format:
```
{
...,
'joe.bloggs-admin': 'arn:aws:iam::123467890123:role/joe.bloggs-admin',
...,
}
```
This is being used in `infra-security` to output the role names and ARNs when creating `admin`, `poweruser` and `user` roles, allowing us to use this when creating resources elsewhere, such as in our new EKS cluster.
=> Output role names and ARNs for roles created via gds_user_role module

terraform/projects/infra-root-dns-zones/test.govuk.backend
The outputs from this module are needed in order to keep the new [govuk-infrastructure](https://github.com/alphagov/govuk-infrastructure) Terraform DRY.
Requires alphagov/govuk-aws-data#918.
[Trello card](https://trello.com/c/hqCr1ozs/625)
Tested: already applied, produced no diff and generated the expected outputs to match the existing zones in the test account.
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:
external_root_domain_name = test.govuk.digital.
external_root_zone_id = (redacted)
internal_root_dns_validation_zone_id = (redacted)
internal_root_domain_name = test.govuk-internal.digital.
internal_root_zone_id = (redacted)
```
=> Add backend config for infra-root-dns-zones in test account.

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/ci-master.tf, terraform/projects/infra-security-groups/main.tf
Fix GitHub IP Ranges Returning IPv6
The GitHub provider is returning IPv6 IPs in addition to IPv4
IPs for the hooks. This is not compatible with AWS security
rules which require IPv4 and IPv6 IPs to be seperate.
This is a [fixed bug](integrations/terraform-provider-github#883)
in 4.14 version of the provider.
=> fix GitHub IP range returning IPv6

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
A policy attachment was referring to a role created in the same TF module by name, defeating TF's ability to infer the dependency and causing first-time apply to fail.
Instead of duplicating the policy name, refer to it by ARN so that the graph can be inferred correctly.
Fixes #1466.
TF plan in integration:
- resource "aws_iam_role_policy_attachment" "datascience_pass_step_function" {
- id         = "govuk-datascienceusers-20210813..." -> null
- policy_arn = "arn:aws:iam::...:policy/govuk-pass-step-function-role" -> null
- role       = "govuk-datascienceusers" -> null
}
+ resource "aws_iam_role_policy_attachment" "user_policy_attachment" {
+ id         = (known after apply)
+ policy_arn = "arn:aws:iam::...:policy/govuk-pass-step-function-role"
+ role       = "govuk-datascienceusers"
} …
=> Fix a dependency ordering issue between datascience IAM resources.

terraform/projects/app-data-science-data/main.tf
We think it was running out of memory
and the larger size seems to work.
=> Increase data generation machine spec

terraform/modules/aws/lb/README.md, terraform/modules/aws/lb/main.tf, terraform/projects/infra-public-services/main.tf
This was set at 60 seconds, which was too low for some queries to `hmrc-manuals-api`, therefore increasing to be consistent with other load balancers.
[Zendesk ticket](https://govuk.zendesk.com/agent/tickets/4712404)
=> Increase backend-public ALB timeout to 400 seconds

terraform/projects/app-knowledge-graph/main.tf
The knowledge graph is set to shut down at 17:30 GMT, which is a bit early
for some users (6:30p during summer time, 5:30p otherwise). So we're extending
by 2 hours so users can access it later.
=> Keep the Knowledge Graph running 2 hours longer

terraform/projects/app-ci-agents/README.md, terraform/projects/app-ci-agents/main.tf
gp3 is 20% cheaper than gp2 and includes 3000 IOPS at any size instead of 3 IOPS/GB. This should speed up builds at least a bit.
While we're there, define the values once instead of copy-pasting.
The volumes can be upgraded in place without downtime.
=> Use cheaper and faster gp3 storage for CI agent EBS volumes.

terraform/projects/infra-database-backups-bucket/main.tf
We've taken a snapshot of the account-manager[1] and
attribute-service[2] databases before terminating the apps.  This is
in case we need to refer to any historic data (most likely the audit
log in the security_activities table, which didn't get migrated to
Digital Identity). We've said in our privacy policy that we keep user
data for two years, so we should get rid of the data at that point.
[1] https://github.com/alphagov/govuk-account-manager-prototype
[2] https://github.com/alphagov/govuk-attribute-service-prototype
---
[Plan](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1650/console)
[Trello card](https://trello.com/c/OcGZ4Wys/1124-take-snapshots-of-the-pre-migration-databases)
=> Set a two-year expiration time on the GOV.UK accounts backup

terraform/projects/app-content-data-api-postgresql/README.md, terraform/projects/app-content-data-api-postgresql/main.tf, terraform/projects/app-transition-postgresql/README.md, terraform/projects/app-transition-postgresql/main.tf
https://trello.com/c/ybS7Dnns/41-upgrade-the-legacy-m4-database-machine-instances
These are being updated because the m4 instance class is legacy and will
not support newer versions of PostgreSQL. So this is a pre-requisite
before the Databases on these instances can be upgraded to newer
versions of PostgreSQL.
As I understand, we don't use a "apply_immediately" flag in our RDS
configuration so this change will take effect during the next
maintenance window - which will be early Monday morning.
=> Change m4 DB instances to m5

terraform/projects/infra-ask-export/README.md, terraform/projects/infra-ask-export/integration.govuk.digital, terraform/projects/infra-ask-export/main.tf
Trello: https://trello.com/c/pmiW3jZk/249-tech-spike-ask-contingency-plan-port-the-script-we-run-on-concourse-to-jenkins
Pairs with: https://github.com/alphagov/govuk-aws-data/pull/941
This sets up a conditional terraform command to create an S3 bucket. It
has been introduced so that the GOV.UK integration environment can have
a test mechanism to run the Ask export.
The prompt for adding this was the retirement of big Concourse, which
has led to the export process being moved to Jenkins. The team need a
method to try the system out before configuring the production one.
---
I wasn't 100% sure whether the syntax for a boolean was conventionally `true` or `"true"` - I could see examples of both in this project. 
Is the convention to have a PR merged before running a plan or to wait until …
=> Ask export can create a bucket

terraform/projects/infra-ask-export/README.md, terraform/projects/infra-ask-export/main.tf
It turns out the terraform version we use, 0.11, has no concept of a
boolean and needs to be defined as a string in the type declaration.
This fixes that issue.
I did _finally_ work out to do a plan of a working branch so I'm finally
confident this works.
=> Fix terraform boolean

terraform/projects/app-apt/README.md, terraform/projects/app-apt/main.tf, terraform/projects/app-ci-master/README.md, terraform/projects/app-ci-master/main.tf, terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
Making `elb_public_secondary_certname` optional by adding an empty
string as default value. This will allow use to "migrate" from
using 2 certificate to only one certificate on the load balancers.
Ref:
1. [lb secondary cert code](https://github.com/alphagov/govuk-aws/blob/498581043d26e4e4e3474edf5d1718ad735f589f/terraform/modules/aws/lb/main.tf#L196)
=> Make elb_public_secondary_certname optional

terraform/projects/app-related-links/README.md, terraform/projects/app-related-links/main.tf
This PR fixes the SSH public key used as the key pair for the EC2 instance running related links, so that it uses the correct key for the particular environment (previously it was hardcoded to the integration SSH public key).
=> Provision related links with correct Jenkins SSH public key

terraform/projects/app-mysql/main.tf, terraform/projects/app-postgresql/main.tf
Trello: https://trello.com/c/OFuRPguC/35-investigate-whether-aws-dms-is-a-suitable-tool-for-large-postgresql-databases
This applies the configuration that AWS suggest (and what I've been using in the test environment) to our multi-tenant RDS instances so that they can be used as source database endpoints for DMS (Database Migration Service). The intention is to use this to start experiments migrating some of the bigger databases we host to gain confidence that this will be successful in production as a tool to minimise user downtime.
The PostgreSQL change is going to require a reboot to take effect and the MySQL one requires an additional manual query to be run.
More details in the commits.
=> Configure postgresql-primary and mysql-primary for DMS replication

terraform/projects/app-govuk-rds/rds.tf
"${engine}${version}" works for postgres, as the family name is
"postgres13", but it doesn't work for mysql, as the family name is
"mysql8.0" rather than "mysql8".
---
[Trello card](https://trello.com/c/rB7CoPoG/42-terraform-up-all-the-new-rds-instances-and-db-admin-ec2-instances)
=> Allow specifying RDS engine parameter group family

terraform/projects/app-account/main.tf, terraform/projects/app-backend/main.tf, terraform/projects/app-ckan/main.tf, terraform/projects/app-data-science-data/main.tf, terraform/projects/app-email-alert-api/main.tf, terraform/projects/app-publishing-api/main.tf, terraform/projects/app-whitehall-backend/main.tf, terraform/projects/app-whitehall-frontend/main.tf
Incorrect syntax for the old version of terraform + the stackname for app-data-science-data.
Plans:
- [app-account](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1887/console)
- [app-backend](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1888/console)
- [app-ckan](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1889/console)
- [app-data-science-data](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1897/console)
- [app-email-alert-api](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1892/console)
- [app-publishing-api](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/1893/con …
=> Fix references to new RDS security groups

terraform/projects/app-govuk-rds/rds.tf
This is the name of the snapshot to create the database from - not, as
I thought, the name it'll use to create snapshots.  We're not creating
these databases from snapshots, so creation is failing because they
don't exist.
---
[Trello card](https://trello.com/c/rB7CoPoG/42-terraform-up-all-the-new-rds-instances-and-db-admin-ec2-instances)
=> Do not set snapshot identifier for RDS instances

terraform/projects/app-data-science-data/userdata.tpl
The data generation process (used by the Knowledge Graph) is currently broken without any diagnostics in the logs.
So we're adding stderr to the log to see what's happening.
=> Also log stderr

terraform/projects/app-data-science-data/README.md, terraform/projects/app-data-science-data/main.tf
The app needs the bigquery credentials in order to compute the "structural network" using user journey data.
=> Allow the data science data app to get bigquery credentials

terraform/projects/app-data-science-data/README.md, terraform/projects/app-data-science-data/main.tf
`read_secrets_from_secrets_manager_policy` was already defined in `app-related-links/main.tf` so we're namespacing the policy and attachment names by prefixing them.
=> Add prefix to avoid clash with app-related-links

terraform/projects/app-deploy/README.md, terraform/projects/app-deploy/main.tf, terraform/projects/app-deploy/remote_state.tf, terraform/projects/app-search/README.md, terraform/projects/app-search/main.tf
This give Jenkins IAM permissions to scale the Search API's learn to rank autoscaling group. This is need for the Jenkins job to train and deploy a new learn to rank model.
=> Add scale learn to rank ASG policy to Jenkins

terraform/projects/app-transition-postgresql/main.tf
This has now been updated.
Trello: https://trello.com/c/c869iqyh/68-plan-production-upgrade-for-transition
=> Update Terraform for Transition: Postgres 9.6 => 13

terraform/projects/app-backend/README.md, terraform/projects/app-backend/main.tf
The backend machine class runs apps with each type of database, but we
have only created the postgres instances in production and staging
currently.
As expected, this is a no-op on integration with the relevant govuk-aws-data branch:
https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2008/console
=> Add separate variables for split postgres & msyql databases

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/search-ltr-generation.tf
This rule enable SSH ingress from the Jenkins (deploy) instance. This is needed as the learn to rank (LTR) Jenkins job needs SSH access into new instances.
=> Add Jenkins ssh ingress SG rule for LTR ASG instances

terraform/projects/app-search/README.md, terraform/projects/app-search/main.tf
This updates the AMI id to use Ubuntu 20.04 instead of Ubuntu 18.04 for instances used for Search API's Learn to rank process. Using a newer version of Ubuntu as it comes pre-packaged with Python 3.8 which is required by the train and deployment scripts.
=> Use Ubuntu 20.04 for LTR ASG instances

terraform/projects/app-govuk-rds/db_admin.tf
The tag is called "Name" not "name" - this matches the legacy db-admin
machines and the behaviour of the node_group module.  Changing the
tags of one of the new db-admin instances through the AWS console
makes the name show up in the instance list.
[Terraform plan](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2035/console)
---
[Trello card](https://trello.com/c/ZxgxywAY/91-new-db-admin-machines-dont-have-a-name-in-aws-ec2)
=> Correctly set name for new db-admin instances

terraform/projects/app-search/main.tf
This updates the instance role for instances created in the Learn to rank ASG to an existing role with correct permissions for accessing the SageMaker and the relevant S3 buckets.
=> Update the instance role for LTR instances

terraform/projects/app-account/README.md, terraform/projects/app-account/main.tf, terraform/projects/app-backend/README.md, terraform/projects/app-backend/main.tf, terraform/projects/app-ckan/README.md, terraform/projects/app-ckan/main.tf, terraform/projects/app-data-science-data/README.md, terraform/projects/app-data-science-data/main.tf, terraform/projects/app-email-alert-api/README.md, terraform/projects/app-email-alert-api/main.tf, terraform/projects/app-publishing-api/README.md, terraform/projects/app-publishing-api/main.tf, terraform/projects/app-whitehall-backend/README.md, terraform/projects/app-whitehall-backend/main.tf, terraform/projects/app-whitehall-frontend/README.md, terraform/projects/app-whitehall-frontend/main.tf
These were introduced so we could create (or not create) the security
group rules only in environments where the new RDS instances had been
deployed.  We now have all the new RDS instances, so these variables
are unnecessary.
---
Terraform plans (all no-ops):
- [app-account](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2094/console)
- [app-backend](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2095/console)
- [app-ckan](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2096/console)
- [app-data-science-data](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2102/console) (has an unrelated launch configuration change)
- …
=> Remove use_split_database variables

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
This var is not used - the list tfvar provided by aws-data is now empty - see https://github.com/alphagov/govuk-aws-data/pull/965.
=> Remove unused var from infra-security

terraform/projects/app-search/README.md, terraform/projects/app-search/main.tf, terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/search-ltr-generation.tf, terraform/projects/infra-security-groups/variables.tf
This removes permissions for the shared concourse to access resources needed to run Search API's learn to rank pipeline. This is because the pipeline has now been migrated to Jenkins.
=> Remove concourse permissions for LTR resources

terraform/projects/app-postgresql/main.tf
Set skip final snap shot to true to allow module to be deleted as otherwise the destroy action is prevented:
https://trello.com/c/ewzHAr6A/56-remove-postgresql-primary-and-postgresql-standby-infrastructure-and-configuration
https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2137/console
=> Skip final snap shot for postgres replica

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/outputs.tf
The postgres primary is to be removed see https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/2139/ so the ID is not available for the output. Removing this allows us to remove the postgres primary resources from the infra-security group.
https://trello.com/c/ewzHAr6A/56-remove-postgresql-primary-and-postgresql-standby-infrastructure-and-configuration
=> Remove ID from outputs file

terraform/projects/infra-security-groups/mysql.tf
These are no longer required, so we'll delete them.
Once these Terraform changes have been applied, we can then delete
the mysql.tf file.
Trello: https://trello.com/c/VWpD8SvY/55-remove-mysql-primary-and-mysql-standby-infrastructure-and-configuration
=> Set a count of 0 on mysql-primary resources

terraform/projects/infra-database-backups-bucket/README.md, terraform/projects/infra-database-backups-bucket/main.tf
This PR simplifies the lifecycle rules on the S3 buckets which hold database backups created by env_sync.
Previously, various retention rules were needed on different paths within the bucket. This reflected the fact that the bucket was being used to store lots of different types of backup.
We made the decision to simplify the purpose of this bucket so that it's only used to store env_sync database dumps.
We now have one lifecycle rule which is applied to the entire bucket.
Given the current configuration, this means:
- Production backups will be permanently deleted after 121 days ('soft deleted' after 120 days and 'hard deleted' the next day)
- Staging & integration backups will be permanently deleted after 4 days ('soft deleted' after 3 days)
This database backups bucket (and its replica …
=> Simplify lifecycle rules for database backups

terraform/projects/infra-monitoring/main.tf
The `govuk-{env}-aws-logging` buckets have a 30 day expiration policy, but also had versioning enabled. This means that files are only soft deleted after 30 days, and continue to exist in the background as old versions taking up storage space.
The straightforward approach would be to disable versioning on the bucket so that files are permanently deleted when they expire. However versioning needs to remain enabled on the bucket because there is a replica configured.
Instead, this change configures a non-current version expiry so that old versions of files are permanently deleted after 1 day.
In real terms, this means that files will be permanently deleted from the bucket after 31 days (expiring at 30 days, and being deleted 1 day later).
=> Permamently delete items in aws-logging buckets

terraform/modules/aws/lb/README.md, terraform/modules/aws/lb/main.tf
Trello: https://trello.com/c/C9hginSe/166-remove-tls-10-and-11-support-for-publishing-apps
This changes the default TLS security policy used in the application
load balancers to be a newer rule that drops support for TLS 1.0 and
1.1.
As no ALBs set a non-default listener_ssl_policy this rule will apply to
all of the public ALBs in GOV.UK infrastructure. So this will apply to
anything on publishing.service.gov.uk which is not behind the CDN (www,
assets and transition sites). I decided that it'd be better to apply
this broadly rather than individually as this change has been something
that has been put off for a while and it'd be good to set any exceptions
based on reasoning rather than caution.
This has been done because TLS versions below 1.2 are susceptible to
man-in-the-middle attacks …
=> Drop TLS 1.0 and 1.1 support from ALB's

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
As part of the AWS Shield Advanced offering, there is a "Shield Response
Team" who can help out during an incident.
Unlike ordinary AWS support, this team can be given permission to access
certain APIs to help out directly during the incident (rather than just
providing advice).
To make it easier to enable this during an incident, this commit adds a
role which includes the recommended permissions. This can be selected
from the AWS Console, under the option "Choose an existing role for the
SRT to access my accounts."
We'll document how to enable this in the developer docs.
Note that most of the access this role gives is List / Describe / Get
level. The more highly privileged actions are all on shield / waf / elb
/ cloudfront resources.
=> Add Shield Response Team IAM role

terraform/projects/app-jumpbox/README.md, terraform/projects/app-jumpbox/main.tf
We'd like to ship SSH logs to Cyber. The standard way of doing this is
to ship the logs to CloudWatch Logs first, and then use Cyber's
[centralised security logging service](https://github.com/alphagov/centralised-security-logging-service)
This commit grants the jumpboxes permission to use CloudWatch.
https://trello.com/c/3PEIdbKp/2608-ship-ssh-logs-from-jumpboxes-to-splunk
=> Allow jumpboxes to use CloudWatch

terraform/projects/app-search/README.md, terraform/projects/app-search/main.tf
This is needed so that search-api in EKS is able to access
these buckets.
=> Output the policy used to access the search-api s3 buckets

terraform/projects/infra-security/main.tf
This is so a sagemaker user can create internal sagemaker git repositories, needed for some applications to run.
See https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateCodeRepository.html
=> Add sagemaker:CreateCodeRepository to infra-security

terraform/projects/app-data-science-data/main.tf, terraform/projects/app-knowledge-graph/main.tf
By default the time zone is GMT so during summer time the govgraph is
generated one hour later (09:30) and isn't available to users early enough.
So adding the Europe/London IANA time zone parameter, as documented at
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_schedule\#argument-reference
=> Specify time zone for daily govgraph generation

terraform/projects/app-data-science-data/main.tf, terraform/projects/app-knowledge-graph/main.tf
The version of terraform currently used in this repo (0.11.15) doesn't support `time_zone` so instead we're changing the generation and start time to an hour earlier
=> no time_zone support so start sooner

terraform/projects/app-knowledge-graph/userdata.tpl
The Knowledge Graph instance (that we start every morning) used to do some 
data processing (like some elegibility experiments, or the brexit spreadsheet)
using Python3.7. But that version of python is no longer available on the old neo4j 
AMI we use. So we removed all python code and moved some of it to the Data Science
Data app where it belongs anyway, since that app computes most of the Knowledge Graph data already.
Since no python code is being run on the KG instance, we're removing all the python installation commands, to avoid seeing errors and keeping unnecessary code in there.
=> Knowledge graph: remove python setup code

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-public-services/waf.tf
Currently, Locations API's internal DNS only allows connections
through the 'blue' stack:
```
$ curl https://locations-api.integration.govuk-internal.digital
curl: (6) Could not resolve host: locations-api.integration.govuk-internal.digital
$ curl https://locations-api.blue.integration.govuk-internal.digital
(resolves)
```
Other APIs (including email-alert-apil, publishing-api and
account-api) are only available on the non-blue domain. This
commit (taken from Account API config) is to make Locations API
consistent with that.
Trello: https://trello.com/c/gPRVvLXh/2848-set-up-remaining-infrastructure-for-locations-api-5
=> Add Route53 record for internal Locations API DNS

terraform/projects/app-content-store/README.md, terraform/projects/app-content-store/main.tf, terraform/projects/app-draft-content-store/README.md, terraform/projects/app-draft-content-store/main.tf, terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
During the migration from Carrenza to AWS some communication was needed between pat of the infrastructure in AWS and the part that was still running in Carrenza. Hence the need for public facing load balancers for services that would normally not require them.
Now that nothing is left running in Carrenza we can get rid of this vestigial infrastructure.
See also https://github.com/alphagov/govuk-aws-data/pull/1010
=> Remove obsolete public facing load balancers

terraform/projects/app-deploy/README.md, terraform/projects/app-deploy/main.tf, terraform/projects/app-deploy/user_data_snippets.tf, terraform/projects/infra-govuk-repo-mirror/README.md, terraform/projects/infra-govuk-repo-mirror/main.tf
Depends on https://github.com/alphagov/govuk-aws-data/pull/1022
These are the minimum changes required to move the repository
mirroring pipeline out of Concourse and into Jenkins. Whilst we
could go down the route of creating a brand new user and role
for Jenkins, the existing pipeline is quite tightly coupled to
the Concourse user/role and existing SSH keys, so is best left
as-is:
https://docs.publishing.service.gov.uk/manual/github-unavailable.html
We can look at removing outdated config and renaming away from
'Concourse' later once the new pipeline is working.
Trello: https://trello.com/c/QlPzhn6A/2814-move-code-repository-mirroring-off-of-concourse
=> Allow Jenkins to assume the govuk-codecommit-poweruser role

terraform/projects/app-deploy/main.tf
In #1579, the new resources should be created only in integration.
This PR fixes where some of the resources would have been
created in staging and be superfluous.
=> Fix #1579 by conditioning some additional resources

terraform/projects/app-deploy/README.md, terraform/projects/app-deploy/main.tf, terraform/projects/infra-govuk-repo-mirror/README.md, terraform/projects/infra-govuk-repo-mirror/main.tf
1. create in Tools a SSH user that the govuk-repo-mirrorer script will
use
2. change IAM permissions so that the govuk-repo-mirrorer script can
run in production only because integration has too wide access
Trello: https://trello.com/c/QlPzhn6A/2814-move-code-repository-mirroring-off-of-concourse
=> Create SSH user for govuk-repo-mirrorer and switch to script to production

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
In #1412, a role is created for each user per GOV.UK privilege
category. This was done as a workaround to the size limit of a
role in ARN where we can't create a single role per GOV.UK
privilege category and add in all the users of that category in.
As a temporary measure, we left the legacy roles there but now
we hit again that limit so it's time to remove these legary
roles. Developers had time to switch to their new roles now.
=> Remove legacy roles

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf, terraform/projects/infra-public-services/waf.tf, terraform/projects/infra-public-services/waf_test_rule.tf
This PR has three sections:
- converting the existing "classic" WAF to WAFv2 and applying it to the public cache LB as an example
- converting the other LBs that use the existing WAF to use the new WAF (and removing the old one)
- adding the new WAF to the public LBs that did not have anything applied
This is a stepping stone to make it easier to configure specific WAF configurations to each LB that needs it. The next step is to configure separate WebACLs for each LB that needs different configuration.
There is further context in each commit.
https://trello.com/c/IvZrVCL3/2869-setting-rate-limits-within-aws-waf
=> Sort out WAF baseline on public LBs

jenkins.sh
Before there was a regex in Jenkins which interpreted `Plan ..`
as unstable builds. This is incorrect with newer versions of
Terraform which displays this line when doing applies with changes.
We now make terraform plan with detailed-exitcode so that it exits
with 2 when there are changes in the plan and Jenkins will mark the
build as unstable.
=> Set detailed exit status for terrform plans

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
These IDs will be referenced from a separate project which will configure the web acls for the public load balancers. The resources we're outputting are:
- IDs of public load balancers
- the ID of the existing kinesis data firehose
The load balancer IDs will be used in the new project to attach the new web ACLs to the public load balancers.
The kinesis data firehose is used to [send the logs generated by the new WAFs to S3.](https://aws.amazon.com/premiumsupport/knowledge-center/waf-configure-comprehensive-logging/).
This happens at present with the default web ACL, but the plan is to move that configuration out of the extremely large infra-public-services project into something a bit more easily manageable. 
We'll reuse this kinesis data firehose instance for the moment, until we need to …
=> Output the IDs of infra-public resources

terraform/projects/infra-public-services/waf.tf
This is set again two lines further down. It looks like the second time
wins, because the bucket in integration is called
govuk-integration-aws-waf-logs.
=> Remove duplicate bucket parameter

terraform/projects/app-data-science-data/userdata.tpl
If we use a single $ then terraform thinks it's a variable passed to the template
=> Data-science data: Use double-dollar for local variable

terraform/modules/aws/network/nat/README.md, terraform/modules/aws/network/nat/main.tf
The current terraform doesn't work at all. I think it was included by mistake in a previous PR.
This adds the EIPs to the resources covered by AWS shield advanced.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/shield_protection
[Plan of the change adding 3 AWS shield resources](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3097/console)
=> Fix shield advanced on EIP

terraform/projects/app-knowledge-graph/userdata.tpl
So that we get the error messages when the provision_knowledge_graph
script outputs errors to stderr
=> app-knowledge-graph: also log stderr

terraform/projects/app-knowledge-graph/userdata.tpl
instance_id is a local variable defined above, and as such
needs to be instantiated using two dollar signs, as opposed
to pre-set variables that need only one.
=> Use 2 dollar signs to instantiate local variable

terraform/projects/infra-mirror-bucket/README.md, terraform/projects/infra-mirror-bucket/main.tf, terraform/projects/infra-mirror-bucket/mirror-read-policy.tf
[Smokey is currently failing](https://alert.production.govuk.digital/cgi-bin/icinga/extinfo.cgi?type=2&host=ip-10-13-5-163.eu-west-1.compute.internal&service=Smokey+loop+for+mirror) because the monitoring machine is attempting to use the [new S3 gateway](https://github.com/alphagov/govuk-aws/pull/1605) to retrieve pages from the replica mirror and failing.
Looking at the policies on the bucket, we have locked them down to Fastly, office and AWS NAT ip addresses, none of which are used in this case.
=> Allow monitoring to access the mirror bucket

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
This was missed previously during the Carrenza cleanup.
[The Terraform plan](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3203/console) has been run for `integration`:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy
Terraform will perform the following actions:
- aws_autoscaling_attachment.licensify_frontend_asg_attachment_alb
- aws_lb_listener.licensify_frontend_public_http_80
- aws_route53_record.licensify_frontend_public_service_cnames
- aws_route53_record.licensify_frontend_public_service_names
- aws_route53_record.rate_limit_redis_internal_service_names
- module.licensify_frontend_public_lb.aws_cloudwatch_metric_alarm.elb_httpcode_elb_5xx_count
- …
```
=> Remove public load balancer for licensify-frontend

terraform/projects/app-knowledge-graph/README.md, terraform/projects/app-knowledge-graph/main.tf, terraform/projects/app-knowledge-graph/userdata-dev.tpl, terraform/projects/app-knowledge-graph/userdata.tpl
For testing purposes as the live one now has a substantial
number of users, so it's more awkward if we break it as we
test changes.
=> Create a second instance of the knowledge graph

terraform/projects/infra-public-services/main.tf
This feels like the best place to document that uploadlicence.publishing.service.gov.uk
is still in use. See [this incident review](https://docs.google.com/document/d/178xHfacEiYn64607tc7Ab-_F8EMOjAUlKPB7dJWg6nU/edit#) for more information.
Trello card: https://trello.com/c/u6p9k6It/2909-investigate-why-licensing-frontend-is-publicly-routable-and-hide-it-if-possible5
=> Add comment about uploadlicence domain

terraform/projects/infra-vpc/README.md, terraform/projects/infra-vpc/main.tf
We've been trying for a long time to get Civica to update their ACLs to allow our AWS environments to make API calls to their infrastructure, on behalf of GOV.UK Licensing's local authority users.
We're starting to see some promising signs that they might finally do this, and we want to make sure that we've got a reasonably future proof set of IP addresses to give them.
Currently, API calls to Civica go through a VPN that runs to UK Cloud.
We'd like to remove this, and have API calls go through the NAT Gateways in our production and staging VPCs. There are three NAT gateways in both environments, so we have 6 IP addresses which need to be allowlisted.
In the future, there's a high chance we'll want to move Licensing into its own VPC (or possibly its own AWS account). If this happens, …
=> Allocate EIPs for future use by GOV.UK Licensing

terraform/projects/app-transition-db-admin/README.md, terraform/projects/app-transition-db-admin/main.tf
This grants access for the staging and integration DB admin machines to
read the production transition database backups. It is required for
their overnight env-sync tasks [1] [2].
The lack of this is preventing integration from syncing databases
overnight. Oddly it is working in staging where there seems to be an IAM
role policy added that isn't managed by Terraform.
[1]: https://github.com/alphagov/govuk-puppet/blob/950d713e663b081af763bff46d7db5c4cc4821db/hieradata_aws/class/integration/transition_db_admin.yaml#L2-L13
[2]: https://github.com/alphagov/govuk-puppet/blob/950d713e663b081af763bff46d7db5c4cc4821db/hieradata_aws/class/staging/transition_db_admin.yaml#L2-L13
=> Staging and integration can read production transition backups

terraform/modules/aws/node_group/main.tf
The Canonical AMI we previously depended on is not available
anymore, we've made a copy that we own so that we can continue to
use it. In order to make it findable we add our own owner id to
the search filter.
=> Add our own owner id to the list that images are filtered by.

terraform/projects/app-knowledge-graph/main.tf
Much more data is being loaded into the graph, causing the disk to run out of space.
To enable https://github.com/alphagov/govuk-knowledge-graph/pull/409
=> Double the size of the knowledge graph disk

terraform/projects/infra-public-wafs/README.md, terraform/projects/infra-public-wafs/cache_public_rule.tf, terraform/projects/infra-public-wafs/variables.tf
In integration and staging, production traffic is replayed to some extent. The rate limiting works using the IP address of the request originator, which in the case of traffic replay is limited to a couple of addresses on our side.
This will not affect production, as traffic is not replayed there.
As before, the IP address is provided in a CIDR block format. This is specified already in the [common config](https://github.com/alphagov/govuk-aws-data/blob/main/data/common/staging/common.tfvars#L72)
Temporarily leaving the old IP set in, as it doesn't appear to delete cleanly if all done at once.
Also re-adding metrics for the rules that bypass the rate limiting, as this makes troubleshooting easier
https://trello.com/c/IvZrVCL3/2869-setting-rate-limits-within-aws-waf
=> Allow traffic replay to bypass rate limiting

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
This allows a particular GCP project to read the bucket govuk-integration-database-backups, so that other GCP projects can securely and easily access GOV.UK's data.  The approach has been [discussed](https://docs.google.com/document/d/1Nw7xqXZQn6PIjkB_XsXuAFa2iyN9s6Booi9HxtpyGCE).
The GCP project uses the "Storage Transfer" service to sync a GCP bucket with the AWS bucket.  The service uses a default service account (i.e. one that Google manages).  This pull request allows that service account, identified by its "subject ID", given here as `accounts.google.com:sub`, to assume an IAM role that has permission to read the contents of the AWS bucket.  No keys are required.  See [Google's documentation of this arrangement](https://cloud.google.com/storage-transfer/docs/source-amazon-s3#federate …
=> Allow Google Cloud Platform to read a bucket

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/outputs.tf
The outputted office IPs will then be used in govuk-infrastructure for the GOV.UK EKS Platform.
=> Output office IPs

terraform/projects/infra-cyber-cloudwatch-to-splunk/README.md, terraform/projects/infra-cyber-cloudwatch-to-splunk/main.tf
Cyber are migrating their ingestion lambda because of the deprecation (by AWS) of something their old one relied on.
Here we add another filter pointing at their new lambda. The two will run in parallel for a short time while we confirm that everything's working and to ensure that we don't drop any logs.
https://trello.com/c/IJQFMwki/2984-update-cyber-splunk-endpoint
=> Add a log subscription filter

terraform/projects/infra-cyber-cloudwatch-to-splunk/README.md, terraform/projects/infra-cyber-cloudwatch-to-splunk/main.tf
We've migrated to the new one, so this can be removed.
Corresponds with https://github.com/alphagov/govuk-aws-data/pull/1098
https://trello.com/c/IJQFMwki/2984-update-cyber-splunk-endpoint
=> Remove original Cyber logging filter

terraform/projects/infra-public-services/waf.tf
nodejs10.x is no longer supported.
Node 12 is a supported runtime, however [it's the last on the block](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). 14 and 16 are newer, so we should aim to bump up to those soon.
In the interest of making small changes though, and because we're not amazingly familiar with upgrading lambdas, we'll stick with just getting to a supported version.
I've reviewed [node's changes between 10 and 12, and they all look reasonable.](https://nodejs.org/tr/blog/uncategorized/10-lts-to-12-lts/)
[The lambda itself](https://github.com/alphagov/govuk-aws/blob/main/terraform/lambda/WAFLogTrimmer/lambda.js) is quite simple which makes this process easier to evaluate.
https://trello.com/c/GMYN51xo/2988-bump-waf-logs-lambda-nodejs-version
=> Bump waf logs lambda to supported node version

terraform/projects/app-knowledge-graph/main.tf
GovGraph Search no longer connects via the Bolt endpoint, but uses the http api instead, so we need to open the right port
=> Open the HTTP API for the Knowledge Graph

terraform/projects/infra-public-wafs/README.md, terraform/projects/infra-public-wafs/cache_public_rule.tf, terraform/projects/infra-public-wafs/variables.tf
We  currently use a kinesis firehose to send log entries to Splunk. There's a lambda that runs on each log entry to filter out things that aren't relevant.
Since the kinesis firehose was configured, AWS announced support for native [WAF log filtering](https://aws.amazon.com/about-aws/whats-new/2021/05/aws-waf-adds-support-for-log-filtering/).
If this works as expected, we should eventually be able to ditch [the kinesis/lambda set up](https://github.com/alphagov/govuk-aws/blob/main/terraform/projects/infra-public-services/waf.tf#L67-L101), which will be one less thing for us to worry about keeping up to date.
Logging to CloudWatch also gives us more ability to monitor what's happening on tools that we are more familiar with.
I expect we'll eventually ship the logs off to Splunk as well, …
=> Swap cache public WAF to CloudWatch logging

terraform/userdata/00-base
https://trello.com/c/CkRb8XcT/3003-audit-usage-of-alphagovcouk-domain-2
=> Stop using old alphagov.co.uk domain

terraform/modules/aws/network/nat/README.md, terraform/modules/aws/network/nat/main.tf, terraform/projects/infra-networking/README.md, terraform/projects/infra-networking/main.tf
This isn't enabled in our Tools environment, and causes us to not be able to apply the infra-networking project. See
https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/3892/console
=> Make AWS shield protection an opt-in feature

terraform/projects/app-accessibility-reports/main.tf, terraform/projects/app-data-science-data/main.tf, terraform/projects/app-govuk-rds/db_admin.tf, terraform/projects/app-knowledge-graph/main.tf, terraform/projects/app-related-links/main.tf, terraform/projects/app-search/main.tf
The AMI Owner ID that was needed to fix the central node_group module (here: https://github.com/alphagov/govuk-aws/pull/1626)  is also needed in 6 other places where AMI Owner IDs have been specified explicitly.
=> Add new Owner ID where specified in projects rather than centrally.

terraform/projects/infra-public-wafs/README.md, terraform/projects/infra-public-wafs/cache_public_rule.tf, terraform/projects/infra-public-wafs/variables.tf
The National Archives requires to crawl our content. We accept this, therefore, we need to allow their IPs to get through the cache-public-waf.
Trello: https://trello.com/c/3tnQrCBV/3036-add-national-archives-ip-addresses-to-allow-list
=> Allow external partner IPs to send traffic to us

jenkins.sh
Running a terraform build with the `destroy` action throws an error when the terraform version is v1.0+
This is because [the `-force` flag was deprecated in v1.0](https://community.harness.io/t/terraform-terraform-destroy-force-is-deprecated/863). For non-interactive execution of a `terraform destroy`, we now must supply `-auto-approve` instead. 
This PR changes the default `EXTRA` parameter on a `terraform destroy` to `auto-approve`, so that it will work on any build targetting v1.0+. 
We'll also need to work out how to deal with projects that target terraform v0.x. Options discussed include parsing the output of `terraform version` (fiddly and error-prone) or adding a new `COMMAND` option (say, destroy-v0 - but that would need adding to govuk-cli as well).
=> replace -force with -auto-approve for terraform v1.0+

terraform/lambda/CspReportsToFirehose/index.mjs, terraform/projects/infra-csp-reporter/lambda.tf
Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
This is to reduce the noise in the Content Security Policy reports. We
get a lot of reports related to things we don't have control over, such
as browser extensions or apps that inject scripts into browsers. A lot
of these are hosting providers for fonts.
This is just an effort to filter out the most prolific of the reports
and does not attempt to remove all non-reports. The theory is that if we
reduce the most common false-positives then an actual positive will be
quite evident from it's volume in comparison to other reports.
=> Filter out commonly reported blocked URIs from CSP reporter

terraform/projects/app-publishing-amazonmq/main.tf
PR #1655 introduced auto-generated passwords for AmazonMQ users. Now that we've tried connecting to the MQ using the `RABBITMQ_URL` format, the default 'special' characters (i.e. non-alphanumeric) cause problems when used in URLs. 
To prevent the need for all client apps to URL-encode the passwords, it's cleaner to just not include special characters in the passwords. I've also upped the length to 24 to compensate for the decreased complexity.
=> Stop URL-unsafe characters in auto-generated AmazonMQ passwords

tools/update-docs.sh
Builds were [failing at the docs check linting stage](https://github.com/alphagov/govuk-aws/actions/runs/3619471834/jobs/6100553287#step:7:45), as the version numbers generated in CI were using the version spec given in the `required_providers` block, whereas running locally (at least on Ubuntu) they were using the exact version numbers in the .hcl lock file. This mean that the instruction `You should run ./tools/update-docs.sh and commit the results.` did not fix the broken builds.
It looks like there was [a bit of back-and-forth on this with the developers](https://github.com/terraform-docs/terraform-docs/issues/517) but a `--lockfile` flag was introduced in [terraform-docs v0.15](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.15.0)
I assume the default setting for …
=> Add explicit --lockfile=false flag to terraform-docs invocation

terraform/projects/app-publishing-amazonmq/publishing-rabbitmq-schema.json.tpl
This makes it consistent with all the other usernames
=> update search-api username for AmazonMQ to search_api

terraform/projects/infra-public-wafs/README.md, terraform/projects/infra-public-wafs/cache_public_rule.tf, terraform/projects/infra-public-wafs/variables.tf
There are three steps to this:
- add a count only rate limit to allow us to monitor what happens at lower rate limits prior to reducing the blocking limit
- configure the existing rate limit to `block` instead of count and return 429, Cache-Control and Retry-After headers
- add a basic HTML response telling people what has happened should they fall foul of this limit
In future we may wish to do something better with the error page, such as writing VCL to retrieve a rendered one from S3, but I think this is OK for now. Based on the history of the limit we have set to `count` at present, it's only robots that will be affected.
https://trello.com/c/1B7DgFvt/3038-add-custom-response-headers-for-the-cache-public-waf
=> Apply rate limit

terraform/projects/app-rabbitmq/README.md, terraform/projects/app-rabbitmq/main.tf
Part of the [Trial AmazonMQ deployment process on integration](https://trello.com/c/oqsXryjz/389-update-monitoring-alerting-from-rabbitmq-amazonmq) epic. 
Nothing is publishing to or consuming from the self-hosted RabbitMQ on integration, we've [repointed all apps over to AmazonMQ](https://github.com/alphagov/govuk-puppet/pull/11930) now. However, the RabbitMQ instances are now (rightly) triggering Icinga alerts because they have no consumers connected, and other related alerts.
This PR updates the RabbitMQ auto-scaling group definition to use parameters for min, max, and desired size,, which are defined in [this govuk-aws-data PR](https://github.com/alphagov/govuk-aws-data/pull/1141)  to be 0 on integration only, and 3 everywhere else.  
We've tested (by deploying & applying this branch …
=> Use variables for RabbitMQ auto-scaling group sizes

terraform/projects/infra-fastly-logs/main.tf
See https://github.com/alphagov/govuk-cdn-config/pull/438
We're going to start logging the client JA3 fingerprint of each request.
We first need to edit the Fastly UI to start logging that, and then this PR makes the corresponding change in our AWS/S3 logging logic.
Trello: https://trello.com/c/LVGgeLG7/
=> Update AWS Glue to include client_ja3 data for www and assets

terraform/lambda/CspReportsToFirehose/index.mjs, terraform/projects/infra-csp-reporter/glue.tf
Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
Note, I've tried this out and it is operational. It is currently applied to integration.
---
The original policy is the CSP policy that is an effect when the
violation occurs. Initially I didn't include this as data stored as I
thought it would effectively be a constant - just the same data in every
report, as our policies have very low variances between URLs.
I've since found out that it seems to be common for ad-blockers to
rewrite policies and thus what might be in effect is not what we've set.
Therefore I actually think it could be valuable to store this
information. It may help with some of the more mysterious reports.
On initial testing I found that adding a column amongst existing …
=> Include original policy in CSP logged data

terraform/projects/infra-fastly-logs/main.tf
The default timeout is 3s, but this is not enough to run the functions.
The original ones have 2 min for DownloadLogsAnalytics and 10s for SendPublicAPIEventsToGA.
SendPublicAPIEventsToGA:
DownloadLogsAnalytics:
Trello card: https://trello.com/c/6hvNCAhx/2957-check-if-govuk-lambda-app-deployment-is-still-needed-and-retire-if-not
=> Update timeout for the analytics lambda functions

terraform/projects/infra-fastly-logs/main.tf
`send-public-events-to-ga` lambda function has a few `Task timed out after 10.08 seconds` errors.
Even though the original `SendPublicAPIEventsToGA`lambda function had 10s set as timeout, this was never seen in practice since the function always failed with other errors.
`DownloadLogsAnalytics` has the timeout set to 2m so we might want the same value for this too.
=> Update timeout for send-public-events-to-ga lambda

terraform/projects/infra-public-wafs/README.md, terraform/projects/infra-public-wafs/backend_public_rule.tf, terraform/projects/infra-public-wafs/standard_config.tf, terraform/projects/infra-public-wafs/variables.tf
This is mostly copied from the cache_public WAF.
We retain the x-always-block rule. This is the easiest way for Smokey to determine that a WAF is applied.
We retain the rule allowing traffic from GOV.UK's infrastructure. Smokey is the heaviest user here.
We do not need to specifically allow Fastly health checks, as they're not running against this resource.
We don't need to allow traffic from an external set of IPs, as we don't have that requirement here yet.
We keep a warning/count rate limit rule.
We'll set the "blocking" rule to count for now while we confirm that the rest works as expected.
For the rules we retain we do not need to parse the True-Client-IP header to identify the IP of the client. We have therefore switched aggregate key types from "FORWARDED_IP" (removing some of the …
=> Add a backend specific WAF

terraform/projects/infra-content-publisher/README.md, terraform/projects/infra-content-publisher/main.tf
Needed for alphagov/govuk-infrastructure#815.
```sh
tools/build-terraform-project.sh -c refresh \
-d ../govuk-aws-data/data -s govuk -p infra-content-publisher -e ${ENV?}
```
For each environment. No need need for `apply`.
New output is as expected in integration:
```
activestorage_s3_bucket_arn = arn:aws:s3:::govuk-integration-content-publisher-activestorage
```
Related: https://github.com/alphagov/content-publisher/pull/2705
=> Add an output for the content-publisher bucket ARN.

terraform/projects/infra-mirror-bucket/main.tf, terraform/projects/infra-public-services/waf.tf
Reverts alphagov/govuk-aws#1652
See https://github.com/alphagov/govuk-aws/pull/1652#issuecomment-1378923671 - the version of Node is incompatible with the old version of Terraform we have. I've decided to revert so that we have time to address this, rather than live with a broken Terraform project and wait for somebody to fix-forward.
Trello: https://trello.com/c/PMsAXSoT/3029-review-govuks-usage-of-node-2
=> Revert "Upgrade nodejs versions"

terraform/projects/infra-mirror-bucket/README.md, terraform/projects/infra-mirror-bucket/main.tf
The assets Cloudfront distribution was referencing the (expired)
cert in us-east-1, for `*.publishing.service.gov.uk` - which had
been manually created, thus not auto-renewed.
https://us-east-1.console.aws.amazon.com/acm/home?region=us-east-1#/certificates/108d0f34-cf9f-4e04-81a2-231e42824b08
Instead we should be using the certificate that's created and
managed in Amazon Certificate Manager (ACM), in the eu-west-1
region:
https://eu-west-1.console.aws.amazon.com/acm/home?region=eu-west-1#/certificates/063a18cc-d4bf-4eaf-b1c1-41e86bbdd69d
That cert covers a number of domains, including the necessary
`*.publishing.service.gov.uk`.
However, we can't simply change the [aws_cloudfront_certificate](https://github.com/alphagov/govuk-aws/blob/18f25c90e6f14208ada49a452d8e726e069ffb71/terraform/proj …
=> Reference different certificate for Cloudfront Production

terraform/projects/infra-mirror-bucket/README.md, terraform/projects/infra-mirror-bucket/main.tf
Successful `apply` in Integration:
https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/4797/console
Successful `apply` in Staging: https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/4795/console
See commits for details.
Trello: https://trello.com/c/PMsAXSoT/3029-review-govuks-usage-of-node-2
=> Bump NodeJS runtime version in infra-mirror-bucket

jenkins.sh
There has been some previous instances where developers have run `apply` using a branch that has a significant number of commits behind `main`.
Adding a warning message in the console output of the `plan` job should hopefully avoid confusion and potential incident due to being out of sync with `main`.
Co-authored-by: Catalina Ilie <catalina.ilie@digital.cabinet-office.gov.uk>
Example [console output](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/4905/console)
Trello card: https://trello.com/c/Po3ln1BC/3041-make-deploy-terraform-warn-when-ran-against-outdated-branch-3
=> Add warning messages if branches used are not main

terraform/projects/app-draft-cache/README.md, terraform/projects/app-draft-cache/main.tf
Adds security rules to allow AP to talk to RDS, needed for the Postgres switch.
NB: This adds elements, it does not remove any existing elements (ie it is safe to deploy even if we have to roll back, because the existing infrastructure for MongoDB is untouched)
Authenticating Proxy PR:
https://github.com/alphagov/authenticating-proxy/pull/350
Related PRs:
https://github.com/alphagov/govuk-aws-data/pull/1092
https://github.com/alphagov/govuk-puppet/pull/11967
https://github.com/alphagov/govuk-secrets/pull/1370
https://trello.com/c/lSpntlfk/81-mongo-26-has-reached-end-of-life
=> Allow authenticating-proxy to talk to RDS for Postgres

terraform/projects/app-publishing-amazonmq/main.tf
After [creating the AmazonMQ cluster on staging](https://trello.com/c/kdOCXjeM/437-create-amazonmq-ha-cluster-nlb-with-custom-domain-in-staging) as part of the [AmazonMQ migration process](https://trello.com/c/8a87xtft/428-run-amazonmq-migration-process-on-staging), we found that the passwords as listed in `terraform output` did not work when we tried to repoint the applications.
While [investigating](https://trello.com/c/zIYm3eUX/454-find-out-why-all-non-root-user-credentials-for-amazonmq-did-not-work-in-staging-when-deployed), we destroyed the stack and recreated it, to try and replicate the issue - the create [failed](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/4953/console)  with an error 
`│ Error: open /tmp/amazonmq_rabbitmq_definitions.json: …
=> Fix potential out-of-sequence AmazonMQ lambda invocation loophole

terraform/projects/infra-public-wafs/backend_public_rule.tf
This puts the WAF into blocking mode so that requests to apps behind the govuk_backend_public ALB will have a rate limit applied.
The limits are applied here: https://github.com/alphagov/govuk-aws-data/blob/2120cc8ff00012acc30123fb28bba883ca976f6c/data/infra-public-wafs/production/common.tfvars#L2 and are for the preceding 5 minutes, measured every 30 seconds.
https://trello.com/c/DQkJXVPJ/2810-set-backend-waf-rate-limit-rule-into-blocking-mode
=> Enable backend WAF

terraform/projects/app-publishing-amazonmq/production.blue.backend
Needed in order to [create AmazonMQ cluster in production](https://trello.com/c/RKnTTZv6/460-create-amazonmq-ha-cluster-nlb-with-custom-domain-in-production) as part of [running the AmazonMQ migration process in production](https://trello.com/c/to4fHvoa/458-run-amazonmq-migration-process-on-production)
=> Add production backend for app-publishing-amazonmq

terraform/projects/infra-public-wafs/README.md, terraform/projects/infra-public-wafs/bouncer_public_rule.tf, terraform/projects/infra-public-wafs/standard_config.tf, terraform/projects/infra-public-wafs/variables.tf
Bouncer lives behind a CDN, so this WAF is of a similar style to the [cache WAF](https://github.com/alphagov/govuk-aws/blob/main/terraform/projects/infra-public-wafs/cache_public_rule.tf) in the way it determines the original IP address.
It's stripped back to begin with so it only has the default x-always-block rule and a rule to count breaches of the rate limit.
This helps us determine whether we need to add any other rules to effectively manage legitimate traffic.
https://trello.com/c/z65OXqJ1/2845-bouncer-rate-limit-waf
=> Add rate monitoring WAF for Bouncer

terraform/projects/infra-mirror-bucket/README.md, terraform/projects/infra-mirror-bucket/main.tf, terraform/projects/infra-mirror-bucket/mirror-read-policy.tf, terraform/projects/infra-public-wafs/README.md, terraform/projects/infra-public-wafs/cache_public_rule.tf, terraform/projects/infra-public-wafs/variables.tf
- Allow traffic from EKS NAT gateways to S3 mirror buckets.
- In the WAF ratelimit exemptions, take the list of EKS NAT gateways from the new var in govuk-aws-data `data/common` instead of duplicating it in the module vars. (No diff from this, just avoid duplication.)
This fixes the Smokey probe failures for mirrors when running from the production EKS cluster.
Rollout: with alphagov/govuk-aws-data#1179. Already applied in production.
=> Add EKS egress addresses to IP ACLs.

terraform/projects/fastly-datagovuk/datagovuk.vcl
Also remove the (very outdated) list of Fastly netblocks since this is no longer required (Fastly support no longer need this in order to purge stuff if we need them to). We made the same change for the other GOV.UK services years ago.
Rollout: needs a `gds govuk t -e ${ENV?} -p fastly-datagovuk -s govuk -r govuk-${ENV}-admin -a plan  # followed by apply` for `ENV` in integration, staging, production.
=> Update data.gov.uk cache purge ACL to reflect EKS launch.

terraform/projects/infra-public-services/README.md, terraform/projects/infra-public-services/main.tf
These are no longer in use since the Kubernetes migration (and had been deleted, but it turns out this module is a bit more active than we thought so we need to get rid of them from here so they don't keep getting re-created).
The names that referred to these were deleted in https://github.com/alphagov/govuk-dns-tf/pull/17.
Tested: [`terraform plan` in integration](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/5199/console) (needs VPN, sorry)
=> Remove disused load balancers.

terraform/modules/aws/network/nat/main.tf, terraform/modules/aws/network/private_subnet/main.tf, terraform/modules/aws/network/public_subnet/main.tf
These were being wrapped in an extra list, i.e.
[['foo', 'bar', 'baz']]
instead of
['foo', 'bar', 'baz']
as expected by the modules which consume these outputs.
The semantics of the original TF 0.11 syntax for list values changed (in 0.12?) so this started returning the wrong type.
Rollout: already done; it seems only staging had been updated since the Terraform upgrade that broke this, and I've run `terraform refresh` there and now the consumer modules (such as `infra-public-services`) are working again.
=> Fix list outputs from networking modules.

terraform/projects/app-publishing-amazonmq/README.md, terraform/projects/app-publishing-amazonmq/main.tf, terraform/projects/app-publishing-amazonmq/publishing-rabbitmq-schema.json.tpl
We are retiring Cache clearing service. Monitoring will be removed later on.
[Plan output](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/5336/console)
[GIFT week summer 2023 card](https://trello.com/c/ENPwB2vT/41-retire-cache-clearing-service)
[Tech debt card](https://trello.com/c/TX9wLihh/101-cache-clearing-app-exists-and-we-dont-think-its-necessary-replacing-cache-clearing-app-only-clears-path-not-query-strings)
=> Remove cache_clearing_service from Publishing AmazonMQ

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
This simplifies the key policy statements for the SOPs and DocumentDB KMS keys.  The top level statement "Enable IAM User Permission" delegates all access control to IAM policies. 
```json
{
"Sid": "Enable IAM User Permissions",
"Effect": "Allow",
"Principal": {
"AWS": "arn:aws:iam::<aws_account_id>:root"
},
"Action": "kms:*",
"Resource": "*"
}
```
From [the AWS docs](https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-overview.html):
>When the principal in a key policy statement is an [AWS account principal](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-accounts) expressed as `arn:aws:iam::111122223333:root`, the policy statement doesn't give permission to any IAM principal. Instead, it gives the AWS account permission …
=> Simplify SOPs and DocumentDB KMS key policies

terraform/projects/infra-security/README.md, terraform/projects/infra-security/main.tf
The variables office_ip, stack name and the time resource are no longer used.
=> Remove unused Terraform in infra-security

terraform/projects/infra-public-wafs/README.md, terraform/projects/infra-public-wafs/licensify_backend_public_rule.tf, terraform/projects/infra-public-wafs/standard_config.tf, terraform/projects/infra-public-wafs/variables.tf
This is mostly copied from the cache_public WAF.
We retain the x-always-block rule. This is the easiest way for Smokey to determine
that a WAF is applied.
We keep a warning/count rate limit rule.
We'll set the "blocking" rule to count for now while we confirm that the rest works as
expected.
For the rules we retain we do not need to parse the True-Client-IP header to
identify the IP of the client. We have therefore switched aggregate key types
from "FORWARDED_IP" (with some additional configuration) to "IP". The different
rules have slightly different ways of configuring this:
- [rate based statement](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl.html#rate-based-statement)
- [IP set reference …
=> Add licensify backend waf

terraform/projects/infra-security-groups/README.md, terraform/projects/infra-security-groups/apt.tf, terraform/projects/infra-security-groups/ci-master.tf, terraform/projects/infra-security-groups/deploy.tf, terraform/projects/infra-security-groups/offsite_ssh.tf, terraform/projects/infra-security-groups/rabbitmq.tf, terraform/projects/infra-security-groups/support-api.tf, terraform/projects/infra-security-groups/variables.tf, tools/build-terraform-project.sh
We haven't had anything running in Carrenza/6degrees for years now.
Goes with https://github.com/alphagov/govuk-aws-data/pull/1253
Tested: applied in staging (see other PR for example plan output).
=> Clean up dangling ACL entries from Carrenza.

terraform/projects/fastly-datagovuk/datagovuk.vcl
Remove UTM query params as they have little effect on the backend.
Sort remaining query params so that the resulting URL has a greater chance of being cacheable/retrievable from cache.
Discard query params from the home page. The home page doesn't respond to query params, so there's little point in accepting them at the origin.
=> Improve DGU Fastly cache hit rate

terraform/projects/fastly-datagovuk/README.md, terraform/projects/fastly-datagovuk/main.tf, terraform/projects/fastly-datagovuk/remote_state.tf
It's not possible to plan/apply infrastructure changes in this project as we are now using Terraform version 0.12. 
Running a Terraform `plan` threw this error:
```
Error: Unsupported Terraform Core version
This configuration does not support Terraform version 0.12.30. To proceed,
either choose another supported Terraform version or update the root module's
version constraint. Version constraints are normally set for good reason, so
updating the constraint may lead to other errors or unexpected behavior.
```
The new changes have been tested running a `plan` - see the [console output ](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/5403/console)
Trello card: https://trello.com/c/lN55wEjL/3289-finish-retiring-contracts-finder-archive-3
=> Upgrade terraform version for Fastly DGU

terraform/projects/fastly-datagovuk/main.tf
We are retiring the service and deleting the [DGU AWS account](https://dgu.signin.aws.amazon.com/console) it lives in. The instance is not running and is unavailable.
The new changes have been tested running a plan - see the [console output](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/5409/console)
Trello card: https://trello.com/c/lN55wEjL/3289-finish-retiring-contracts-finder-archive-3
=> Remove proxy for the Contracts Finder Archive

terraform/projects/app-publishing-amazonmq/README.md, terraform/projects/app-publishing-amazonmq/main.tf, terraform/projects/app-publishing-amazonmq/publishing-rabbitmq-schema.json.tpl
- Add a new RabbitMQ user for `search-api-v2` with relevant permissions
- Add a `search_api_v2_published_documents` queue and binding to the `published_documents` exchange
=> Set up RabbitMQ for `search-api-v2`

terraform/projects/infra-public-wafs/cache_public_rule.tf
There’s nothing at https://gov.uk/autodiscover/autodiscover.xml, therefore, requests made from Microsoft Outlook to this URI path should be blocked as it is currently done through fastly VCL. Our goal is to remove VCL code, this PR is part of that work.
Trello: https://trello.com/c/tprMplI9/3293-move-logic-for-serving-an-http-404-if-request-url-matches-autodiscover-autodiscoverxml-from-cdn-to-waf-3
=> Block autodiscover

terraform/projects/infra-mirror-bucket/README.md, terraform/projects/infra-mirror-bucket/main.tf
[Trello card](https://trello.com/c/vhKRQfLu/3296-delete-the-old-static-cloudfront-distributions)
Depends on alphagov/govuk-aws-data#1261
It looks like someone has made some clickops changes inside the AWS console to:
- Disable replication from the primary mirror bucket to the replica in integration and staging
- Disable lifecycle rules on the replica in staging only
As a result, this project can't currently be applied, which is blocking #1760.
This commit contains the minimal changes required to make the Terraform match reality, so that it can be applied once again.
=> Update `infra-mirror-bucket` to match reality

terraform/projects/app-publishing-amazonmq/README.md, terraform/projects/app-publishing-amazonmq/main.tf
Quoth @aldavidson: "This is outdated and should be removed, as the TF was used in production 6 months ago".
[Trello](https://trello.com/c/lZp7YWgu/837-remove-the-do-not-use-in-production-yet-warning-from-the-amazonmq-terraform-projects-readme)
=> Remove outdated warning

terraform/projects/fastly-datagovuk/main.tf, terraform/projects/fastly-datagovuk/variables.tf
The variables now sit in variables.tf, as covered in https://developer.hashicorp.com/terraform/language/modules/develop/structure
I've tested the changed with a [plan](https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/5453/console) and the output looks fine.
=> Refactor fastly-datagovuk to standard structure

terraform/modules/aws/iam/gds_user_role/README.md, terraform/modules/aws/iam/gds_user_role/main.tf
Looks like this root module broke when a variable was removed in fc66fe83, but the iam/gds_user_role module required a value for that variable even though it wasn't in use.
Tested: plans locally, null diff.
=> Make infra-security module deployable again.

terraform/projects/app-publishing-amazonmq/publishing-rabbitmq-schema.json.tpl
Like the existing functionality in `search-api`, we want to add the
ability to enqueue a "bulk reindex/sync" for `search-api-v2`. This
deliberately listens to a different routing key from `search-api` to
avoid pointlessly reindexing documents there as part of any v2 work, and
uses the same queue as regular indexing for simplicity.
=> Add binding for search-api-v2 bulk sync

terraform/projects/app-govuk-rds/rds.tf
Context: https://aws.amazon.com/blogs/aws/rotate-your-ssl-tls-certificates-now-amazon-rds-and-amazon-aurora-expire-in-2024/
Tested: applied in staging, no sign of any apps failing to talk to databases, app probes all passing etc.
=> Switch from rds-ca-2019 to rds-ca-rsa2048-g1.

terraform/projects/app-govuk-rds/rds.tf
Mostly for https://github.com/alphagov/govuk-aws-data/pull/1272 so we can use micro instances for some databases that are really tiny (and quiet).
Tested: applied in integration and staging, plans cleanly in prod.
=> Make RDS Perf Insights configurable per instance.

terraform/projects/infra-datagovuk-organogram-bucket/main.tf
This is because when the data is synced between production and other environments, any organograms uploaded are referred to on the production s3 bucket which is not currently synced between environments.
https://trello.com/c/2qXYzZYb/1239-switchover-paas-apps-to-k8s-cluster
=> Allow integration and staging access to prod S3

terraform/projects/infra-datagovuk-organogram-bucket/main.tf
As all requests to data.gov.uk get re-routed to www, update the allowed_origins to reflect this
https://trello.com/c/2qXYzZYb/1239-switchover-paas-apps-to-k8s-cluster
=> Allow access to DGU buckets from www.{environment}

terraform/projects/infra-public-wafs/README.md, terraform/projects/infra-public-wafs/backend_public_rule.tf, terraform/projects/infra-public-wafs/cache_public_rule.tf, terraform/projects/infra-public-wafs/standard_config.tf, terraform/projects/infra-public-wafs/variables.tf
Make it clearer as to what the rule does. See:
- https://github.com/alphagov/govuk-aws-data/pull/1276
=> Rationalise ratelimit exemption rules.

terraform/projects/infra-fastly-logs/main.tf
Following https://github.com/alphagov/govuk-fastly/pull/41, this will allow us to analyse usage of HTTP/3, once it's enabled.
=> Parse the protocol field in Fastly logs

terraform/projects/infra-fastly-logs/main.tf
Terraform identifies these columns by their position in the list, so if we add a new one in the middle of the list it ends up renaming all the subsequent columns (so request_time gets renamed to be protocol, and so on), before adding a new column for the last one in the list.
This is not what we want, and it causes problems for Athena, which gets confused about the types of columns.
We can make our lives a lot easier by just adding the column to the end of the list, so terraform will just add the one we want.
=> Move protocol column to the end of the list

terraform/projects/infra-security/main.tf
This came out of a [recent security review](https://docs.google.com/document/d/1B2UM7FTe8goAiZUivTT_-9DIeC7tEvQ3ck19j_t27Ns/edit#heading=h.35nkun2) (access probably limited but it's not very exciting).
Also kinda moot right now cos pretty much everyone who has one of these "poweruser" roles also has a full admin role, but hopefully that won't be the case for too much longer.
Also "poweruser" should be "developer" but that's another issue.
=> `poweruser` roles should only allow rotating the user's own keys.

terraform/projects/infra-public-wafs/backend_public_rule.tf
[Trello card](https://trello.com/c/5nkX83ng/3404-3-implement-ja3-fingerprinting-on-the-waf-acl-used-by-our-publishing-apps)
Rationale: We recently added support (#1819) for JA3 denylisting on the backend_public ACL, but the only place we currently log JA3 fingerprints is in the WAF logs. Currently the backend_public ACL is configured to only log requests that were blocked or counted, so we have no way to find the JA3 fingerprints of traffic that was allowed, but that we want to add to the JA3 denylist.
This will increase the number of requests being logged by this ACL, but the amount is around the same order of magnitude as the volume of requests we already block (and therefore log) in the cache_public ACL. The `aws-waf-logs-backend-public-production` log group only has 1 month of …
=> Log all requests through backend_public WAF ACL

terraform/lambda/PostConfigToAmazonMQ/post_config_to_amazonmq.py, terraform/projects/app-publishing-amazonmq/main.tf, terraform/projects/app-publishing-amazonmq/outputs.tf, terraform/projects/app-publishing-amazonmq/publishing-rabbitmq-schema.json.tpl, terraform/projects/app-publishing-amazonmq/variables.tf
- Use an up-to-date Python runtime for the config Lambda.
- Use `aws_iam_policy_document` for better ahead-of-time checking.
- Fix the HTTP error handling in the lambda that uploads the config to RabbitMQ.
- Fix a JSON syntax error in the config template which was causing RabbitMQ 3.11 to reject the config.
- Use a map for the random_password resources, since we were putting them in a map for the template anyway.
- Eliminate the `publishing_amazonmq_instance_count` parameter.
- Remove unused provider declaration.
- Remove redundant comments.
Tested: applied in the integration and staging accounts.
https://github.com/alphagov/govuk-infrastructure/issues/1267
=> Further cleanup in MQ module.

terraform/projects/app-publishing-amazonmq/main.tf, terraform/projects/app-publishing-amazonmq/variables.tf
Make RabbitMQ 3.11.28 the default version. 3.11.28 is currently the latest version that Amazon MQ supports.
This has been soaking in integration and staging for a couple of days now.
Also get rid of the engine_type parameter; it's not useful as-is.
Rollout: I'm not gonna do the actual rollout via Terraform; this PR is just to update the stored config to match once we're done. https://github.com/alphagov/govuk-aws-data/pull/1286 reflects the intermediate 3.10 rollout.
https://github.com/alphagov/govuk-infrastructure/issues/1267
=> Roll out RabbitMQ 3.11 to production.

terraform/projects/app-publishing-amazonmq/main.tf, terraform/projects/app-publishing-amazonmq/publishing-rabbitmq-schema.json.tpl
We need a new queue in rabbitmq for the govuk chat app to consume new published document in order to update its vector database as soon as a new document is published in GOV.UK
=> Add govuk_chat_published_documents queue to rabbitmq

terraform/projects/app-publishing-amazonmq/publishing-rabbitmq-schema.json.tpl
Previously we didn't need to listen to this queue as chat didn't utilise any decisions based on the contents of RabbitMQ links. However the new features we're planning require this (checking history mode, parent document type) and thus I'm adding this.
This will result in a higher drastically higher quantity of content being ingested as the links queue is quite noisy.
=> Chat listen to links queue

terraform/projects/app-elasticsearch6/main.tf
One slightly unfortunate gotcha here is that the Project tag (note: capital P) is already used for "blue" or "govuk" stacks, alongside the "aws_stackname" tag.
Tags are case sensitive in AWS, so Project != project.
project with a lower case "p" is set as a cost allocation tag, while Project with an upper case "P" is not.
Having them both is probably a bit confusing, but I don't want to go too far down the rabbit hole here.
Eventually we should probably just remove the Project = blue / govuk tags from everything.
=> Tag elasticsearch resources with GOV.UK - Search

terraform/projects/app-elasticsearch6/main.tf, terraform/projects/app-related-links/main.tf, terraform/projects/app-search/main.tf
This was the security group that let us SSH into instances in the pre-replatforming world.
It no longer exists, but its ID is still in the now deleted infra-security-groups project's statefile.
None of these projects have been applied since the security group was deleted, but clearly they've all been removed from the security group (since it no longer exists). Or in the case of related links, they're probably just not applied at all.
This commit at least fixes an obviously broken bit of config, making it slightly more likely that we'd be able to apply these projects if we wanted to.
It's enough to fix app-elasticsearch6, which is the one I care about right now.
=> Remove references to sg_management_id

terraform/projects/app-publishing-amazonmq/README.md, terraform/projects/app-publishing-amazonmq/publishing-rabbitmq-schema.json.tpl, terraform/projects/app-publishing-amazonmq/variables.tf
There is a need from the govuk-chat app to be able to control the amount of delay that is used when a message from the govuk_chat_pulished_documents is retried. At the moment, a message will be retried immediately. The desired outcome is that we could have a message be sent away for a fixed amount of time before it is back in the queue.
The way we do this is we set a dead letter exchange for the govuk_chat_published_documents called govuk_chat_retry_dlx This dlx then send all incoming messages to a queue called govuk_chat_retry. this queue has a message-ttl value set and a dead letter exchange set to an exchange called govuk_chat_dlx. This last exchange route all incoming messages back to govuk_chat_published_documents.
The result of all this is that when a message is rejected in …
=> Add dead letter exchanges and queues to rabbitmq

terraform/projects/app-publishing-amazonmq/main.tf, terraform/projects/app-publishing-amazonmq/publishing-rabbitmq-schema.json.tpl, terraform/projects/app-publishing-amazonmq/variables.tf
Fix use of govuk_chat_retry_message-ttl variable
=> Fix use of govuk_chat_retry_message-ttl variable

docs/guides/environment-provisioning.md
We're closing Gandi account as we don't manage any domains there or use it for TLS certificates anymore.
https://github.com/alphagov/govuk-infrastructure/issues/1427
=> Remove references to Gandi.net and update link

terraform/projects/infra-security/main.tf
... as well as integration.
The idea here is to mirror from staging instead of integration, so that we can reduce the frequency that the integration databases are restored. See https://github.com/alphagov/govuk-helm-charts/pull/2719 for more context.
Initially, we need to allow reading from both environments, otherwise we'll break the current mirroring from integration. There's probably no harm in it being able to read both in the long term, but strictly speaking it should only need staging once we've switched it over.
This produces no-changes plans in integration and production. In staging we have:
Terraform will perform the following actions:
+ resource "aws_iam_policy" "google-s3-mirror" {
+ arn         = (known after apply)
+ description = "Allows a Google Cloud Platform project to …
=> Allow google_s3_mirror to read from staging
